### PR TITLE
Edited for style and grammar across all Quick Start docs

### PR DESCRIPTION
**Pull request by kurtgcollins**
**Summary**

Noticed a lot of future tense, passive voice, and general formatting/wording changes to be made.

**Test plan**

**A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Comment by kurtgcollins** [comment]
Relevant to #1632

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit c50257cb1ba5bfeef7aabd1b55525f19cef4ea3e

https://deploy-preview-1637--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit c50257cb1ba5bfeef7aabd1b55525f19cef4ea3e

https://deploy-preview-1637--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit dc7f0699e45a3747fe96f178814510c052f4812c

https://deploy-preview-1637--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit dc7f0699e45a3747fe96f178814510c052f4812c

https://deploy-preview-1637--cms-demo.netlify.com

**Pull request merged**
