### PR TITLE
feat: add definition list editor component

### PR DESCRIPTION
**Pull request by erquhart**
**Summary**

Hugo's Goldmark markdown parser supports definition lists - this component provides a way to edit them in Netlify CMS without editing raw values.

**Test plan**

Tests added.

### CODE REVIEW

**Comment by erezrokah** [comment]
I had an issue when testing it locally and creating a new definition list for an empty entry.

Default values are inferred from the fields list and always return a map, while the definition list expects a default value of an array. Not sure my approach is the best one, but couldn't think of a better way to do it atm.

**Comment by erezrokah** [comment]
FYI, tests are failing since `matchAll` is not supported in node 10. We can use this as an opportunity to remove the node 10 build.

**Comment by erquhart** [comment]
Good catch, can't believe I didn't try creating a new definition list 🤦‍♂ 

This is another example of a need for widgets to manage their own default values - the code you updated is leftover from when all widgets were object widgets. I'd rather not surface `defaultValues` in the API, looking for other options now.

**Comment by erquhart** [comment]
Doing this well requires a true inline mode for the markdown widget - if you can still create blocks (Eg., headers) through raw markdown, and the markdown widget still parses that markdown, that makes this editor component pretty unstable. Defaults handling is another problem uncovered here - if widgets can't handle their own, then upstream entities like editor components have to patch together a way to provide them. Closing for now.

**Pull request closed without merging**
