### PR TITLE
Docs: Link widget cloud to browser URL.

### LINKED ISSUE #934: Improve widget documentation linking and history
The widget docs now show each widget on a separate page thanks to the awesome improvements in #866. Things we should consider improving include:

* Using an actual hash for links (currently uses "/#<widget-name>"
* Updating browser history when a new widget docs link is clicked so that back/forward buttons work
* Allowing each widget doc page to be accessed only one way (currently "/#<widget-name>" and "/<widget-name>" both work, the former leading to the widget cloud view, the latter to the standalone generated page

### PR DESCRIPTION
**Pull request by tech4him1**
**- Summary**

Closes #934.
> Updating browser history when a new widget docs link is clicked so that back/forward buttons work

**- Test plan**

Manually tested.

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit e9d156c5360abfe5d1921dffa7221ebd43fc5af6

https://deploy-preview-1212--cms-demo.netlify.com

**Comment by verythorough** [comment]
Though I know it's not all that important, it would be nice if this worked without JavaScript, and it wouldn't be much of a change. All widgets in the `widgets__container` could be given the `widget-open` class in html, then use JS on load to remove all but one.  Then each `widgets__item` could be an `a` instead of a `span`, with an `href` pointing to the id.

**Comment by tech4him1** [comment]
@verythorough Sounds good, I'll work on adding that. If either of you would rather merge this and have a separate PR, I can do that as well.

**Comment by erquhart** [comment]
@tech4him1 whatever you prefer - just go ahead and merge this if you'd rather open a separate Pr.

**Pull request merged**
