### PR TITLE
feat: make lists empty by default

### LINKED ISSUE #3534: Can not set default value for empty list.
```
collections:
  - name: goods
    label: Goods
    create: true
    folder: 'static/data/goods/'
    format: json
    description: 'All goods'
    fields:
      - { name: 'title', label: 'goods name', widget: 'string' }
      - { name: 'description', label: 'goods description', widget: 'string', required: false }
      - { name: 'image', label: 'main image', widget: 'image' }
      - { name: 'price', label: 'price', widget: 'number', valueType: 'float' }
      - {
          name: 'detailImages',
          label: 'detail images',
          widget: 'list',
          field: { name: 'image', label: 'image', widget: 'image' }
        }
  - name: category
    label: Category
    create: true
    folder: 'static/data/category/'
    format: json
    description: 'All categories'
    fields:
      - { name: 'title', label: 'category name', widget: 'string' }
      - { name: 'description', label: 'category description', widget: 'string', required: false }
      - { name: 'image', label: 'category main image', widget: 'image' }
      - {
          name: goodsList,
          label: 'relative products',
          widget: list,
         ** default: [],**
          field: {
            name: 'goods',
            label: 'goods',
            widget: relation,
            collection: goods,
            valueField: title,
            searchFields: ['title'],
            displayFields: ['title', 'description', 'price']
          }
        }

```

Can not create a default `goodsList` value, and this key doesn't exist also:

```json
{
  "title": "test",
  "image": "/assets/test.png",
  "description": "test"
}
```

Expected:

```json
{
  "title": "test",
  "image": "/assets/test.png",
  "description": "test",
  "goodsList": []
}
```

### PR DESCRIPTION
**Pull request by guillett**
closes #3534

**Summary**

I think list should be empty by default.
That's actually what happens for typedList (because it relies on `types` and not `field` or `fields`).

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by erezrokah** [comment]
Thanks for pushing this @guillett.
This breaks the current behaviour of setting defaults for list field/fields.
For the following config:
```yml
collections:
  - name: goods
    label: Goods
    create: true
    folder: 'static/data/goods/'
    description: 'All goods'
    default: []
    fields:
      - { name: 'title', label: 'goods name', widget: 'string' }
      - {
          name: 'listWithField',
          label: 'Field List',
          widget: 'list',
          field: { name: 'string', label: 'string', widget: 'string', default: 'hello' },
        }
      - {
          name: 'listWithFields',
          label: 'Fields List',
          widget: 'list',
          fields: [{ name: 'string', label: 'string', widget: 'string', default: 'hello' }],
        }
      - {
          name: 'listWithTypes',
          label: 'Types List',
          widget: 'list',
          types:
            [
              {
                name: 'object',
                label: 'object',
                widget: 'object',
                fields: [{ name: 'string', label: 'string', widget: 'string', default: 'hello' }],
              },
            ],
        }
```
and creating a new entry,
before:
image
After:
image
I know there is an inconsistency with the `types` configuration, but that's another issue.

The fix also doesn't work with `types`.
For this config:
```
collections:
  - name: goods
    label: Goods
    create: true
    folder: 'static/data/goods/'
    description: 'All goods'
    default: []
    fields:
      - { name: 'title', label: 'goods name', widget: 'string' }
      - {
          name: 'listWithTypes',
          label: 'Types List',
          widget: 'list',
          types:
            [
              {
                name: 'object',
                label: 'object',
                widget: 'object',
                fields: [{ name: 'string', label: 'string', widget: 'string', default: 'hello' }],
              },
            ],
        }
```
Create a new entry, enter a title and save. The resulting file is:
```yaml
---
title: t
---
```

How about we change https://github.com/netlify/netlify-cms/blob/3e5ff7184604fd1f18a01c7223d0dc5d199f0eac/packages/netlify-cms-core/src/actions/entries.ts#L652 to `const defaultValue = item.get('default', list ? [] : null);`?
See here https://github.com/netlify/netlify-cms/commit/36c8f60572f387b65a946a7faabc67c26564019d

@barthc do you mind adding your thoughts on this? Linking https://github.com/netlify/netlify-cms/pull/2374 for context.

**Comment by smashercosmo** [comment]
Maybe it should be just possible to set 'default' as empty array?

**Comment by erezrokah** [comment]
Thanks @smashercosmo, that's even better. The list `default` value is only used for "simple" lists  at the moment (with no fields definition). Ideally one could use that value to populate complex lists structure. 
 
Also a workaround for the current issue is to add an item and remove it, which will output an empty list.

**Comment by barthc** [comment]
The closes fix for issue #3534 is a config like so:
```yaml
- label: 'List'
 name: 'list'
 widget: 'list'
 field: { label: 'String', name: 'string', widget: 'string', default: '' }
```
Which should give you a default `['']`.

> Thanks @smashercosmo, that's even better. The list default value is only used for "simple" lists at the moment (with no fields definition). Ideally one could use that value to populate complex lists structure.

I thought about allowing a top-level default value for `list` and `object` widget, but that would allow users to set anything as default which would break the UI #3524

I would go for this patch https://github.com/netlify/netlify-cms/commit/36c8f60572f387b65a946a7faabc67c26564019d as a fix but could be a breaking change for some users.

**Comment by erezrokah** [comment]
> I would go for this patch [36c8f60](https://github.com/netlify/netlify-cms/commit/36c8f60572f387b65a946a7faabc67c26564019d) as a fix but could be a breaking change for some users.

You're right about the breaking change. Also I noticed that patch makes the list widget inconsistent with other fields. For example if you have an optional string field, creating a new entry without changing the optional field will not output that field at all in the resulting file.
If we apply that patch, a list field will always show up in the output.
Maybe we can allow setting the default, and fix the issues related to values breaking the UI when they rise.
We can start by wrapping each widget with an error boundary and display a relevant error for that widget.

**Comment by guillett** [comment]
I am happy to get my PR replaced by a better one. To me the default proper default value for an empty string shoud be an empty list unless the `list` field as a default value with items for instance

```yaml
type: list
default: [{name: "ok"}]
fields:
  - name: name
    type: string
```

**Comment by barthc** [comment]
> Maybe we can allow setting the default, and fix the issues related to values breaking the UI when they rise.

hmm, ok so if we allow setting the default. We can start by making sure the default value for `list` is an array.

**Comment by erezrokah** [comment]
So to sum up:
1. Allow setting `default` for list widgets regardless if it is a "simple" list or a list with `field` or `fields` or `types`
2. If no `default` value is present output an empty array in the file (breaking change and inconsistent with other widgets behaviour).

I would skip number 2 since it is a breaking change (some users might rely on that key not being present).

**Comment by guillett** [comment]
Maybe it would be better to prevent `default` for `list` and have a `defaultLength` for them. Currently the default value for that field could be 1 and 0 in the next major version. For values > 0, the items could be generated with list item default logic.

`default` for lists is relatively hard to implement.

**Comment by erezrokah** [comment]
Closing in favour of https://github.com/netlify/netlify-cms/pull/3746.
I went with the smallest possible fix to that issue of being able to set an empty array as a default for complex lists.

**Comment by smashercosmo** [comment]
@erezrokah is this fix applicable for simple lists?
```
 - label: Posts
    name: posts
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Tags, name: tags, widget: list, allow_add: true, default: []}
      - {label: Body, name: body, widget: markdown}
```

**Pull request closed without merging**
