### PR TITLE
feature: Add `group by` to collection view (Issue 3614)

### LINKED ISSUE #3614: Add a "Group by" dropdown selector in the folder collection view
**Is your feature request related to a problem? Please describe.**
Given an example "scholars" folder collection with taxonomies "cohort" and "country" (grouped by Markdown frontmatter values), if I want to browse scholars by cohort, I can't easily do that in the folder view.

**Describe the solution you'd like**
Ideally there would be a dropdown "Group by" right next to "Sort by" in the collections list view. The selected dropdown value would then be used to group items in the list, like so:

Screenshot 2020-04-16 at 17 30 16

**Describe alternatives you've considered**
1. I could search for "2019" in the global search box, but that would return any post from any collection containing that term.
2. I could also sort by cohort and then view scholars sequentially (and potentially change the "summary" collection config variable to show their cohort in the listing), but that creates cognitive overload.
3. I could split the collection up into different collections with the "filter" collection config variable, but my understanding is that this creates separate collections, which is undesired for a use case like the above.

**Additional context**

### PR DESCRIPTION
**Pull request by KancerEzeroglu**
closes #3614

**Summary**

We could not create groups for posts/entries.
After adding the"view_groups" attribute in the config file to create groups, we will be able to group the posts/entries.

Screen Shot 2020-10-21 at 11 18 47

**Test plan**
This diff is ready for a quick initial review. It is working for the year option for now.
You can check it to see my direction.
Tests are not ready for now. I'll add it. 

**A picture of a cute animal (not mandatory but encouraged)**
giphy

### CODE REVIEW

**Comment by erezrokah** [comment]
@KancerEzeroglu thank you for adding those tests, I'm going to review this PR by the end of this week

**Comment by KancerEzeroglu** [comment]
> @KancerEzeroglu thank you for adding those tests, I'm going to review this PR by the end of this week

Thanks, @erezrokah :)

**Comment by erezrokah** [comment]
This looks very good. I'm going to follow up next week with some minor fixes once I finish them

**Review by erezrokah — APPROVED** [review]

**Comment by KancerEzeroglu** [comment]
Thanks @erezrokah 😄 
Checked out the changes you've made.

**Pull request merged**
