### PR TITLE
cover gitlab backend integration

### PR DESCRIPTION
**Pull request by erquhart**
**Summary**

Opening this early for visibility, discussion, and contribution.

This project's greatest weakness is its lack of testing. The lack of testing is, I think, mostly owing to a general awareness that the backends are by far the most needful of testing, but require considerable effort to test well. Being often busy with features and bugfixes, we tended to put this effort off. That's my theory, anyway. We've only avoided massive failure for the thousands of sites using Netlify CMS through diligence in writing and merging code.

This is not a scalable solution.

The project is now at a place where important and exciting contributions are being delayed to avoid the risk of bugs - a risk that is exponentially higher than it should be because of our lack of testing. This PR aims to get the ball rolling by doing the following:

1. provide a template for properly testing backends
2. completely cover the GitLab backend

### The plan

Netlify CMS is also difficult to test because it's a complete application. Requirements range from e2e coverage of a fairly complex React app to API mocking for the extensive integrations with services like GitHub and GitLab, and even testing integrations with external applications like the Uploadcare and Cloudinary media library widgets, which are completely external UI's loaded via script tags. Lots of ground to cover.

For this reason, we should keep our tests high level. Not necessarily e2e for everything, but at least at the integration level. For backends this means **we don't test the backend directly**, but instead sandwich it between [`backend.js`](https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-core/src/backend.js) and a fully mocked API via [nock](https://github.com/nock/nock), and testing _through_ the `backend.js` interface. This should help make the tests created here for GitLab maximally reusable for the other backends while avoiding the brittleness that comes with testing implementation details.

### Status
This PR is very much a work in progress. Lots of repetitive code that will be reduced once we get closer to the finish line and opportunities for meaningful optimization become more obvious.

### How to help
If you love testing and want to get in on the action, start by commenting and we'll get you involved! This is definitely an all-hands-on-deck effort.

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit b0dff33ea3798375028b5809136c2e9346276487

https://deploy-preview-1968--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 145ad73a67199a8601729c2ead8e6d8c480bbfa2

https://deploy-preview-1968--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit fc62a53597b1bd65112f05731d52aa7014b24910

https://deploy-preview-1968--cms-demo.netlify.com

**Comment by erquhart** [comment]
Thanks for the additions @barthc. I still would like to add testing for all backend methods.

**Comment by erquhart** [comment]
Going to merge this as is for now, at least establishes how backends can be mocked and tested.

**Pull request merged**
