### PR TITLE
Throw on unsupported format.

### LINKED ISSUE #797: Break on unsupported file format.
Currently, if an unsupported file format is set on a collection (`format: ini`), we simply assume that it should be saved as YAML front-matter (see #748 and #776). I think in this case, when the user has explicitly set a format, and we are not inferring at all, it makes more sense to just throw an "Invalid Config" error. @erquhart @Benaiah?

***Expanded discussion: https://github.com/netlify/netlify-cms/issues/776#issuecomment-347731448***

### PR DESCRIPTION
**Pull request by tech4him1**
**- Summary**

Closes #797.

If a format is specified that is unsupported, throw instead of just saving as markdown/frontmatter.

(Re)based on #795.

**- Test plan**

No regressions seen on `/example` site.
Threw if unsupported format set.

**- Description for the changelog**

Throw on unsupported format.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by tech4him1** [comment]
I'm not quite sure what to do about the duplication here -- `formatByExtension`, `formatByName`, and `supportedFormats` are almost exactly the same now, but they are all technically different. Ideas?

**Comment by tech4him1** [comment]
Looks like this is broken -- please don't merge.

**Comment by erquhart** [comment]
We won't merge as long as it's WIP, no worries.

**Comment by tech4him1** [comment]
OK, this should be ready for review again. The `markdown` and `html` explicit formats have been removed -- `format: frontmatter` and `extension: md` are the defaults, and you can set `extension: html` if you prefer.

**Comment by tech4him1** [comment]
@erquhart Please re-review before merge -- a few new commits were added.

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit dede8e063068820e9d58b46195d6c37f78992123

https://deploy-preview-831--netlify-cms-www.netlify.com

**Pull request merged**
