### PR TITLE
Fix broken bitbucket backend doc link

### PR DESCRIPTION
**Pull request by milesmatthias**
This is a simple doc update.

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 8f8e0f571d781f5fca17e66139d0420899fac4be

https://deploy-preview-1834--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 8f8e0f571d781f5fca17e66139d0420899fac4be

https://deploy-preview-1834--cms-demo.netlify.com

**Comment by tomrutgers** [comment]
The link you are changing is not broken. It is after the changes though..

**Comment by milesmatthias** [comment]
When I clicked the link on https://www.netlifycms.org/docs/add-to-your-site/, it took me to https://www.netlifycms.org/authentication-backends/#bitbucket-backend, which is a 404.

https://www.netlifycms.org/docs/authentication-backends/#bitbucket-backend is where the resource is, but double checking the site, and you're right, it's updated now.

I must have had a cached version in my browser when viewing.

**Pull request closed without merging**
