### PR TITLE
WIP: Use config schema definition for validation.

### PR DESCRIPTION
**Pull request by tech4him1**
**- Summary**

For https://github.com/netlify/netlify-cms/issues/487.

I was just thinking about the best method for config validation, and this seemed like a viable option. [@Benaiah's validator](https://github.com/Benaiah/netlify-cms-config-examiner-rewrite) may be better, but I think it's worth a comparison.

This kind of basic format definitely does have the downside of only being able to statically check things -- it would be harder, for example, to run most of the validations in `reducers/collections.js`.

**- Todo**

- [ ] Clarify error messages. Make human-readable.

**- Test plan**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit ff0e926a69aa5c190e1fbe5eae508fa013686485

https://deploy-preview-1305--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit ff0e926a69aa5c190e1fbe5eae508fa013686485

https://deploy-preview-1305--cms-demo.netlify.com

**Comment by erquhart** [comment]
Using a schema for this is a fantastic idea, love this!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tech4him1** [comment]
See https://github.com/netlify/netlify-cms/pull/1363

**Pull request closed without merging**
