### PR TITLE
Prepare CMS to be used as an npm module

### PR DESCRIPTION
**Pull request by biilmann**

### CODE REVIEW

**Comment by okonet** [comment]
I'm wondering why https://github.com/netlify/netlify-cms/pull/168/commits/d7d17df79a8f2176bd1a71423f0e3912a3cfaf90 is required to start using it as an npm module?

**Comment by okonet** [comment]
Should we setup semantic-release for it?

**Comment by biilmann** [comment]
The CSS linting is not related to the npm usage - but I'm removing it until we're sure it's not overwriting files - we've been loosing some CSS changes due to this...

**Comment by okonet** [comment]
Gotcha! Let's remove the stylefmt and git add then but leave the stylelint. I'll try to fix it soon.

**Pull request merged**
