### PR TITLE
chore: add Node.js 8 and 10

### PR DESCRIPTION
**Pull request by DanielRuf**
**- Summary**

This adds Node.js 8 and 10 for the tests on Travis CI to make sure that netlify successfully builds and runs on them.

**- Description for the changelog**

### CODE REVIEW

**Comment by tech4him1** [comment]
Looks like we'll need to go through and upgrade dependencies before Node v10 will work.

**Comment by DanielRuf** [comment]
> Looks like we'll need to go through and upgrade dependencies before Node v10 will work.

Thats what I did in the last commit. `upath` 1.0.4 is the issue in many projects.

**Comment by erquhart** [comment]
@DanielRuf the yarn lock update was by yarn and not a manual update right? (There's a popular recommendation to manually update upath in the lockfile when addressing this issue, just making sure).

**Comment by DanielRuf** [comment]
> @DanielRuf the yarn lock update was by yarn and not a manual update right? (There's a popular recommendation to manually update upath in the lockfile when addressing this issue, just making sure.) We should probably update the npm lockfile as well.

I ran `yarn upgrade webpack` so this should be fine.

**Comment by DanielRuf** [comment]
> I don't see the reason for upgrading webpack in this PR

This is actually needed to upgrade upath.

**Comment by DanielRuf** [comment]
The current upath version is limited to Node.js <= 9, see the failing test of the first commit.

**Comment by Benaiah** [comment]
A minor version bump to webpack seems fine to me to get this working - @talves am I missing something? Does this negatively affect the work on the webpack 4 upgrade?

**Comment by talves** [comment]
@Benaiah no, the upgrade has been merged. It just needs to be tested. I did not see the upath issue, that's all.

**Comment by erquhart** [comment]
@talves:

```
yarn why v1.5.1
[1/4] 🤔  Why do we have the module "upath"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "upath@1.0.4"
info Reasons this module exists
   - "chokidar" depends on it
   - Hoisted from "chokidar#upath"

$ yarn why chokidar
yarn why v1.5.1
[1/4] 🤔  Why do we have the module "chokidar"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "chokidar@2.0.3"
info Has been hoisted to "chokidar"
info Reasons this module exists
   - Hoisted from "webpack-dev-server#chokidar"
   - Hoisted from "webpack#watchpack#chokidar"
```

**Pull request merged**
