### PR TITLE
fix: use the sortable handle

### LINKED ISSUE #1614: Sorting in list widget doesn't work?
**Describe the bug**
Maybe I'm expecting a feature that doesn't exist but the list widget is supposed to be sortable by drag and drop right?  I can't see how it is...the drag handle doesn't trigger. After trouble shooting my own config.yml for a while I ended up testing on the demo site and it turns out it doesn't work there either...?

**To Reproduce**
1. Go to https://cms-demo.netlify.com/#/collections/settings/entries/authors
2. Try drag Mathias below Chris

**Expected behavior**
I would expect Mathias to end up below Chris

**Applicable Versions:**
Chrome 68, Safari 11.1.2

### PR DESCRIPTION
**Pull request by daddykotex**
**Summary**
Hi,

Thanks for the CMS. I've started to use it and it has evolved a bit. It's great. I found an issue with the reordering of the items. The issue is here https://github.com/netlify/netlify-cms/issues/1614.

fixes #1614

**Test plan**
I have no test plan, I'm very unfamiliar with React :/ (it took me long enough just to get that working haha).

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit aa2e060e7eae1af9c1e9fa0216c79860d89ea6cf

https://deploy-preview-1655--netlify-cms-www.netlify.com

**Comment by daddykotex** [comment]
I've fixed the `prettier` issue.

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 55910ddec663d78fce8fff53c7de1119db35e108

https://deploy-preview-1655--cms-demo.netlify.com

**Comment by daddykotex** [comment]
You can see the working result here: https://deploy-preview-1655--cms-demo.netlify.com/#/collections/settings/entries/authors

**Comment by erquhart** [comment]
Thanks @daddykotex! This was fixed in #1395, will be released soon.

**Comment by tech4him1** [comment]
Re-opening, as @erquhart's fix caused a regression. All markdown editor widgets are currently broken.

Closes #1672.

**Comment by erquhart** [comment]
Thanks @daddykotex! (and good catch @tech4him1)

**Pull request merged**
