### PR TITLE
Make object control pure (no extra imports).

### PR DESCRIPTION
**Pull request by tech4him1**
**- Summary**

Make the object widget use the editor control passed in as a prop instead of importing it separately.

**- Test plan**

Tested -- working correctly.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit b1b38197933000c95c91745c192934a673a4fcd6

https://deploy-preview-1446--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit b1b38197933000c95c91745c192934a673a4fcd6

https://deploy-preview-1446--cms-demo.netlify.com

**Comment by erquhart** [comment]
I actually started working on this Friday and would like to eliminate widgets wrapping their own children entirely instead of passing `EditorWidget` around. It'll give us a ton of control over individual widgets and set us up to fix nesting problems like validation and a11y handily. Pushed the [branch](https://github.com/erquhart/netlify-cms/commits/internalize-editor-control) up in case you're up for taking it forward.

So far it's showing widgets, but values aren't being updated properly for nested fields, likely `onChangeObject` is not being used correctly.

**Comment by tech4him1** [comment]
Awesome, I saw your note in #1410 before you updated it -- I think that's a better idea. Have a nice week!

**Comment by erquhart** [comment]
Dug into this a little more - passing in children _seemed_ like the "React" approach, but doing so via recursive mapping stops nested widgets from receiving props organically, which feels much more important than how we pass children.

I think your approach here was right, at least for now. Maybe we'll split the `EditorControl` component out so it doesn't need to passed via props, but that's a further improvement.

**Pull request merged**
