### PR TITLE
Fix test-repo crash on non-existent folder.

### LINKED ISSUE #1438: After login: TypeError: Cannot convert undefined or null to object
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
After logging in to Netlify CMS via the /admin/ page I get a console error of "TypeError: Cannot convert undefined or null to object"

The folder specified in my collection contains 2 markdown files and a javascript file which is a React component:

```
import React, { PureComponent } from 'react'

export default class PostPage extends PureComponent {
  render() {
    const { data } = this.props;
    return (
      <div>
        <span>{data.markdownRemark.frontmatter.date}</span>
        <h1>{data.markdownRemark.frontmatter.title}</h1>

        <p>{data.markdownRemark.frontmatter.title}</p>
        <div dangerouslySetInnerHTML={{
          __html: data.markdownRemark.html
        }} />
      </div>
    )
  }
}

export const query = graphql`
  query BlogPostQuery($slug: String!) {
    markdownRemark(fields: {
      slug:{
        eq: $slug
      }
    }) {
      excerpt
      frontmatter {
        title
        date(formatString: "DD MMMM YYYY")
      }
      html
    }
  }
`;

```

File structure:
file structure

I am using Gatsby as my static site generator.

Dependencies:

```
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "gatsby": "^1.9.270",
    "gatsby-image": "^1.0.52",
    "gatsby-link": "^1.6.40",
    "gatsby-plugin-netlify-cms": "^2.0.1",
    "gatsby-plugin-react-helmet": "^2.0.10",
    "gatsby-plugin-sharp": "^1.6.47",
    "gatsby-plugin-styled-components": "^2.0.11",
    "gatsby-source-filesystem": "^1.5.38",
    "gatsby-transformer-remark": "^1.7.42",
    "gatsby-transformer-sharp": "^1.6.26",
    "netlify-cms": "^1.9.0",
    "react-helmet": "^5.2.0",
    "styled-components": "^3.3.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write 'src/**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "prettier": "^1.12.0"
  }
}

```

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Navigate to the /admin/ page
2. Login
3. Error occurs

**- What is the expected behavior?**
I should navigate to the backoffice area of Netlify CMS with no errors.

**- Please mention your versions where applicable.**

Netlify CMS version: 1.9.0
Browser version: Chrome 67.0.3396.87

Node.JS version: 5.6.0
Operating System: Windows 10 Pro 64Bit (10.0.17134 Build 17134)

**- Please link or paste your `config.yml` below if applicable.**

```
backend: 
  name: test-repo

media_folder: static/assets

collections:
  - name: post
    label: Posts
    folder: src/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Create At, widget: date }
      - { name: body, label: Post, widget: markdown }
```

I am following along with a tutorial and I can confirm the same file structure works with the following dependencies:

```
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "gatsby": "^1.9.202",
    "gatsby-image": "^1.0.38",
    "gatsby-link": "^1.6.37",
    "gatsby-plugin-netlify-cms": "^1.0.8",
    "gatsby-plugin-react-helmet": "^2.0.5",
    "gatsby-plugin-sharp": "^1.6.47",
    "gatsby-plugin-styled-components": "^2.0.7",
    "gatsby-source-filesystem": "^1.5.21",
    "gatsby-transformer-remark": "^1.7.33",
    "gatsby-transformer-sharp": "^1.6.20",
    "react-helmet": "^5.2.0",
    "sharp": "^0.20.3",
    "styled-components": "^3.1.6"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "main": "n/a",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --trailing-comma es5 --no-semi --single-quote --write \"src/**/*.js\"",
    "test": "echo \"Error: no test specified\" && exit 1",
    "deploy": "gatsby build && gh-pages -d public -b master"
  },
  "devDependencies": {
    "gh-pages": "^1.1.0",
    "prettier": "^1.10.2"
  }
}
```

### PR DESCRIPTION
**Pull request by tech4him1**
**- Summary**

The test-repo backend was crashing if a different folder was specified in the config. Fixes #1438.

**- Test plan**
Manually tested.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by tech4him1** [comment]
This will need backported to v1 as well.

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 3c8cbc62ea3f023b0d9fe29624f027ae38ed5bf2

https://deploy-preview-1444--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 3c8cbc62ea3f023b0d9fe29624f027ae38ed5bf2

https://deploy-preview-1444--netlify-cms-www.netlify.com

**Comment by tech4him1** [comment]
@erquhart Can you pull this into v1 as well?

**Comment by erquhart** [comment]
@tech4him1 done, released in 1.9.2.

**Pull request merged**
