### PR TITLE
Add missing contributors.

### PR DESCRIPTION
**Pull request by tech4him1**
**- Summary**

Add missing contributors. Details from #902.

**- Test plan**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by tech4him1** [comment]
There isn't really a specific category for typo fixes, which we've had quite a few of, so I just put them under documentation.

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit b32070f8a47461b52028613066fb78c05063c531

https://deploy-preview-996--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit b32070f8a47461b52028613066fb78c05063c531

https://deploy-preview-996--cms-demo.netlify.com

**Comment by tech4him1** [comment]
@verythorough This should be all users that actually submitted a PR (so code or docs). Is there anyone else that you think needs added?

**Pull request merged**
