### PR TITLE
Fix DocSearch link alignment

### PR DESCRIPTION
**Pull request by pixelastic**
**- Summary**

The current live documentation website of Netlify CMS displays a scrollbar in the search dropdown menu:
image

This is due to the "Search by Algolia" link being slightly too offset on the right. This PR solves this by making the offset only apply to top-level links in the header, and not all links in the dropdown.

**- Test plan**

This is the new output after the slight change of markup. The content of the dropdown is correctly styled, while the top-level links keep their initial styling.
image

**- Description for the changelog**

Only applied link styling in the header to the top-level links.

**- A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit dfee28f03036ece191603596f84e3cc663e85f6b

https://deploy-preview-1080--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit dfee28f03036ece191603596f84e3cc663e85f6b

https://deploy-preview-1080--cms-demo.netlify.com

**Comment by pixelastic** [comment]
@verythorough Great talk at Fosdem yesterday by the way. You're really fast at deploying the previews! :sweat_smile:

**Comment by tech4him1** [comment]
@pixelastic Can you add yourself to the contributors list: https://github.com/netlify/netlify-cms/blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor

**Comment by pixelastic** [comment]
Done! :white_check_mark:

**Comment by erquhart** [comment]
@pixelastic p.s.: @verythorough isn't ignoring you, those deploy preview messages were generated by a bot she created :)

**Comment by verythorough** [comment]
lol, @pixelastic Thanks! 
(@erquhart I mentioned at my FOSDEM talk that people often think I'm just very fastidious about posting deploy preview comments. 😉  )

**Pull request merged**
