### PR TITLE
fix(typings): incorrect import in index.d.ts

### PR DESCRIPTION
**Pull request by smashercosmo**
**Summary**

Constants were imported from the incorrect path

**Test plan**

No testing needed

### CODE REVIEW

**Review by erezrokah — APPROVED** [review]

**Comment by smashercosmo** [comment]
Patch release needed. Because it breaks typescript projects with ```skipLibCheck: false```

**Comment by erezrokah** [comment]
> Patch release needed. Because it breaks typescript projects with `skipLibCheck: false`

Sure. I'll merge and release once the tests pass

**Comment by smashercosmo** [comment]
Hmm... I have a feeling, that in order this to work properly collectionTypes should be converted to TypeScript

**Comment by smashercosmo** [comment]
Locally I get this errors from TS
```
TS2439: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
TS2307: Cannot find module './src/constants/collectionTypes' or its corresponding type declarations.
```

**Comment by smashercosmo** [comment]
Seems like this works
```import { FILES, FOLDER } from 'netlify-cms-core/src/constants/collectionTypes';```

**Comment by smashercosmo** [comment]
I'll update the PR

**Review by erezrokah — APPROVED** [review]

**Comment by erezrokah** [comment]
Released in `netlify-cms-app@2.14.23`

**Comment by smashercosmo** [comment]
Alright, can confirm, this fixed the issue 🎉

**Comment by erezrokah** [comment]
Thank you for being on top of this 🚀

**Pull request merged**
