### PR TITLE
Fix #2469 : File collection entries not differentiated in Workflow

### LINKED ISSUE #2469: File collection entries not differentiated in Workflow
**Describe the bug**

Editorial workflow entries from the same file collection are not differentiated.

**To Reproduce**

1. Go the settings collection in the CMS demo: https://cms-demo.netlify.com/#/collections/settings
2. Edit and save each of the two entries in the collection.
3. Click "Workflow" in the navbar to view the entries in the editorial workflow

**Expected behavior**

The entries should be differentiated, at least using the label from the entry config, like the collection view does.

**Screenshots**

Screen Shot 2019-07-22 at 8 26 03 PM

### PR DESCRIPTION
**Pull request by Ananthakr**
**Summary**
Fixes #2469 

Editorial Workflow Entries like General Settings and Authors are not differentiated in the Workflow cards(because `title` is not available). 

In this PR, Added `Slug` as fallback for `title` if not available.(Couldn't get any entry like `label`, so went forward with `slug`)

**Test plan**
Screenshot 2019-08-19 at 10 51 19 PM

** Cute Animal Pic **
cute_dog

### CODE REVIEW

**Comment by erquhart** [comment]
Thanks for opening this! If you log `entry` the label should be in there somewhere, can you give that a shot?

**Comment by Ananthakr** [comment]
Tried that, but the label value comes in as `null` for all entries

**Comment by Ananthakr** [comment]
I did some digging and found that, while creating New Unpublished Entry on first edit, `label` field gets missed out in the `entry` that is being created.

To resolve that, we need to add `label` field in the `unpublishedEntryDraft` that is being saved in backend and add `label` field while fetching entries for workflow.

@erquhart Is this the right way to solve this issue?

**Comment by erquhart** [comment]
Better to pull it from the config, which is stored in redux.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Ananthakr** [comment]
Fetching from config little complex because `Settings` have a different structure(`Collections` -> `Settings` -> `Files` -> `General/Authors` -> `Label`) than the others(`Collections` -> `Posts` ->  `Label`).

It would be simple if we pass `Label` as a part of `metaData` of Unpublished Entry.

**Comment by erquhart** [comment]
Give that a spin and let me know if you run into any issues.

**Comment by Ananthakr** [comment]
It works. Thank you so much. 
Screenshot 2019-09-10 at 8 04 32 AM

**Pull request merged**
