### PR TITLE
Update Slate dependencies

### LINKED ISSUE #1432: Pasted text into markdown field and hit cntrl+z to undo and got an error page
I added a markdown type field to my page and after pasting a text block into it from my clipboard them command Z on my computer. I am sent to an error page, I can reliably reproduce this

Netlify CMS version: 1.7.0
Browser version: Chrome 67.0.3396.79
Node.JS version: 8.11.2
Operating System: Mac OSX 10.13.3

Config.yml - this is happening in the /about/our-team page in the leadership -> story field

```yml
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "content"
    label: "General Content"
    create: true 
    files:
      - file: "src/content/layout.md"
        label: "Layout"
        name: "layout"
        slug: "layout"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "header"}
          - {label: "Title", name: "title", widget: "string", default: "header"}
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Phone Number", name: "phone", widget: "string"}
          - {label: "Phone Number CTA", name: "phoneCTA", widget: "string"}
          - {label: "Phone Number icon", name: "phoneIcon", widget: "string"}
          - {label: "Header Links", name: "links", widget: "list", fields: [
              {label: Title, name: title, widget: string}, 
              {label: Description, name: description, widget: string},  
              {label: Url, name: url, widget: string, required: false },
              {label: Sublinks, name: sublinks, required: false, widget: "list", fields: [{label: Title, name: title, widget: string},{label: Url, name: url, widget: string}]}
            ]}
      
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    create: true 
    files:
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/about/mission-statement/index.md"
        label: "Mission Statement"
        name: "mission-statement"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "mission-statement"}
          - {label: "Hero Banner", name: "headerimagehero", widget: "object", fields: [{name: "background",label: "Background Image",widget: "image"},{name: "title",label: "H1 Title",widget: "string"},{name: "description",label: "Description",widget: "string"}]}
          - {label: "Top Heading", name: "topheading", widget: "string"}
          - {label: "The Problem reasons", name: "problemreasons", widget: "list", fields: [{name: "number",label: "Number",widget: "number"},{name: "description",label: "Description",widget: "markdown"}]}
          - {label: "Middle Text", name: "middletext", widget: "string"}
          - {label: "Blurbs", name: "blurbs", widget: "list", fields: [{name: "title",label: "Title",widget: "string"},{name: "description",label: "Description",widget: "string"}]}
          - {label: "Did You Know Section", name: "didyouknow", widget: "object", fields: [{name: "text",label: "Text",widget: "markdown"},{name: "didyouknowheading",label: "Did You Know Heading",widget: "string"}, { label: "Did You Know Reason", name: "didyouknowreason", widget: "object", fields: [{name: "number",label: "Number",widget: "number"},{name: "description",label: "Description",widget: "markdown"}]}]}
          - {label: "Bottom Text", name: "bottomText", widget: "markdown"}                 
          - {label: "Hubspot Form ID", name: "hubspotFormId", widget: "string"}     
      - file: "src/pages/about/our-team/index.md"
        label: "Our Team"
        name: "our-team"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "our-team"}
          - {label: "Leadership Team Heading", name: "leaderHeading", widget: "object", fields: [{name: "heading", label: "Heading", widget: "string"}, {name: "description", label: "Description", widget: "string"}]}
          - {label: "Leadership Team", name: "leaders", widget: "list", fields: [{name: "fullName", label: "Full Name", widget: "string"},{name: "role", label: "Role", widget: "string"}, {name: "headshot", label: "Headshot", widget: "image"}, {name: "almaMater", label: "Alma Mater", widget: "string"}, {name: "major", label: "Major", widget: "string"}, {name: "petName", label: "Name of Pet", widget: "string"}, {name: "secondBestLanguage", label: "Second Best Language", widget: "string"}, {name: "story", label: "Story", widget: "markdown"}, {name: "background", label: "Background", widget: "markdown"}]}
          - {label: "Employee Team Heading", name: "employeeHeading", widget: "object", fields: [{name: "heading", label: "Heading", widget: "string"}, {name: "description", label: "Description", widget: "string"}]}
          - {label: "Employees", name: "employees", widget: "list", fields : [{name: "fullName", label: "Full Name", widget: "string"},{name: "role", label: "Role", widget: "string"}, {name: "image", Label: "Headshot", widget: "image"}]}
          - {label: "Board Heading", name: "boardHeading", widget: "object", fields: [{name: "heading", label: "Heading", widget: "string"}, {name: "description", label: "Description", widget: "string"}]}
          - {label: "Board", name: "board", widget: "list", fields: [{name: "fullName", label: "Full Name", widget: "string"},{name: "role", label: "Role", widget: "string"}, {name: "image", Label: "Headshot", widget: "image"}, {name: "story", label: "Story", widget: "markdown"}]}
      - file: "src/pages/apply/essay-editing/index.md"
        label: "Essay Editing"
        name: "essay-editing"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "mission-statement"}
          - {label: "Hero Banner", name: "headerimagehero", widget: "object", fields: [{name: "background",label: "Background Image",widget: "image"},{name: "title",label: "H1 Title",widget: "string"},{name: "description",label: "Description",widget: "string"}]}
          - {label: "Top Heading", name: "topheading", widget: "string"}               
          - {label: "Top Section Left", name: "topSectionLeft", widget: "markdown"}             
          - {label: "Top Section Right", name: "topSectionRight", widget: "markdown"}           
          - {label: "Essay Step Examples", name: "essayStepExamples", widget: "list", fields: [{name: "heading", label: "Heading", widget: "string"},{name: "description", label: "Description", widget: "string"},{name: "example", label: "Example", widget: "image"}]}       
          - {label: "Essay Ideation Process", name: "essayIdeationProcess", widget: "object", fields: [{name: "title",label: "Title",widget: "string"},{name: "ideationItems", label: "Ideation Items", widget: "list", fields: [{ name : "title", label : "Title", widget: "string"}, {name: "description", label: "Description", widget: "text"}]} ]}       
          - {label: "Additional Application Services", name: "applicationServices", widget: "object", fields: [{name: "title",label: "Title",widget: "string"},{name: "ideationItems", label: "Ideation Items", widget: "list", fields: [{ name : "title", label : "Title", widget: "string"}, {name: "description", label: "Description", widget: "text"}]} ]}       
          - {label: "Hubspot Form ID", name: "hubspotFormId", widget: "string"}        
```

### PR DESCRIPTION
**Pull request by robertkarlsson**
Fixes #1432
Update Slate and Slate plugin dependencies to be up to date with current versions.
Change setBlock -> setBLocks according to deprecation warning in slate 0.33.0
Change node.kind -> node.object according to deprecation warning introduced in Slate 0.32.0
Update Jest snapshot to pass the change from node.kind -> node.object

**- Summary**

Update Slate and Slate plugin dependencies to be up to date with current versions to fix Bugs produced by slate rather than Netlify CMS itself.

Fix breaking changes and deprecation warnings.
Also update package.json and package.lock.json (This seems to have been missed since the version did not match with the package.json).

**- Test plan**

Tests are passing, jest snapshot is updated.
Manually tested editor and fixed deprecation warnings about renaming kind to object in slate objects, see: https://github.com/ianstormtaylor/slate/blob/master/packages/slate/Changelog.md#breaking-2
Manually tested editor and fixed deprecation warnings about renaming setBlock to setBlocks, see:
https://github.com/ianstormtaylor/slate/blob/master/packages/slate/Changelog.md#deprecated-1

I'm not confident enough with this product to cover for all the breaking changes (the ones touching the lower levels of Slate) so this needs to be overlooked. See https://github.com/ianstormtaylor/slate/blob/master/packages/slate/Changelog.md for full changelog.

For the plugins, the only breaking change that is not in the low level aspect of slate is in slate-react which is also connected to
"kind" being renamed to "object". It should be covered by this PR.

The editor works as expected. All default fields tested and no errors
image (Tested on staging env)

**- Description for the changelog**

Update Slate and Slate plugin dependencies to be up to date with current versions.

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit ca912c965301c2d028a4b69f994263ac398616f5

https://deploy-preview-1451--cms-demo.netlify.com

**Comment by robertkarlsson** [comment]
Misspelled the setBlocks so fixed it and squashed. Is there any way to trigger a redeploy for the preview? Or do i have to make a new pr?

**Comment by robertkarlsson** [comment]
Need to look through the changelogs for the plugins as well, forgot to do that

**Comment by tech4him1** [comment]
@robertkarlsson The preview will update automatically with the latest commit. Also, you don't have to squash unless you want to, we normally do it at merge anyway.

**Comment by robertkarlsson** [comment]
I've updated the "test" section of the PR. From my testing this works, but I'm not 100% sure what to test except the editors default behaviour.

**Comment by papandreou** [comment]
I've cherry-picked this fix to my fork and done some light testing. It seems to work, and I can confirm that https://github.com/netlify/netlify-cms/issues/1432 no longer happens.

**Comment by papandreou** [comment]
Oh, we just found a pretty serious regression: When this change is applied, adding a new editor component adjacent to an existing one will overwrite it.

Steps to reproduce:

1. Define an editor component, eg.:

```js
CMS.registerEditorComponent({
  id: 'youtube',
  label: 'Youtube',
  fields: [
    {
      name: 'id',
      label: 'Youtube Video ID',
      widget: 'string'
    }
  ],
  pattern: /^youtube (\S+)$/,
  fromBlock: function(match) {
    return { id: match[1] };
  },
  toBlock: function(obj) {
    return 'youtube ' + obj.id;
  },
  toPreview: function(obj) {
    return (
      '<img src="http://img.youtube.com/vi/' +
      obj.id +
      '/maxresdefault.jpg" alt="Youtube Video"/>'
    );
  }
});
```

2. Click a markdown field
3. Insert a Youtube component via the dropdown
4. Insert another Youtube component via the dropdown

Observe that the youtube that was first added gets replaced with the new one instead of being added alongside it.

**Comment by robertkarlsson** [comment]
@papandreou Does it produce any errors together with it? Also, does it replace the previously added component if that component had been interacted with before adding the second one?

**Comment by papandreou** [comment]
@robertkarlsson,

> Does it produce any errors together with it?

No, nothing is logged in the developer console, at least.

> Also, does it replace the previously added component if that component had been interacted with before adding the second one?

Yes, it replaces the previously added component whether or not it has been interacted with. Even if the  other component was persisted and the CMS was reloaded.

**Comment by robertkarlsson** [comment]
@papandreou I've identified why this happens but is a bit unsure about the code that triggers it.

When adding a plugin component in the slate editor it checks the text of something called focusBlock, that comes from change.value.

 If the text-attribute of focusBlock is an empty string, it runs change.setNodeByKey(focusblock.key, block) which seems to manipulate the block in focus, which in this case is the previously added block as i understand it (the youtube vid).

https://github.com/netlify/netlify-cms/blob/a2cacac0e5cd92240d64fe120cd91f1e527f6613/src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/index.js#L159

If the text attribute of the focusBlock is anything else than an empty string, it runs change.insertBlock(block) which seems to insert a new block (youtube  instead of manipulating an already existing one. 

https://github.com/netlify/netlify-cms/blob/a2cacac0e5cd92240d64fe120cd91f1e527f6613/src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/index.js#L161

Making the code only run the else clause fixes the problem @papandreou describes, but I guess the .text check is there for a reason. I can't figure out why we would like to check for an empty string in this case though, but I'm probably missing something about how the plugins work.

Someone who has a better understanding of the system as a whole who can take a quick look at this?

@tech4him1 @erquhart

**Comment by robertkarlsson** [comment]
I took another look at this and I think I got the answer to my question asked a month ago. As explained, the problem here is the empty string check on the focusBlock. My understanding now is that the empty check is there to make plugins (youtube videos etc) replace empty paragraphs if that is what the current focusBlock is.

I've added a type check for the focusBlock and specifically check that it's a paragraph, else it inserts a new block instead of replacing. The problem explained by @papandreou do no longer occur.

I compared the output for the focusBlock when using the shortcode block type in the master / my branch versions of slate. The only difference I could find was that in the master version the focusBlock.text is " " in master, and after upgrading slate focusBlock.text is "", therefore causing the problem.

Changing line 143 to add a " " instead of "" semi-fixed the problem (worked if you added text to the top block in the editor, else not) but i think adding the check for the focusBlock type is a nicer solution. 

@tech4him1  @erquhart @papandreou 

Can you confirm if this solution seems valid?

**Comment by papandreou** [comment]
@robertkarlsson, great! I can speak to the fix itself, but I can confirm that the problem I reported no longer occurs with the latest commits on https://github.com/robertkarlsson/netlify-cms/tree/rk-update-slate-dependencies :hugs:

**Comment by erquhart** [comment]
Sorry guys, got buried in the monorepo stuff, but this PR will get attention very soon. Thanks so much for digging into this @robertkarlsson!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by robertkarlsson** [comment]
This got lots of conflicts, I'll see if if a quick squash and rebase can solve the component files later today. package-lock and jest snapshot should just require a re-generate.

**Comment by robertkarlsson** [comment]
Conflicts solved and files updated. Haven't re-tested but can do tomorrow.

**Comment by robertkarlsson** [comment]
@erquhart Rebased on latest master and quickly tested. Seems to behave like it did before the monorepo update, so it currently works.

**Comment by erquhart** [comment]
Alright, I'll definitely review this soon.

**Comment by papandreou** [comment]
@robertkarlsson, unfortunately this seems to have broken drag'n'drop of editor components: #1738

I didn't notice that when I tested this change the first time :(

**Pull request merged**
