### PR TITLE
Mention Gitter channel in the Community section

### PR DESCRIPTION
**Pull request by ragasirtahk**
**- Summary**
This is in reply of https://github.com/netlify/netlify-cms/pull/1054#issuecomment-362719061

**- Test plan**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 4d7c6921b3c7008e0d66a04a788386c6530f90cb

https://deploy-preview-1072--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 4d7c6921b3c7008e0d66a04a788386c6530f90cb

https://deploy-preview-1072--cms-demo.netlify.com

**Comment by ragasirtahk** [comment]
I deleted the repo and branch yesterday due to some reasons. Will the changes be done or I need to create a new pull request?

**Comment by tech4him1** [comment]
Looks like it merged correctly, thanks!

**Pull request merged**
