### PR TITLE
optimize webpack dev config for use w linked pkgs

### PR DESCRIPTION
**Pull request by erquhart**
Improved support for developing with locally linked dependencies.

### CODE REVIEW

**Comment by Benaiah** [comment]
@erquhart what is the effect of this change? This diff seems at first glance like it could be incompatible with older versions of npm that don't do a flat install if those two packages aren't explicit dependencies of the package including `netlify-cms`.

**Comment by erquhart** [comment]
Hmm didn't try other versions of npm, tested on 4.2.0.

When you link dependencies for local development, webpack tries to get dependencies relative to those linked packages, which isn't an option for dev dependencies like babel-loader. This forces webpack to stick with netlify-cms/node_modules for development.

**Comment by Benaiah** [comment]
I see - this shouldn't cause issues then, as `./node_modules/netlify-cms/node_modules/<dependent package>` will always exist, regardless of whether it's installed flat (in which case it'd be a symlink, IIRC) or deep (in which case it'd be an actual folder).

**Comment by erquhart** [comment]
Seems to work fine in npm 2.

**Pull request merged**
