### PR TITLE
WIP: Bitbucket integration update

### PR DESCRIPTION
**Pull request by george-oakling**
WIP: List of changes:
listFiles: return all files with pagination support
hasWriteAccess: the original implementation worked only for my own repositories, not the ones which are owned by another organizations, so I did this simpler implementation

**- Summary**

Update bitbuket implementation.

**- Description for the changelog**

listFiles: get all pages
hasWriteAccess: if returned object, you have access to repo. Original implementation didn't work for me.

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 0da8284f4527d9aee247df7924130ecaa92bf37e

https://deploy-preview-1098--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 0da8284f4527d9aee247df7924130ecaa92bf37e

https://deploy-preview-1098--cms-demo.netlify.com

**Comment by pogo19** [comment]
Hey, thanks for your effort. I've tried using netlify/netlify-cms#bitbucket-integration and also with your changes  .... and I see "Login with Bitbucket" that doesn't work for me. After giving permissions in Bitbucket I see only "undefined" bubble. Any idea what I do wrong?

**Comment by erquhart** [comment]
@pogo19 it won't work on localhost until we fix the freebie oauth service that's used there.

**Comment by erquhart** [comment]
Closing in favor of #1504.

**Pull request closed without merging**
