### PR TITLE
add docs menu sections

### PR DESCRIPTION
**Pull request by erquhart**
* Splits docs menu into "Quick Start", "Guides", "Reference", and "Contributing" sections.
* Uses Hugo's built in menu functionality
* Removes extraneous `list.html` template for docs and updates `single.html` to cover all cases (we don't actually have a list view, it was mostly duplicate code).

This will need to be ported into the upcoming Gatsby rewrite (cc @zebapy), but this is from a while ago and should be replicated in any migration.

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 0bed27e8804f1e4125bebe772133720c93eb131a

https://deploy-preview-1366--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 0bed27e8804f1e4125bebe772133720c93eb131a

https://deploy-preview-1366--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Woot! Glad to see this improvement. I may propose some changes to the groupings, but any grouping at all is a huge boost. :)

**Comment by zebapy** [comment]
So `architecture.md` and `customization.md` are excluded from menu on purpose now?

**Comment by verythorough** [comment]
Ah, good point! I suspect this may be because these changes were originally part of the Preview API docs PR, #1311. Until the new Preview API is implemented, though, I imagine we want to keep the docs for the current API in place. 
I'm thinking maybe Architecture could go under "Contributing," and `customization.md` would be "Creating Custom Previews" under "Guides."

**Comment by erquhart** [comment]
Good catch @zebapy, I'll add those back.

**Pull request merged**
