### PR TITLE
feat: add french translation

### PR DESCRIPTION
**Pull request by djhi**

### CODE REVIEW

**Comment by erezrokah** [comment]
Great work @djhi!
I cherry picked your commit to this pull request https://github.com/netlify/netlify-cms/pull/2884 and added a missing export for the locale.
Also creating a feature branch for pull requests is preferred instead of using the fork master branch.

**Comment by djhi** [comment]
Thanks @erezrokah! Any idea about when the locales support will be released ?

**Comment by erezrokah** [comment]
I'll have to check with @erquhart when we can get a new release published

**Comment by benavern** [comment]
Great! I was planning to create this too, you've done it faster than me :) Can't wait to have it released!

**Pull request closed without merging**
