### PR TITLE
Add simple color widget

### PR DESCRIPTION
**Pull request by ekoeryanto**
It adds simple native color widget

it is hard to remember all the color code.
**- Test plan**

image

**- Description for the changelog**
Add simple color widget

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by ekoeryanto** [comment]
I've read your comment, that's good idea. I'll try to implement it with [casesandberg/react-color](https://casesandberg.github.io/react-color/)

**Comment by ekoeryanto** [comment]
one more, I think it is better to make the type of value consistent, `string` for example
so format hsl will be `hsla(0, 0, .20, 1)` or `hsl(0, 0, .20)`, what you think @erquhart ?

**Comment by erquhart** [comment]
I'd still like to see RGB and hex options, but yeah definitely a string, agreed.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ekoeryanto** [comment]
> I'd still like to see RGB and hex options

that's configurable via `config.yml`
```yml
label: "Theme Color"
name: "color"
widget: "color"
format: "hsl" # options: hsl, rgb or hex
```

**Comment by erquhart** [comment]
Awesome work @ekoeryanto! I'll dig into this soon.

**Comment by ekoeryanto** [comment]
Thanks, I have one more widget, Icon widget. but I'm not sure to include it here as it will be a big size js.
I currently have (not published yet) fontawesome widget and material-icon-widget.
used [here](https://github.com/pakeweb/apek/blob/master/static/admin/config.yml)

**Comment by erquhart** [comment]
Would you be up for providing these as third party widgets in their own repos and maintaining them there? You can add me as a collaborator to help maintain, and when we hit v2 and have "official" plugins split out into a Netlify CMS monorepo, you could move your packages here at that point.

What do you think?

**Comment by ekoeryanto** [comment]
Yes i am up and running on that 🏃

**Comment by erquhart** [comment]
Awesome! So again, no docs yet on this, so give @Benaiah, @tech4him1 and @talves a chance to chime in before implementing the stuff below, but I expect we'll recommend:

* Naming your npm package "netlify-cms-widget-<name>", e.g. `netlify-cms-widget-color-picker`
* Providing a single widget per package as the main export, so a dev can do:
  ```
  import CMS from 'netlify-cms'
  import ColorWidget from 'netlify-cms-widget-color-picker'
  
  CMS.registerWidget('color', ColorWidget)
  ```
* Have your package also assign the widget to a sensibly named global, so sites that don't use a js build system can do:
  ```
  const ColorWidget = window.ColorWidget
  window.CMS.registerWidget('color', ColorWidget)
  ```
* Publish as 0.x for now, as things might change pretty quickly. You're the first external widget author!! 🚀

**Comment by talves** [comment]
@Benaiah @tech4him1 @erquhart This will also follow the pattern we need to take for other mono-repo strategies like backends and previews. Should we think about starters as a base? Ideas?

**Comment by ekoeryanto** [comment]
@talves haha... I'm to writing the starter right now. trying which is better rollup or webpack as a bundler.

**Comment by talves** [comment]
@ekoeryanto I created the Netlify CMS bundle starter with a `create-react-app`  because it was the most out of the way setup with very little config. I am wondering if that is where we should start for most of these bundles.

**Comment by erquhart** [comment]
Throwing together a quick widget starter repo, one sec...

**Comment by erquhart** [comment]
@ekoeryanto I'll get a readme up tomorrow and steps for local dev, but here's the first iteration of the widget starter: https://github.com/netlify/netlify-cms-widget-starter

`npm start` for a non-optimized build and watch for changes
`npm run build` for a production build

**Comment by erquhart** [comment]
Update: the starter now has a development environment and instructions in the readme.

**Comment by ekoeryanto** [comment]
Hello, I close this and move to my ekoeryanto/netlify-cms-widgets mono repo

**Pull request closed without merging**
