### PR TITLE
sortableFields have default sorting option

### LINKED ISSUE #3715: sortableFields should have default sorting options
**Is your feature request related to a problem? Please describe.**

Whenever I log into Netlify CMS, I have to always do the same operation so that the entries of a folder collection is displayed the way I'd like.

**Describe the solution you'd like**

I'd like if we could have an option in the `sortableFields` config so that we could specify a default order and display type. So for instance we could specify something like:

```yml
sortableFields:
  display: "grid"
  key: "commit_date"
  type: "desc"
  fields:
    - "commit_date"
    - "author"
    - "title"
````

### PR DESCRIPTION
**Pull request by KancerEzeroglu**
closes #3715 

**Summary**
We couldn't set the default sortable field from the config file.
With my changes, it can happen.
You can specify the sortable fields like below:
```
sortable_fields:
   - field: title
      direction: 'Descending'
   - field: date
```

**Test plan**
I haven't added the tests in the code (I've removed those that belong to the sortable fields test).
I would like to be sure my direction is right.

**A picture of a cute animal (not mandatory but encouraged)**

giphy

### CODE REVIEW

**Review by erezrokah — CHANGES_REQUESTED** [review]
Hi @KancerEzeroglu and thank you for this.
A few comments:
1. We would like to keep the config backwards compatible. With this PR anyone with existing `sortable_fields` will have to update their config. We can add migration code here:
https://github.com/netlify/netlify-cms/blob/567438fdd1aa775fd09a6a5de13e79c9d783e0d6/packages/netlify-cms-core/src/actions/config.js#L283

2. The current suggested API allows setting multiple fields as the default which is not supported by the UI. We can use something like:
```yaml
sortable_fields: { names: ['title','date'], default: name, direction: descending }
```

3. I think it would be better to initialize the default sort [in the reducer](https://github.com/netlify/netlify-cms/blob/567438fdd1aa775fd09a6a5de13e79c9d783e0d6/packages/netlify-cms-core/src/reducers/entries.ts#L145) to avoid the UI refreshing after initial load.

WDYT?

**Comment by KancerEzeroglu** [comment]
Sorry for the late reply @erezrokah 
I will work on what you have written and get back to you. 
Thank you for your review.

**Comment by KancerEzeroglu** [comment]
> The current suggested API allows setting multiple fields as the default which is not supported by the UI. We can use something like:
> sortable_fields: { names: ['title','date'], default: name, direction: descending }

In the future, we can enable users to do multiple sort. 
So I think the configuration should be based on this.
What do you think about that @erezrokah ?

**Comment by erezrokah** [comment]
> In the future, we can enable users to do multiple sorts.
> So I think the configuration should be based on this.
> What do you think about that @erezrokah?

Hi @KancerEzeroglu and sorry again for the late reply.

How about enforcing using our schema validation that only a single field has a `direction`?

**Comment by erezrokah** [comment]
Closing this as stale. Let me know if you'd like me to re-open it

**Comment by jlev** [comment]
It would be really nice to have default sort ordering for date fields. With a lot of posts, having the default be date ascending is not a great user experience...

Is the `direction` schema validation a blocker to getting this merged? If so, I can take a look at it if you point me in the right direction.

**Comment by erezrokah** [comment]
> Is the `direction` schema validation a blocker to getting this merged? If so, I can take a look at it if you point me in the right direction.

Hi @jlev the blockers for the PR are:
1. It breaks existing configurations.
2. It allows you to configure something that doesn't work (can be solved by schema validation)

Please note that the CMS remembers the user's preference for the sort if that helps and having a default sort field can impact performance quite a lot as it requires the CMS to fetch all posts on initial load.

**Pull request closed without merging**
