### PR TITLE
fix(widget-list): default values when adding new items

### LINKED ISSUE #2363: Hidden fields don't work when added through a list widget with variable types
**Describe the bug**

When using the new list widget with variable types, hidden fields don't work. When you add a new item the (nested) hidden fields don't get set to the default value.

**To Reproduce**

```yaml
- label: Items
  name: items
  widget: list
  type: list
  types:
    - label: Item
      name: item
      widget: object
      type: some_type
      fields:
        - label: Name
          name: name
          widget: string
        - label: Subtype
          name: subtype
          widget: hidden
          default: sponsor_item
          required: true
  # more items
```

**Expected behavior**

It should set the default values.

**Applicable Versions:**

 - Netlify CMS app version: 2.9.1

### LINKED ISSUE #2378: Default select widget value not populating via lists when adding new items
**Describe the bug**
Default select widget value not populating via lists when adding new items

**To Reproduce via List Widget**
1. Click "Add list +"
2. Notice the select field does not have the configured default value selected

**To Reproduce via List Widget with Variable Types**
1. "Add variable list item" and then "Object"
2. Notice the select field does not have the configured default value selected

**Expected behavior**
If a select field has a default value defined, it should be populated when a new list item is added that contains a select field with a defined default value.

**Screenshots**
netlify-cms-issue-select-widget-default

**Applicable Versions:**
- Netlify CMS version: 2.9.0 via unpkg
- Git provider: GitHub
- OS: Mac OS 10.14.5 Mojave
- Browser version: Chrome 74.0.3729.169
- Node.JS version: v12.1.0

**CMS configuration**
```
fields:
  - label: "Select"
    name: "select"
    widget: "select"
    default: "default"
    options:
      - label: "Default"
        value: "default"
      - label: "Not Default"
        value: "not default"
  - label: "List"
    name: "list"
    widget: "list"
    fields:
      - label: "Select"
        name: "select"
        widget: "select"
        default: "default"
        options:
          - label: "Default"
            value: "default"
          - label: "Not Default"
            value: "not default"
  - label: "Variable List"
    name: "variableList"
    widget: "list"
    types:
      - label: "Object"
        name: "object"
        widget: "object"
        fields:
          - label: "Select"
            name: "select"
            widget: "select"
            default: "default"
            options:
              - label: "Default"
                value: "default"
              - label: "Not Default"
                value: "not default"
```

### PR DESCRIPTION
**Pull request by barthc**
**Summary**
Closes #2378, closes #2363

### CODE REVIEW

**Comment by erquhart** [comment]
Thanks for this @barthc - would you be up for adding some tests?

**Comment by barthc** [comment]
@erquhart  was about sending in the tests now, sorry for the delay. oh boy.

**Comment by erquhart** [comment]
hahaha no problem, I'll still take 'em!

**Comment by erquhart** [comment]
Publishing this now so if there's bugs we'll be hearing about it soon 😄

**Comment by barthc** [comment]
cool, thanks. 😄

**Pull request merged**
