### PR TITLE
Don't render hidden widgets in markdown visual editor

### LINKED ISSUE #1405: Hidden field in editor component is rendered
**- Do you want to request a *feature* or report a *bug*?**

*bug*

**- What is the current behavior?**

An editor component that declares a hidden field will have it rendered:

screen shot 2018-06-05 at 11 10 57

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Declare an editor component that has a field with `widget: 'hidden'`:

```js
CMS.registerEditorComponent({
  // Internal id of the component
  id: "youtube",
  // Visible label
  label: "Youtube",
  // Fields the user need to fill out when adding an instance of the component
  fields: [{
    name: 'id',
    label: 'Youtube Video ID',
    widget: 'string'
  }, {
    name: 'myHiddenField',
    label: 'My hidden field',
    widget: 'hidden'
  }],
  // Pattern to identify a block as being an instance of this component
  pattern: /^youtube (\S+)$/,
  // Function to extract data elements from the regexp match
  fromBlock: function(match) {
    return {
      id: match[1]
    };
  },
  // Function to create a text block from an instance of this component
  toBlock: function(obj) {
    return 'youtube ' + obj.id;
  },
  // Preview output for this component. Can either be a string or a React component
  // (component gives better render performance)
  toPreview: function(obj) {
    return (
      '<img src="http://img.youtube.com/vi/' + obj.id + '/maxresdefault.jpg" alt="Youtube Video"/>'
    );
  }
});
```

2. Add an instance of the component to a markdown editor.

Observe that the label for the hidden field is rendered with a `No control for widget: 'hidden'` message below it. The same thing happens if the hidden field has no `label` except that a small gray box is rendered instead of the label.

**- What is the expected behavior?**

That the field isn't rendered, similar to how `hidden` widgets work for collections.

**- Please mention your versions where applicable.**

Netlify CMS version: 1.8.4
Browser version: Chrome 67.0.3396.62/OSX

Node.JS version: 9.5.0
Operating System: OSX

**- Please link or paste your `config.yml` below if applicable.**

### PR DESCRIPTION
**Pull request by robertkarlsson**
Fixes #1405

**- Summary**

Fields using hidden was rendered in the markdown editor with "no control" error if no label attached, else a grey box. Return null when rendering the control for hidden widgets.

**- Test plan**
After change UI no longer displays hidden components in the markdown visual editor, nor the markdown editor.
image

image

This was tested using the registered widget in the bug report, attached below.

```javascript
CMS.registerEditorComponent({
  // Internal id of the component
  id: "youtube",
  // Visible label
  label: "Youtube",
  // Fields the user need to fill out when adding an instance of the component
  fields: [{
    name: 'id',
    label: 'Youtube Video ID',
    widget: 'string'
  }, {
    name: 'myHiddenField',
    label: 'My hidden field',
    widget: 'hidden'
  }],
  // Pattern to identify a block as being an instance of this component
  pattern: /^youtube (\S+)$/,
  // Function to extract data elements from the regexp match
  fromBlock: function(match) {
    return {
      id: match[1]
    };
  },
  // Function to create a text block from an instance of this component
  toBlock: function(obj) {
    return 'youtube ' + obj.id;
  },
  // Preview output for this component. Can either be a string or a React component
  // (component gives better render performance)
  toPreview: function(obj) {
    return (
      '<img src="http://img.youtube.com/vi/' + obj.id + '/maxresdefault.jpg" alt="Youtube Video"/>'
    );
  }
});
```

**- Description for the changelog**
Return null when rendering hidden widgets in the markdown editor.

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 0a41609a7fb91b95b913a07ba4eeec8a30811b48

https://deploy-preview-1414--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 0a41609a7fb91b95b913a07ba4eeec8a30811b48

https://deploy-preview-1414--netlify-cms-www.netlify.com

**Comment by fellasuess** [comment]
Hey! To throw in my salt; another approach could be to construct a boolean holding if this widget is hidden or not.

`const hidden = field.get('widget') === 'hidden' ? 'display: hidden;' : 'display: block;'`

then on the div upon return;
`<div key={key} style={hidden}>
  <Control {...controlProps}/>
 </div>`

**Comment by robertkarlsson** [comment]
@fellasuess It makes sense and i thought about this as well, then i found the following code for other hidden widgets:

```javascript
   {fields.map((field, i) => field.get('widget') === 'hidden' ? null : (render the component)
```

https://github.com/netlify/netlify-cms/blob/78e4b829d0ced72f8f38721d38c0d67ccb092aaf/src/components/Editor/EditorControlPane/EditorControlPane.js#L47

Maybe the preferred way is to not execute the rest (by the early return fo null) if the component has no value of being rendered. Anyone else has an opinion on this?

**Comment by erquhart** [comment]
Rendering null is 👍

**Pull request merged**
