### PR TITLE
Feat(widget-datetime): add now to datepicker

### PR DESCRIPTION
**Pull request by tclaes**
**Summary**
Fixes https://github.com/netlify/netlify-cms/issues/3399

Added a now button under the datepicker

**Test plan**

image

### CODE REVIEW

**Comment by tomrutgers** [comment]
Question: Shouldn't we position the now button inside of the input field, like the `choose an image` button for the image widget for consistency?

**Comment by erezrokah** [comment]
I'll have to test how this looks when the field bellow errors

**Comment by erquhart** [comment]
Yep, widget can’t overflow it’s borders.

**Comment by tclaes** [comment]
Would this be better?

image

**Comment by erezrokah** [comment]
@tclaes can you let us know when you think this is ready so we can review it again?

**Comment by tclaes** [comment]
I changed it yesterday so it looks like the last srcreenshot.

**Comment by tomrutgers** [comment]
screenshot

There's a slight bug when testing on Safari.

**Comment by erezrokah** [comment]
Doesn't look right on wider screens or with preview disabled (even with latest commit).

now_button

**Pull request merged**
