### PR TITLE
Doc: Set dev server to 127.0.0.1

### PR DESCRIPTION
**Pull request by gcallaghan**
**- Summary**

When walking through the setup documentationn I was unable to access the dev
server on localhost:8080 on Mac OSX. I attempted to implement the
workarounds suggested at
https://github.com/webpack/webpack-dev-server/issues/183 to no avail.
This change allowed me to follow the output of the webpack dev server
directly and see all assets from the browser.

**- Test plan**

grant at McBeast in ~/work/netlify-cms on origin/master
$ npm start

> netlify-cms@0.7.0 start /Users/grant/work/netlify-cms
> webpack-dev-server -d --config webpack.dev.js

Project is running at http://127.0.0.1:8080/
webpack output is served from http://127.0.0.1:8080/
Content not from webpack is served from example/
404s will fallback to /index.html
You are using @apply rule and custom property sets.
This feature won't be included in next the major release of postcss-cssnext.
This most likely won't get any more support from browser vendors as the spec is yet considered deprecated and alternative solutions are being discussed.
Read more about the reason here https://github.com/pascalduez/postcss-apply.
Hash: 0971a643d3190ae4b6d6
Version: webpack 3.6.0
Time: 14312ms
                                 Asset     Size  Chunks                    Chunk Names
  40b2ba67cfdebc631c5942867695a2e2.eot  83.4 kB          [emitted]
570eb83859dc23dd0eec423a49e147fe.woff2  44.3 kB          [emitted]
 012cf6a10129e2275d79d6adac7f3b02.woff  57.6 kB          [emitted]
  a37b0c01c0baf1888ca812cc0508f6e2.ttf   128 kB          [emitted]
e5147f7843186e46490bd896d6a85abf.woff2  41.3 kB          [emitted]
 3360b1d4036d32df1e555e993b30946c.woff  50.4 kB          [emitted]
  c8c19ba3328799e7bb03f3b47c40dba2.ttf  83.3 kB          [emitted]
  db4e36de8364fc2444c5ed0443c04da4.svg   121 kB          [emitted]
                                cms.js  15.8 MB       0  [emitted]  [big]  cms
   [0] ./node_modules/react/index.js 190 bytes {0} [built]
 [378] (webpack)-dev-server/client/overlay.js 3.73 kB {0} [built]
 [380] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]
 [631] multi (webpack)-dev-server/client?http://127.0.0.1:8080 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://127.0.0.1:8080/ ./index 76 bytes {0} [built]
 [632] (webpack)-dev-server/client?http://127.0.0.1:8080 7.23 kB {0} [built]
 [675] (webpack)/hot/dev-server.js 1.61 kB {0} [built]
 [676] (webpack)/hot/log-apply-result.js 1.31 kB {0} [built]
 [677] ./node_modules/react-hot-loader/patch.js 41 bytes {0} [built]
 [678] ./node_modules/react-hot-loader/lib/patch.js 209 bytes {0} [built]
 [750] (webpack)-dev-server/client?http://127.0.0.1:8080/ 7.23 kB {0} [built]
 [751] ./src/index.js 2.27 kB {0} [built]
 [766] ./node_modules/react-hot-loader/index.js 41 bytes {0} [built]
 [778] ./node_modules/normalize.css/normalize.css 960 bytes {0} [built]
[1592] ./src/index.css 1.16 kB {0} [built]
[1600] ./src/utils.css 1.16 kB {0} [built]
    + 1586 hidden modules
webpack: Compiled successfully.

**- Description for the changelog**

Set dev server to 127.0.0.1

**- Summary**

**- Test plan**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by erquhart** [comment]
Thanks @gcallaghan!

@talves I know this will be moot once we merge your PR, but for the moment, can you review from a cross-platform standpoint?

**Comment by talves** [comment]
@gcallaghan can you try something for me?

Leave the setting as localhost and delete [this line](https://github.com/netlify/netlify-cms/blob/master/webpack.dev.js#L21) in the webpack.dev.js and let me know if it still give you the same issue.
```
publicPath: `http://${ HOST }:${ PORT }/`,
```

**Comment by gcallaghan** [comment]
@talves I updated my OS X and checked out latest master and can now resolve localhost:8080 including the assets. Not sure if this was a 10.12 Sierra issue, but it is resolved for me now.

**Comment by talves** [comment]
Glad to hear. The issue with going to 127.0.0.1 would have implications on other platforms. Documented. Going to 0.0.0.0 would be better, but some windows would gack on it. localhost is our lesser of all evils at this point. 👍

**Pull request closed without merging**
