### PR TITLE
WIP - Implement feature to allow_publish be configured

### LINKED ISSUE #1298: Add allow_publish flag for editorial workflow
**- Do you want to request a *feature* or report a *bug*?**

enhancement

**- What is the current behavior?**

Publishing can't be disabled in the editorial workflow. You generally wouldn't want to, but for folks that use multiple cms instances to approximate a roles based setup, it would be beneficial to switch editorial workflow off on certain instances so that users of those instances can only open pull requests, but can't merge them.

This would help (but not fix) #2 and #1268.

**- What is the expected behavior?**

Allow publishing to be disabled.

### PR DESCRIPTION
**Pull request by springdo**
closes #1298 
and closes https://github.com/openpracticelibrary/openpracticelibrary/issues/349
**Summary**

Add a config flag `allow_publish` to the cms `config.toml` file that allows an admin configure if the publish feature should be enabled. Defaults to true, so admin would have to set `allow_publish: false` to remove it. 

Still TODO 
- [ ]  Add same functionality to the Workflow view which can also be published from.
- [ ]  Fix linting / tests

**Test plan**

Set the `allow_publish: false` and you'll see the Publish button disappear. 

**A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit bdda3d4786a76d1693c64a625aa9ebfa98c7f255

https://deploy-preview-1624--netlify-cms-www.netlify.com

**Comment by erquhart** [comment]
This isn't really disallowing publishing in any real way, but I guess we could do a `show_publish` config property for now, with a default value of `true`. Instead of `hasPublishflow` internally, just call it `showPublish`. Would you mind adding some documentation too?

**Comment by erquhart** [comment]
Closing as stale, please comment or open a new PR if you're still interested in working on this. Thanks!

**Comment by springdo** [comment]
Hi @erquhart  -that's fine; I'll open a new PR when I get some  improvements on it. 
I've not had time to work on this feature since opening the intial PR so will come back to it hopefully before christmas.
Thanks for the input on it though!

**Pull request closed without merging**
