### PR TITLE
Feat(widget-relation): string templates support

### PR DESCRIPTION
**Pull request by erezrokah**
Fixes https://github.com/netlify/netlify-cms/issues/1063
Fixes https://github.com/netlify/netlify-cms/issues/2800

Created a package called `netlify-cms-lib-widgets` to share common code between widgets.
Also updated the relation widget docs with an example on how to use string templates and re-arranged so the required fields are listed first.

### CODE REVIEW

**Comment by barthc** [comment]
> Created a package called netlify-cms-lib-widgets to share common code between widgets.

How about we move the `compileStringTemplate` to `netlify-cms-lib-util` since it's also used by the core ?

**Comment by erezrokah** [comment]
> How about we move the `compileStringTemplate` to `netlify-cms-lib-util` since it's also used by the core ?

I thought about that - but `netlify-cms-lib-util` has a lot of backend related code too (well almost only backend related code other than `promise.ts` which is no longer used and `path.ts` that we can replace just using the `path` module) which is not related to the widgets.

Maybe move that code to `netlify-cms-lib-backends`? 

Thought about doing that refactoring in another PR, what do you think?

**Comment by barthc** [comment]
> Maybe move that code to netlify-cms-lib-backends?
Agreed.

I am thinking, the new `netlify-cms-lib-widgets` package doesn't have much content save the `compileStringTemplate`. Maybe we can wait for more widget related lib codes to ramp up before splitting or group them by folder inside the `netlify-cms-lib-util` package, thoughts?

**Comment by erezrokah** [comment]
Ok, let me do the refactoring with the libs. I was planning on removing `promise.js` and replacing `path.js` usages with the built in `path` module, but I'll do that in another PR.

**Comment by erezrokah** [comment]
> Ok, let me do the refactoring with the libs.

Ok so changing `netlify-cms-lib-util` to `netlify-cms-lib-backends` touches A LOT of code which seems a bit risky and unrelated to do as a part of a relation widget PR.

I'll re-visit this in another designated refactoring.

**Comment by guillett** [comment]
I don't know anywhere else I can thank you. So here it is many thanks for that PR!! The work done on Netlify CMS is really great. :pray:  :1st_place_medal:

**Pull request merged**
