### PR TITLE
add admin UI demo link

### PR DESCRIPTION
**Pull request by DavidWells**
The idea here is to surface it for everyone to quickly see how the admin UI works and feels.

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 14ee2cee1086aa30e78358fcfd145d94681da107

https://deploy-preview-1622--netlify-cms-www.netlify.com

**Comment by DavidWells** [comment]
`npm run lint:format` from main package.json is failing =(

I don't know why

**Comment by DavidWells** [comment]
image

Links to demo site https://cms-demo.netlify.com/

**Comment by verythorough** [comment]
One of the downsides to featuring the demo so prominently is that it doesn't really work like Netlify CMS does in reality. It has no backend, and no associated site to display the content. The changes you make are saved in memory, and lost on reload.

The demo site is great for testing development of Netlify CMS itself. As a tool for getting people to try it, however, I think it falls short.

People don't use Netlify CMS on their sites because it has a super awesome UI. They use it because it has a really cool relationship with Git, and enables development patterns that you can't really get with traditional CMSs.

For me, this is the magic of Netlify CMS:
- Seeing a realtime preview of the page right next to the editor.
- Saving a draft in the CMS and seeing it create a PR on the repo. 
- Publishing that draft and seeing that the CMS merges the PR and deletes the branch.
- Realizing that you can still use regular Git functionality to change and merge that content, in parallel with other users using the CMS.

... and the demo does none of this. We do link to the demo from the docs Intro, but I hesitate to drive people to it so strongly from the front page, because I think people going there will find it kind of meh, and possibly miss out on the very best part.

> “Its like a finger pointing away to the moon. Dont concentrate on the finger or you will miss all that heavenly glory.”
> ― Bruce Lee

😆 but I digress!

On the other hand, we've talked about making an actual repo-backed demo site where people make real edits on it. We'd probably want to set a routine to reset it periodically, and of course someone will come along now and then and post something inappropriate, but I do think it could be pretty cool nonetheless.

**Comment by erquhart** [comment]
Going to go ahead and close this as there's been a consensus here and elsewhere that we'd rather get a full fledged demo working.

**Pull request closed without merging**
