### PR TITLE
Fixes #292 Display version number

### LINKED ISSUE #292: Feature request: Display version number in UI
This would be useful for remote support. :)

### PR DESCRIPTION
**Pull request by josephearl**
**- Summary**

Show the version number in the "settings" dropdown - fixes #292. I also combined the settings menu and user avatar together, which haves the benefit of leaving more space for the search bar on mobile. "-dev" is appending to the version when developing.

**- Test plan**

screen shot 2017-04-15 at 01 32 24

screen shot 2017-04-15 at 01 32 21

**- Description for the changelog**

* Inject the version number from `package.json` with Webpack and display it in the settings menu (this could lead to an about page)
* Combine the settings icon and user avatar together

**- A picture of a cute animal (not mandatory but encouraged)**

Cute duckling

### CODE REVIEW

**Comment by calavera** [comment]
What if we put it in the footer?

Having it in the drop down makes me think that's something I can click on a do something with it.

**Comment by biilmann** [comment]
Seems like it's mainly relevant when debugging. Would it be enough to write it in a console log message when the CMS loads?

**Comment by erquhart** [comment]
I agree with @calavera that placing it in the footer is ideal, but we should try to avoid UI related iterations at this point. For that reason I'd go with @biilmann's approach, as this really is just for debugging.

**Comment by josephearl** [comment]
:+1: will change to console log it

**Comment by josephearl** [comment]
Updated to log to the console:

screen shot 2017-04-18 at 23 04 49

**Comment by calavera** [comment]
LGTM

**Pull request merged**
