### PR TITLE
remove/add copy to earlier paragraph

### PR DESCRIPTION
**Pull request by christinavoudouris**
Hello! I was using your docs earlier and I found the copy (which I deleted in this PR) a bit confusing  and redundant, placed right above the Installing with npm section. I know that using a CDN or npm is a choice, but a newer developer may not, and wonder if there's something else they should install.

**Checklist**

Please add a `x` inside each checkbox:

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x] Code is formatted via running `yarn format`.
- [x] Tests are passing via running `yarn test`.
- [x] The status checks are successful (continuous integration). Those can be seen below.

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by erezrokah — CHANGES_REQUESTED** [review]
Thanks @christinavoudouris!

I agree this paragraph is a bit confusing in the current location.

How about we move it next to the  `The first file, `admin/index.html`, is the entry point for the Netlify CMS admin interface.`?
We do instruct users to add 2 files, so we should explain the reason behind it.

We'll probably need to rephrase the entire paragraph after the:
```bash
admin
 ├ index.html
 └ config.yml
```

for the explanation to make sense. 

WDYT?

**Comment by christinavoudouris** [comment]
@erezrokah I think that works! I went ahead and added it before the last line, "In this example..." and put that on its own line. I don't think anything needs to be rephrased, but I added the name of the file for clarity.

**Comment by erezrokah** [comment]
> @erezrokah I think that works! I went ahead and added it before the last line, "In this example..." and put that on its own line. I don't think anything needs to be rephrased, but I added the name of the file for clarity.

This works great 🚀

**Review by erezrokah — APPROVED** [review]
This works great

**Pull request merged**
