### PR TITLE
Fix Tests

### PR DESCRIPTION
**Pull request by tech4him1**
**- Summary**

Tests cannot resolve the new module aliases, because they are only implemented in WebPack. This changes them to be resolved by Babel instead, so that we don't have to duplicate the alias code between Jest and WebPack.

@erquhart Was there a reason you intentionally used WebPack aliases instead, or just not enough time 😀? 

**- Test plan**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit 82999f2190b1ad7f7fa66462318f560359760975

https://deploy-preview-900--netlify-cms-www.netlify.com

**Comment by tech4him1** [comment]
@verythorough Is there a deploy preview link for the demo site as well?

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit e0a115d6595ad6ca61317cebfcd91f71413442ca

https://deploy-preview-900--netlify-cms-www.netlify.com

**Comment by tech4him1** [comment]
@erquhart The only test left that is failing is https://github.com/netlify/netlify-cms/blob/b370929087c042be951a6d350cc4af07a95a6f94/src/components/Editor/__tests__/EntryEditorToolbar.spec.js#L3, the import doesn't exist. Can you fix that and push?

**Comment by Benaiah** [comment]
@tech4him1 that's where I ran into trouble too - the equivalent component, `EditorToolbar`, appears to have a much different API than those old tests expect.

**Comment by erquhart** [comment]
Just dropped the test for now - the API changed extensively, and we need a ground-up test effort anyway.

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit 1fdc11702494447cc42c485972b48634b5a9cd5f

https://deploy-preview-900--cms-demo.netlify.com

**Comment by erquhart** [comment]
@tech4him1 moving module aliasing to Babel is brilliant, hadn't even considered it. Thank you!

**Pull request merged**
