### PR TITLE
Adding preact-cli's build location

### PR DESCRIPTION
**Pull request by prateekbh**
**Summary**

Adding `preact-cli` to the static site generators list

### CODE REVIEW

**Comment by talves** [comment]
@prateekbh it might not be real clear, but the folder location should be where to put the `/admin` directory and assets (`config.yml`, `index.html`) in the repository of your site. If someone put them in `/build`, they would get deleted during the build command, correct?

**Comment by prateekbh** [comment]
oh right, yes

**Comment by prateekbh** [comment]
@talves a question: if we introduce a folder e.g. `static`  by which we can `site.com/admin/index.html` and `site.com/admin/config.yml` are exposed as URLs would that suffice?

**Comment by talves** [comment]
yeah, that is the way some other static site generators are accomplishing it. It is just important to not mislead what the column is being used for.

**Comment by prateekbh** [comment]
We do now support the same: https://github.com/preactjs/preact-cli/pull/866/files

**Pull request merged**
