### PR TITLE
WIP: Synchronize package-lock.json with yarn.lock.

### PR DESCRIPTION
**Pull request by tech4him1**
Using [imsnif/synp](https://github.com/imsnif/synp). Both lockfiles will continue to work.

Prerequisite for https://github.com/netlify/netlify-cms/pull/1264#issuecomment-385813596.

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 3e6e0e94c40b5658c346a8bfe8a1205565b7970a

https://deploy-preview-1336--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 3e6e0e94c40b5658c346a8bfe8a1205565b7970a

https://deploy-preview-1336--netlify-cms-www.netlify.com

**Comment by erquhart** [comment]
Looks like a great package, seems the caveats are livable if we're translating from yarn to npm rather than npm to yarn.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tech4him1** [comment]
We're staying with Yarn for the Lerna monorepo workflow.

@erquhart Should we add `package-lock.json` to the `.gitignore` for now?

**Pull request closed without merging**
