### PR TITLE
update sidebar styling, add new entry links

### LINKED ISSUE #273: Improve padding/margin and link appearance in left sidebar
The left sidebar lacks sufficient padding/margin, and the links are small and close together - fixing this is a very cheap way to increase the look and feel of the CMS.

**Requirements**
* If possible, maintain some consistency with established spacing in parts of the UI that already have sufficient spacing
* Increase the size of the links if it seems necessary after spacing adjustments are in place

### PR DESCRIPTION
**Pull request by erquhart**
Fixes #273 

* Add margin/padding to sidebar, and increase sidebar link size
* Add shortcut for creating entries on hover, add associated styling

Note: most of this project does not pass linting, but the pre-commit check is very fine grained. A number of changes in this PR were necessary to satisfy linting rules that were already failing.

### CODE REVIEW

**Comment by erquhart** [comment]
sidebar-update

**Comment by calavera** [comment]
@erquhart you should uDPate the title 😛

**Comment by calavera** [comment]
LGTM

**Comment by erquhart** [comment]
@calavera @biilmann updated to keep new entry links always visible. The sidebar now completely replicates the top navigation, which will lead to confusion for users. We should drop the top nav links and just leave the expand sidebar button, search input, and user avatar. This also coincides with React Toolbox's own guidance that IconMenu's should not be used for app navigation.

**Comment by calavera** [comment]
@erquhart what do you think about doing that in this same PR? That way we make the change as a one specific unit.

**Comment by erquhart** [comment]
@calavera agreed, will do.

**Comment by erquhart** [comment]
screen shot 2017-03-14 at 8 54 33 pm

**Comment by erquhart** [comment]
@biilmann ^^

**Comment by calavera** [comment]
LGTM

**Comment by erquhart** [comment]
This also fixed #271.

**Pull request merged**
