### PR TITLE
Update Docs: Reference “configuration-options”

### PR DESCRIPTION
**Pull request by abraithwaite**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by erezrokah** [comment]
Hi @abraithwaite, looks like there is a similar clarification at the beginning of that file https://www.netlifycms.org/docs/configuration-options/

**Comment by erezrokah** [comment]
Closing for now, please comment re-open if you think the existing clarification is not enough

**Comment by abraithwaite** [comment]
Hey Erez, thanks for the review!  I don't think the clarification is sufficient, in particular for the Hugo framework which has a root config.yaml/config.toml file.  When searching for a solution and scanning the docs for a match to an issue, it's easy to miss that minor note at the top.  Maybe the wording can be improved, but I don't think the clarification would hurt to add.

See more context here:
https://netlifycms.slack.com/archives/CPRR0PQ9E/p1588427744312500

Also, I'm not alone in this confusion:
https://github.com/search?q=%22editorial_workflow%22+filename%3Aconfig.toml&type=Code

**Comment by erezrokah** [comment]
Thanks for clarifying, re-opened - I'll think a bit on the phrasing so it doesn't look like duplication

**Pull request merged**
