### PR TITLE
Clarify the difference between Netlify.com and Netlify CMS

### PR DESCRIPTION
**Pull request by jgarber**
Let's clear up the difference, because it wasn't immediately obvious to a n00b like me. The [Deploy to Netlify](https://www.netlifycms.org/docs/start-with-a-template/) buttons are great, but don't help that confusion.

Based on the [excellent explanation by @verythorough](https://gitter.im/netlify/NetlifyCMS?at=58d31392fe6a638b1af3ac65).

Thanks for all your great work on two great products!

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 7e9fe2b91c85ff57fdf19151f843ff1f7c312ba1

https://deploy-preview-1760--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 7e9fe2b91c85ff57fdf19151f843ff1f7c312ba1

https://deploy-preview-1760--cms-demo.netlify.com

**Comment by verythorough** [comment]
Wow, @jgarber, that conversation's a blast from the past! (It's also one I remember fondly - I even [gave a talk about it](https://youtu.be/UgHSqXeoOiY) a couple months later.)

Though it made sense in the context of the greater conversation, I think we may want to change some of the language a bit when it's here in isolation. I'm going to play with the wording a bit in the first two paragraphs and get back with some comments.

I really like what you did with the bullet points!

**Comment by jgarber** [comment]
Sounds great! Can't wait to see the final product.

**Comment by verythorough** [comment]
@jgarber Here's a suggestion to replace my paraphrased words in the first two paragraphs:

> [Netlify.com](https://www.netlify.com/) is a platform you can use to automatically build, deploy, serve, and manage your frontend sites and web apps. It also provides a variety of other features like form processing, serverless functions, and split testing. Not all Netlify sites use Netlify CMS, and not all sites using Netlify CMS are on Netlify.
>
> The folks at Netlify created Netlify CMS to fill a gap in the static site generation pipeline. There were some great proprietary headless CMS options, but no real contenders that were open source and extensible—that could turn into a community-built ecosystem like WordPress or Drupal. For that reason, Netlify CMS is _made_ to be community-driven, and has never been locked to the Netlify platform (despite the name).
>
> With this in mind, you can:
>
> _[your bullet points follow from here...]_

Any other folks have input?

**Pull request merged**
