### PR TITLE
Docs: Fix Hugo & Gatsby blog article URLs

### PR DESCRIPTION
**Pull request by mistermantas**
**- Summary**

This fixes 2 links that return a 404.

Specifically, these ones:

> [Hugo](https://www.netlify.com/blog/20.7.09/21/a-step-by-step-guide-victor-hugo-on-netlify/)
> [Gatsby](https://www.netlify.com/blog/20.7.02/24/a-step-by-step-guide-gatsby-on-netlify/)

**- Test plan**

I click the link and it works.

**- Description for the changelog**

`Fixed URLs that returned a 404 in the quick start guide`

### CODE REVIEW

**Comment by erquhart** [comment]
@mistermantas thanks, good catch! Would you mind adding yourself to the all contributors grid? Here's how: https://github.com/netlify/netlify-cms/blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor

**Comment by mistermantas** [comment]
It’s just a typo, I don’t deserve to be there 😄

**Comment by tech4him1** [comment]
@mistermantas I've actually had multiple support questions lately about those links being broken, so I think you do deserve to be in there! :)

**Comment by erquhart** [comment]
I'll add ya :)

**Pull request merged**
