### PR TITLE
(WIP) Add multiselect widget

### PR DESCRIPTION
**Pull request by Benaiah**
**- Summary**

Add multiselect widget.

Remaining work:
- [ ] select-like UI and styling

**- Test plan**

Tested manually

**- Description for the changelog**

Add multiselect widget

### CODE REVIEW

**Comment by erquhart** [comment]
Just pushed up some local commits from a few months back, this still needs to be completed.

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit e496bf3d6dd6d88bbab2f4654424083534930918

https://deploy-preview-922--cms-demo.netlify.com

**Comment by cpjolicoeur** [comment]
Any thoughts on ETA for delivering this? Or is this something someone else needs to pick up and run with?

**Comment by erquhart** [comment]
@cpjolicoeur this does need a sponsor, of you're interested in taking it on let me know

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cpjolicoeur** [comment]
@erquhart Will do.  Not sure I can commit currently, but perhaps in the next few weeks.  We are in the middle of rolling our own widget for this, but after that, I'll circle back and see about making a more generic, publically consumable multiselect.

**Comment by erquhart** [comment]
Awesome, sounds good.

**Comment by erquhart** [comment]
They're only being replaced if someone replaces them. Need to close pull requests that stop moving, but anyone is free to pick one up and open a new PR.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by erquhart** [comment]
Note: multi-select is now supported in the select widget via the `multiple` config flag: https://www.netlifycms.org/docs/widgets/#select

**Pull request closed without merging**
