### PR TITLE
Corrects docs re: 'relation' widget configuration

### LINKED ISSUE #1042: Mistake in docs re: setting up 'relation' widget
**- Do you want to request a *feature* or report a *bug*?**  
BUG

**- What is the current behavior?**  
Docs mislead with regard to setting up a relation widget.

**- If the current behavior is a bug, please provide the steps to reproduce.**  
Go to https://www.netlifycms.org/docs/widgets/#relation and locate this information:

**- What is the expected behavior?**  
Where it says `searchFields: "[name, twitterHandle]"`, it should instead say `searchFields: ["name", "twitterHandle"]`.

### PR DESCRIPTION
**Pull request by sumeetjain**
Fixes #1042

**- Summary**

The docs re: configuring a 'relation' widget had a mistake, which led people (or, at least, me) to configure their widgets with

`"[name, twitterHandle]"` instead of
`["name", "twitterHandle"]`

**- Test plan**

Using the corrected syntax was all that was needed to get my 'relation' widget working.

**- Description for the changelog**

Corrects syntax in docs for configuring 'relation' widget searchFields.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 780cf737e219015689156b2def4918ae4b9af0b1

https://deploy-preview-1043--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 780cf737e219015689156b2def4918ae4b9af0b1

https://deploy-preview-1043--cms-demo.netlify.com

**Comment by tech4him1** [comment]
@sumeetjain Thanks for adding yourself to the contributors list as well!

**Comment by verythorough** [comment]
Oh, nice catch! Thanks!

**Pull request merged**
