### PR TITLE
fixing broken links

### PR DESCRIPTION
**Pull request by davidkazuhiro**
**Summary**

The CHANGELOG had broken links, so I fixed them

**Test plan**

no code is changed in this PR

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 61c9437a326f77dd941bdaddc9175774bb97af26

https://deploy-preview-1942--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit ecb274112dace87141b6180c987c797b5e82eed6

https://deploy-preview-1942--netlify-cms-www.netlify.com

**Comment by davidkazuhiro** [comment]
For some reason the links aren't working... so I won't fix the rest of the file for now.
Hopefully this PR conveys the idea of the problem though

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 61c9437a326f77dd941bdaddc9175774bb97af26

https://deploy-preview-1942--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit ecb274112dace87141b6180c987c797b5e82eed6

https://deploy-preview-1942--cms-demo.netlify.com

**Comment by erquhart** [comment]
The changelog is automatically generated, so we'll want to avoid direct edits. This is an issue with Lerna, definitely worth looking into. Can you open an issue for this instead of a PR?

**Comment by davidkazuhiro** [comment]
ah I see.
ok, created #1956
closing this PR

**Pull request closed without merging**
