### PR TITLE
feat(widget-string): add trim option

### PR DESCRIPTION
**Pull request by wawjr3d**
**Summary**

Add an option for the string widget to trim content. We need this feature because users can accidentally (e.g. pasting from another document, pasting an accidental carriage return) input extra spaces.

**Test plan**

https://user-images.githubusercontent.com/1474786/103036236-48b0db80-4537-11eb-973b-a6acddaadd81.mp4

**A picture of a cute animal (not mandatory but encouraged)**
6f29b17b8fcde2889c18c07f571438bb

### CODE REVIEW

**Comment by wawjr3d** [comment]
it wasn't clear to me where to add unit tests for this and i didn't see cypress tests for other widgets besides the markdown widget. let me know if you want me to add them, and, if so, if there is an existing pattern that I should follow. if there isn't, i'd still be happy to add them.

**Review by erezrokah — CHANGES_REQUESTED** [review]
Thanks @wawjr3d and sorry for the late reply.

For the sake of keeping the API surface for the string widget smaller can I suggest to use either [pattern](https://www.netlifycms.org/docs/widgets/#common-widget-options) to validate the value or the [preSave event](https://www.netlifycms.org/docs/beta-features/#registering-to-cms-events) to do the trimming?

**Comment by wawjr3d** [comment]
@erezrokah no worries on the delay. on using the pattern validation, if we go with that, it would be a different user experience than we're hoping for. our goal is to allow folks to paste in a value and it auto-trim for them. are there any other options using the existing API to accomplish that?

**Comment by erezrokah** [comment]
> @erezrokah no worries on the delay. on using the pattern validation, if we go with that, it would be a different user experience than we're hoping for. our goal is to allow folks to paste in a value and it auto-trim for them. are there any other options using the existing API to accomplish that goal?

While not as straightforward as the config option, this should work:

```js
CMS.registerEventListener({
  name: 'preSave',
  handler: ({ entry }) => {
    return entry.get('data').set('title', entry.getIn(['data', 'title'], '').trim());
  },
});
```

**Comment by wawjr3d** [comment]
cool, thanks @erezrokah!

**Pull request closed without merging**
