### PR TITLE
Allow for relative paths of media files

### LINKED ISSUE #325: 'relative path' field for uploaded images
Hi,
I am starting to use Netlify CMS with Gatsby 1.0.
I need a relative path to fetch pictures with the graphQL layer. So in my frontmatter I would like to have a field like:
`fieldName: ../images/myImage.jpg`
Of course the last part ("myImage.jpg") would be different for each entry depending on the file I upload.

Is there a way to auto generate a string field in the frontmatter that would concatenate a string of my choice (for example '../images/') with the name of a picture I may upload in an image field of the same entry ?

I also tried to set:
`public_folder: "../images"`
This would theoretically change all my image fields in all collections to get that leading string in the file path but when I create a new file with the CMS I get an auto opening '/'... So in my frontmatter:
`image: /../images/myImage.jpg`
instead of
`image: ../images/myImage.jpg`
Of course this breaks my groove as well.

What is the best way to get around this issue?

### PR DESCRIPTION
**Pull request by samlanning**
**Summary**

fixes #325 

This is an initial attempt at fixing the long-standing issue of Netlify not supporting relative paths in the output in markdown, frontmatter, yaml etc...

~I wasn't quite able to get it working the way I had hoped, which I'll go into in a little bit, but this at least should work for the majority of cases talked about on #325.~ (EDIT: I was able to get this working)

In short, I've introduced a new configuration option `media_folder_relative` which when set to `true`, ~is used in place of `public_folder`, and no slash is prepended to the path~ will calculate the relative path to media files from the relevant collection's folder, instead of using `public_folder` or `media_folder`. This work is based on the work @fk did in https://github.com/fk/netlify-cms/commit/2ebbed8e86b17dce4fa8a9dfd8822275d73361d1

## Original Idea *(now implemented)*:

What I was originally thinking after reading the thread in #325 was that it would be great if we could instead use a **boolean configuration flag** to indicate if paths should be relative, and then if that's the case, resolve what that relative path would be using the path of the Entry that we're inserting the media into. This has the added benefit of not requiring all collections to be in the same location relative to the media folder. e.e, something like this:

```
content
├── posts
│    ├── hello_world.md
│    └── foo_bar.md
├── media
│    └── image.png
└── meta
     ├── tags
     │    └── tag_1.md
     └── categories
          └── category_1md
```

Would allow files in `posts`, `tags` and `categories` to all relatively refer to images in `media`. However I was unable to get this working as I wasn't sure how to obtain information of the current entry from within the context of the mediaLibrary actions and reducers, or from within the `FileControl` component (i figured out how to pass a path from `FileControl` to `resolvePath` though).

For example, `media_folder` would be `content/media`. And for `content/posts/hello_world.md` we'd resolve `image.png` to `../media/image.png`. And from `tag_1.md` we'd resolve it to `../../media/image.png`.

### Just use `public_folder`, and don't prepend a slash if it starts with `./` or `../`.

@erquhart had suggested this (https://github.com/netlify/netlify-cms/issues/325#issuecomment-352916364). However this has the downside that it is a breaking change for people that have misconfigurations of `public_folder`, but also it prevents us being able to also use `public_folder` to display preview images in the CMS. I also felt that the name would be inconsistent with how we were treating that configuration variable (i.e. not as a public folder at all).

## Further Potential Improvements:

* ~Implement the original idea~ **(DONE)**
* `resolvePath` seems to be used in a number of different contexts, and it's not clear that they're all the same. For example it's now used for converting a single filename to a path to enter in to the markdown. It's also used to convert that path into a path to use when displaying the image in the CMS. It probably makes sense to split it out into different functions for the different contexts so this is clearer. (EDIT: this is partially done in `resolveMediaFilename` now).
* due to its use of `resolvePath`, the image preview in `FileControl` doesn't work in the case where the image:
  * has not been deployed to the public site yet
  * is not directly published to some static folder (e.g. when using resharper)
  * is referred to by some relative path (i.e. the use case here)
  It would probably make sense to have it use the same mechanism as `loadMediaDisplayURL` in the `mediaLibrary` action.

### CODE REVIEW

**Comment by samlanning** [comment]
While working on my other pull request #2397, I was able to work out how to get information about the current entity being edited from within `mediaLibrary` actions. So I came back to this PR and implemented the original idea. I'm now much happier with the way that this is implemented, which feels significantly more robust.

I also introduced a new function in `path.js` called `resolveMediaFilename` that is specifically used to calculate the path to insert into the frontmatter / markdown / collection entry, and has a more explicit API and docs.

The image previews in `FileControl` are still not working for now though.

**Comment by erquhart** [comment]
Thanks for digging into this! The approach is dead on, resolving the relative path for individual files makes the mosts sense 👍

I know there's not a ton of existing coverage to add to (we're working on it), but we're requesting that new pull requests include adequate test coverage. Makes it much easier to ensure against regressions, cover the new code, and provide documentation-in-action of how new functionality is supposed to work.

**Comment by samlanning** [comment]
Sounds good. I'll add some tests for these changes.

**Comment by samlanning** [comment]
I've added unit tests now, and reworked the action a little bit to make it easier to test too. To do this I also added `redux-mock-store` as a `devDependency` for `netlify-cms-core` to use in testing thunk action creators (which `insertMedia` is now).

**Comment by erquhart** [comment]
Awesome, thanks for that! I think we can get this into beta and ask some Gatsby users to test it out.

@Benaiah you good with this being merged? I don't think it impacts what you're working on, but wanted to be sure.

**Comment by samlanning** [comment]
@Benaiah @erquhart any update on this? :)

**Comment by erquhart** [comment]
Hey Sam - sorry, haven't forgotten about this, will get it merged and released soon.

**Comment by erquhart** [comment]
Fixed merge conflict, merging and releasing to beta.

**Comment by erquhart** [comment]
Released in 2.9.8-beta.2 - so sorry for the wait!

**Comment by samlanning** [comment]
Awesome! =)

**Pull request merged**
