### PR TITLE
Add neutyp to list of contributors

### PR DESCRIPTION
**Pull request by imorente**
**- Summary**
Add @neutyp to the list of contributors!

**- Test plan**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit 0359988e66e635bf06ac57068c58e2c987bfcd30

https://deploy-preview-897--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
@tech4him1 Since .all-contributorsrc is a generated file, I wonder if there's another way of customizing the badge template. Feels wonky to have to manually update a generated file.

**Comment by tech4him1** [comment]
@verythorough As far as I can tell, that is the recommended method -- only the contributors part of it should be left alone: https://github.com/jfmengels/all-contributors-cli/blob/master/README.md#configuration.

**Comment by verythorough** [comment]
@tech4him1 When you made your update above to include the template, did you re-run the cli with a flag to set the badge? Or did you open the file and edit it?

**Comment by tech4him1** [comment]
@verythorough I manually added the `badgeTemplate` line, then re-ran the CLI to actually set the badge.

**Pull request merged**
