### PR TITLE
chore(website): Announce Gatsby plugin 4.0.0

### PR DESCRIPTION
**Pull request by talves**
**Summary**

Blog post to Announce 4.0.0 Gatsby Plugin

**Test plan**

Review on build.

**A picture of a cute animal (not mandatory but encouraged)**
📝

### CODE REVIEW

**Comment by erquhart** [comment]
Looks good, ready to merge when you are, Tony - good to go?

**Comment by talves** [comment]
Just added the Media Libraries section, so can we get a build of the site to review?

**Comment by erquhart** [comment]
Here 'tis: https://deploy-preview-2313--netlify-cms-www.netlify.com/blog/2019/05/netlify-cms-gatsby-plugin-4-0-0

**Comment by talves** [comment]
LGTM

**Comment by erquhart** [comment]
Sorry for the delay here @talves - finally had a sec to run through this, took the opportunity to add in the bigger picture of the Gatsby plugin. Stretched the scope a bit, but that story isn't told anywhere, so this gives us a good place to tell it. Hopefully folks searching to understand the whole Gatsby/Netlify CMS thing will make it here.

**Pull request merged**
