### PR TITLE
optimize images

### PR DESCRIPTION
**Pull request by marcobiedermann**
Optimize images using [ImageOptim](https://imageoptim.com) without losing any quality will save ~1.7 MB (24.1%).

image

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit 0410130fa6aad87cf21e1022aae911f73f38bb2f

https://deploy-preview-931--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit 0410130fa6aad87cf21e1022aae911f73f38bb2f

https://deploy-preview-931--cms-demo.netlify.com

**Comment by erquhart** [comment]
Nice!!

**Comment by marcobiedermann** [comment]
@erquhart 
You are very welcome.
Yes, using the image optimization in your build job would be ideal but in this case the files are not processed via webpack.
I optimised some static files and the source files in general.
Anyway it will reduce the overall project size which is always good.

**Comment by erquhart** [comment]
Yeah they're just being copied right now, so we'd need to import them via webpack. I wonder if the copy webpack plugin makes any provision for optimization of copied files, need to check on that.

**Pull request merged**
