### PR TITLE
Add middleman starter to 'start with a template' page in docs

### PR DESCRIPTION
**Pull request by tomrutgers**
**Summary**
Related to #16

Adds a middleman starter template to the Netlify CMS docs

**A picture of a cute animal (not mandatory but encouraged)**
dikdik

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 5c95b356485a486368c81de88f59a5df4a59a88d

https://deploy-preview-1699--netlify-cms-www.netlify.com

**Comment by erquhart** [comment]
@tomrutgers so awesome to have a solid Middleman starter in the docs, thank you!

Tech note: you'll want to keep your fork up to date with the main repo by pulling from time to time (that's why the test build failed). I rebased and pushed an update for this PR branch.

**Comment by tomrutgers** [comment]
@erquhart Cool! You have to give me some git lessons sometime soon!

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 1b10deb12d803a5d55bda94e66e1bd2f21df315b

https://deploy-preview-1699--cms-demo.netlify.com

**Pull request merged**
