### PR TITLE
use react select

### PR DESCRIPTION
**Pull request by barthc**
**Summary**
This PR will allow the cms to use the [react select](https://github.com/JedWatson/react-select) for it's select widget. When merged, it will help finish up the multiselect widget #922 
react-select

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 84effb1249f7b2b5c98bd61ca1c9b93f8f7e5af6

https://deploy-preview-1835--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 84effb1249f7b2b5c98bd61ca1c9b93f8f7e5af6

https://deploy-preview-1835--cms-demo.netlify.com

**Comment by erquhart** [comment]
Thanks for this @barthc! Needs a designers touch to mesh it with the other native widgets visually (colors, spacing, caret icon, empty option selection). @tomrutgers any specific thoughts from a design standpoint?

**Comment by tomrutgers** [comment]
@erquhart Are we talking about styling / theming for the react-select features like on the [example page](https://react-select.com/home)?

**Comment by erquhart** [comment]
This PR just uses basic select functionality, I'm just thinking it should look like the other widgets (as the current select widget does). Maybe that's all the design direction we need here, "make it look like the current one".

**Comment by barthc** [comment]
@erquhart  @tomrutgers

**Default Select**
normal-select

**React Select**
react-select

**Comment by tomrutgers** [comment]
@erquhart For now I'd say make it look like the current one is suffice. 
@barthc I prefer the caret icon having the same color as the 'select' label for accessibility, otherwise LGTM!

**Comment by barthc** [comment]
@erquhart  @tomrutgers  I have made the caret color change.

**Comment by barthc** [comment]
@gil--  Thanks for the feedback. The idea is to make the react select match the previous select in size. Without tryng to adjust the height, the react  select would look like so (`height` `74px` including `padding`) :
react-select-default

> and the other components remained the default 36px height:

Other input components excluding `text` and `markdown` have a default height of `58px` including `padding`. 

Regarding the select been cut off because of the height property ,that  seems to be a firefox issue, works well on chrome. Anyway I have remove the` height` property and have adjusted the `padding` instead. So works well on firefox now.

Fixed the option value aligment as well:
react-select-active

**Comment by erquhart** [comment]
One more thing: the entire area of the select widget needs to be clickable.

**Before**
screen shot 2018-11-19 at 4 32 42 pm

**After**
screen shot 2018-11-19 at 4 32 30 pm

**Comment by barthc** [comment]
@erquhart  fixed the clickable area.

**Comment by erquhart** [comment]
Looks good 👍👍

**Pull request merged**
