### PR TITLE
Add `label_singular` to collection config

### LINKED ISSUE #684: Add `label_plural` field to collection config
**- Do you want to request a *feature* or report a *bug*?**
feature

**- What is the current behavior?**
The `label` field for a given collection is displayed in all places in the UI where the collection is referenced. At the moment, this is not pluralized in any way, so a collection with label "Post" will display as simply, "Post" in the sidebar. If you change the label to "Posts," it looks good in the sidebar, but "New Posts" doesn't make sense.

We used to have programmatic pluralization, but it sometimes produced undesirable results, and was [removed](https://github.com/netlify/netlify-cms/pull/503).

**- What is the desired behavior?**
It would be nice to have an optional `label_plural` field (or something similar), allowing implementers to specify a label version to use in cases where the UI calls for a plural. With this in place, we can bring back programmatic pluralization and use it as a default when the manual plural isn't specified.

### PR DESCRIPTION
**Pull request by peduarte**
Hello 👋

This PR adds `label_singular` to collection config.

Fixes #684

**- Summary**

This field will be used in the UI in places where a singular label makes more sense. For example:

If you have a "Posts" collection, the "add collection" button in the UI will show as "New Post" rather than "New Posts".

I went with `label_singular` because I foresee majority of Collection names being in plural. Therefore, I think by default the label should respect the collection name.

However I'm happy to change it to `label_plural` if needed.

**- Test plan**

There doesn't seem to be tests for certain fields in the config, such as `label`, perhaps because these are optional fields. For this reason I have not written any tests.

**- Description for the changelog**

Add `label_singular` to collection config

screenshot 2018-02-06 22 22 01

image

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit d7ca84a5cf038cc326d4b647e0fbcd3ebe0d229d

https://deploy-preview-1086--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit d7ca84a5cf038cc326d4b647e0fbcd3ebe0d229d

https://deploy-preview-1086--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 164da37580f42618c8f709a4608a6e2ed2c5c80e

https://deploy-preview-1086--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 164da37580f42618c8f709a4608a6e2ed2c5c80e

https://deploy-preview-1086--cms-demo.netlify.com

**Comment by peduarte** [comment]
@erquhart that's cool thank you!

I see this PR is now conflicting with master, I can resolve these. 

Would you like me to rebase master into this branch too (as per contributing docs)?

**Comment by erquhart** [comment]
Just fixed actually - merged a newer PR by mistake earlier and broke a bunch.

**Comment by peduarte** [comment]
@erquhart well thank you! 🙏

**Comment by verythorough** [comment]
@peduarte Thank you for including the matching docs update!! 😉 

`label_singular` makes sense to me, and matches other CMS configs, like WordPress. We may want to run by @biilmann, since it was his desire to bring automatic pluralization that caused me to propose the `label_plural` version in the issue. :)

**Comment by tech4him1** [comment]
@verythorough So I assume it was originally thought of as an override for automatic pluralization, whereas this would be strictly manual?

**Comment by peduarte** [comment]
@tech4him1 that's correct. The goal of this implementation is to be strictly manual, as it's been discovered that trying to intelligently pluralize/singularize words doesn't work.

**Comment by peduarte** [comment]
Hey guys, is there an "ETA" for this? Thanks! 👍

**Comment by verythorough** [comment]
I see no blockers, and it looks like @erquhart approved, so I think we're good to go. Thanks for the nudge, and for the contribution! I'm looking forward to making use of this.

**Pull request merged**
