### PR TITLE
Docs: Added Google Cloud Function to External OAuth Clients List

### PR DESCRIPTION
**Pull request by abcalderon3**
**Summary**
Adding a link to a new Google Cloud Function with Python  External OAuth Client to the Documentation

I created a new External OAuth Client running on Google Cloud Functions with Python for use in a lightweight open-source, community-driven project and would like to add it to the list in the Netlify CMS Documentation. Another user found it useful, so figured others may as well!

**Test plan**
Updated Website markdown only. Confirmed via running local website only.

### CODE REVIEW

**Comment by erezrokah** [comment]
Looks like the build finished successfully on Netlify, but some status checks are still pending. Looking into it.

**Comment by abcalderon3** [comment]
That's odd, tried to make just a surgical change and follow the contributing guidelines, but this is my first contribution, so let me know if there's something I need to change.

**Comment by erezrokah** [comment]
FYI, force push is due to a rebase with the `master` branch

**Comment by erezrokah** [comment]
> That's odd, tried to make just a surgical change and follow the contributing guidelines, but this is my first contribution, so let me know if there's something I need to change.

No worries, this is our fault. Will get this merged soon

**Pull request merged**
