### PR TITLE
auth without netlify oauth provider

### PR DESCRIPTION
**Pull request by vencax**
Hi, i needed to use netlify-cms just with github OAuth provider. So I made this changes along with OAuth client https://github.com/vencax/netlify-cms-github-oauth-provider.
I hope you find it useful. CHeers

### CODE REVIEW

**Comment by erquhart** [comment]
Hey @vencax this seems harmless to merge, and I'm okay with not documenting it at the moment to avoid folks misusing it. Would you be up for publishing a quick walkthrough blog post for folks that want to use this?

**Comment by vencax** [comment]
Ok, where should I publish it?

**Comment by erquhart** [comment]
@vencax for now, you can just publish to your blog if you have one. We're still working toward a documented approach for this, but we could maybe link to your blog post in the docs as an interim solution.

**Comment by vencax** [comment]
Ok, it's live here: http://www.vxk.cz/tips/2017/05/18/netlify-cms/

**Comment by andreaskeller** [comment]
@erquhart any chance this can be merged soon? thanks @vencax for the awesome work!

**Comment by erquhart** [comment]
@andreaskeller yeah this is good to merge, thanks for the reminder.

**Comment by erquhart** [comment]
@vencax your email address for you commit isn't associated with your GitHub account - you should add it so you're credited in the repo's contributors tab :)

screen shot 2017-06-05 at 11 41 24 am

**Comment by andreaskeller** [comment]
@erquhart thank you very much!

**Comment by mryellow** [comment]
How does one configure this?

Using the static HTML admin, it loads `api.netlify.com` popup by default.

**Comment by mryellow** [comment]
It would appear the current version distributed on CDN's doesn't have this commit https://github.com/netlify/netlify-cms/commit/26d402149ad3d6ac6f990b8450880ab21a3f18cc

**Comment by erquhart** [comment]
@mryellow correct, it isn't released yet. Coming very soon.

**Comment by erquhart** [comment]
Update: this was released in 0.4.3.

**Pull request merged**
