### PR TITLE
Improve readability of docs for extension field

### PR DESCRIPTION
**Pull request by dzello**
**- Summary**

Fixes a grammar issue with a sentence in the docs for the `extension` config field.

**- Test plan**

n/a

**- Description for the changelog**

Improved docs for extension field.

**- A picture of a cute animal (not mandatory but encouraged)**

🐯

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 29266c6b35a8157dd79b92fa353a40992819d079

https://deploy-preview-1192--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 29266c6b35a8157dd79b92fa353a40992819d079

https://deploy-preview-1192--cms-demo.netlify.com

**Comment by verythorough** [comment]
Makes sense to me! Could you [add yourself as a contributor](https://github.com/netlify/netlify-cms/blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor)?

(Or we can do it for you if you'd rather skip cloning locally, since it looks like you just used the GitHub editor for this.)

**Comment by dzello** [comment]
Looks like @tech4him1 has added me as a contrib, thank you!

**Comment by verythorough** [comment]
Thank you!

**Pull request merged**
