### PR TITLE
add window.createReactClass

### PR DESCRIPTION
**Pull request by ekoeryanto**
**- Summary**

**- Test plan**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit e516b140143eecb6c8b8bda3a39d1b14d296468d

https://deploy-preview-1371--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit e516b140143eecb6c8b8bda3a39d1b14d296468d

https://deploy-preview-1371--netlify-cms-www.netlify.com

**Comment by tech4him1** [comment]
@ekoeryanto Is there a reason we can't just use the existing `createClass`?

**Comment by ekoeryanto** [comment]
`create-react-class` exports global `createReactClass`
```js
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory(require("react"));
	else if(typeof define === 'function' && define.amd)
		define(["react"], factory);
	else if(typeof exports === 'object')
		exports["createReactClass"] = factory(require("react"));
```

**Comment by tech4him1** [comment]
@ekoeryanto Yes, and we simply "rename" the export to `createClass`. Is there a reason you can't use the name we are already exporting it as instead.

**Comment by ekoeryanto** [comment]
I just think about putting `https://unpkg.com/create-react-class` above the netlify-cms and the `createClass` should be overridden by it

**Comment by erquhart** [comment]
Some bits around all of this will likely change for 2.0 - for now, in the case you described, a user can import `create-react-class` and use it without issue, so not a big problem.

**Pull request closed without merging**
