### PR TITLE
Add Plugin Contributor

### PR DESCRIPTION
**Pull request by hennessyevan**
**- Summary**
Add Plugin Contributor https://github.com/hennessyevan/netlify-cms-widget-youtube

**- Test plan**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 1fae23535104f2ad4f8d7a7fa3645b7b46d583a7

https://deploy-preview-1386--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 1fae23535104f2ad4f8d7a7fa3645b7b46d583a7

https://deploy-preview-1386--netlify-cms-www.netlify.com

**Comment by erquhart** [comment]
Looks like merge conflicts, can you try again from the latest master?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hennessyevan** [comment]
Tried again here: https://github.com/netlify/netlify-cms/pull/1387

**Pull request closed without merging**
