### PR TITLE
Add example

### PR DESCRIPTION
**Pull request by growdigital**
**- Summary**

Adding my own site as an example of integrating Netlify CMS into Hugo site.

**- Test plan**

Not really required for adding an example

**- Description for the changelog**

Added Hugo example

**- A picture of a cute animal (not mandatory but encouraged)**

https://www.flickr.com/photos/forestgardenwales/41036171822/in/photolist-HxDMKN-25we7cQ-249WPo5-22va3Hf-F1HHjh-J9dvFV-22J4U1p-HD67XW-25M1fnT-24FSYj5-HCZqN7

🐕 😄

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 499218cac907a09c9b65072ef93485ce1f65581b

https://deploy-preview-1263--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 499218cac907a09c9b65072ef93485ce1f65581b

https://deploy-preview-1263--cms-demo.netlify.com

**Comment by growdigital** [comment]
What did you think of Ronnie Barker? Did he pass?

**Comment by growdigital** [comment]
Oops. He wasn't public! I have made him public now 🙂

**Comment by erquhart** [comment]
Hey Jake, thanks for the PR! We're more looking for varied implementations, and Hugo blogs are pretty well exemplified. Thanks!

**Comment by erquhart** [comment]
Actually, probably better to just have a bunch of examples, we'll take it. Thanks again!

**Comment by growdigital** [comment]
Thank you 🙂. I've just written a blog post to give a bit of detail, will add link to the example

**Comment by erquhart** [comment]
That would be awesome, sounds good.

**Comment by growdigital** [comment]
I've added it, made a pull request, under review 🙂 Thanks for all your work on Netlify CMS!

**Pull request merged**
