### PR TITLE
fix #1810 delete list item

### LINKED ISSUE #1810: Unable to delete List Item (Image widget)
**Describe the bug**
When in Netlify CMS, I am unable to delete an image widget from a list.

**To Reproduce**

1. Go to `webpage.com/admin` and click on the Properties page
2. Add an image
3. Click X
4. Image will not be removed

**Expected behavior**

Clicking X should remove the image from the CMS

**Screenshots**

screen shot 2018-10-14 at 3 46 15 pm

**Applicable Versions:**

 - Netlify CMS version: 2.1.1
 - Git provider: GitHub
 - OS: macOS High Sierra 10.13.6
 - Browser version: Google Chrome 69.0.3497.100
 - Node.JS version: Node 10.9.0

**CMS configuration**

```
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "property"
    label: "Properties"
    folder: "src/pages/property"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "property"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Images", name: "images", widget: "list", field: { label: "Image", name: "image", widget: "image"}}
```

### PR DESCRIPTION
**Pull request by barthc**
**Summary**
This PR fixes #1810

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 608d7a59eb04550c62da3146277196a3bcb26412

https://deploy-preview-1815--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 608d7a59eb04550c62da3146277196a3bcb26412

https://deploy-preview-1815--cms-demo.netlify.com

**Comment by Gostwow** [comment]
Can we expect a merge soon?

**Comment by tomrutgers** [comment]
@Gostwow The changes have to be reviewed by multiple maintainers. They haven't had much time yet to respond since this PR is only a day old.

**Comment by calvinrbnspiess** [comment]
The workaround changing `field` to `fields` suggested in #1810 won't work when it's a single list item. 
It would result in not even loading the Content Manager:
```
netlify-cms 2.1.3
react-dom.production.min.js:188 TypeError: r.get is not a function
    at t.reduce (serializeEntryValues.js:31)
    at immutable.js:4418
    at immutable.js:1377
    at He.iterate.Ve.iterate (immutable.js:1726)
    at Fe.__iterate (immutable.js:1375)
    at Fe.reduce (immutable.js:4413)
    at s (serializeEntryValues.js:30)
    at i.List.isList.t.set.u.map.e (serializeEntryValues.js:38)
    at immutable.js:3016
    at dt.__iterate (immutable.js:2206)
```
Touching my `.json`content files with changing the array to an object would require a lot of additional work changing some fronted code.

**When will this ship?**

**Comment by barthc** [comment]
@calvinrbnspiess  this PR already fixed the issue, no need to change `field` to `fields`.

**Comment by calvinrbnspiess** [comment]
Haha sorry 😋 Maybe I didn't expressed it clear enough. Although the PR is already merged, it won't take effect until a new release is published. Nonetheless, the suggested workaround is a bit impractical for me

Perhaps this question is more for @erquhart: When can we expect the next minor release?

**Comment by erquhart** [comment]
i got 99 problems and they're all lerna

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
