### PR TITLE
Header and Navigation

### LINKED ISSUE #49: Add a link to "create a new post" in UI
User needs:
- to be able to quickly and easily know how to start a new piece of work

In the first column of the workflow, add a link beneath the first heading to "add a new post".  

See wireframe: https://phae.github.io/netlify-sketch/index.html

Acceptance criteria:
- [ ] User can click a link to create a new post (new branch)

### PR DESCRIPTION
**Pull request by okonet**
It turned out to be a bigger PR after all.

In order to move faster, I've integrated [react-toolbox](http://react-toolbox.com/) as a UI library. It looks like a very well made and relatively easy to theme UI lib with lots of components that follow Google's Material Design. I'd like to hear some feedback on this.

I've also move FindBar from `/containers` to `/components` but there is still some strange constant being exported from it that belongs to `actions` IMO: https://github.com/netlify/netlify-cms/blob/dashboard-link/src/components/UI/FindBar/FindBar.js#L7 Can someone take a look at it?

This PR closes #49, #51 and #71. 

It still has some rough edges that I would like to work on:

* [ ] Toggle drawer button should reflect the state of it
* [ ] Replace the "Dashboard" with the Netlify logo
* [ ] Show amount of posts for each collection
* [ ] Customize default theme to match Netlify colors (#62)

Thoughts?

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by cassiozen** [comment]
LGTM  (Although looks like it closes #51, but not #49.)

**Comment by okonet** [comment]
Yeah. It's still in progress.

**Comment by okonet** [comment]
Can someone review this one please?

**Comment by cassiozen** [comment]
LGTM

**Pull request merged**
