### PR TITLE
Update DOCS: Working with a Local Git Repository

### PR DESCRIPTION
**Pull request by rodnolan**
**Summary**

While attempting to use the beta feature [Working with a Local Git Repository](https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository) I found some errors in the docs. Specifically, I was trying to use a custom port but the configuration options described in step 3 didn’t work. I kept getting an error telling me that the default port (8081) was in use.

The [netlify-cms-proxy-server docs](https://github.com/netlify/netlify-cms/tree/master/packages/netlify-cms-proxy-server) mention that you have to create an .env file in the project root but this step isn’t mentioned in “our” instructions.

Also, the suggested updates to `config.yml` cause config errors…

```
Error loading the CMS configuration
Config Errors:
  'local_backend' should be boolean
  'local_backend' should NOT have additional properties
  'local_backend' should NOT have additional properties
  'local_backend' should match exactly one schema in oneOf
Check your config.yml file.
```
I managed to get my configuration working so I'd like to update the docs to reflect what works.

**A picture of a cute animal (not mandatory but encouraged)**
IMG_3345
Tim says hi!

### CODE REVIEW

**Review by erezrokah — CHANGES_REQUESTED** [review]
Thanks @rodnolan, working with a local git repo configuration has 2 parts:
1. CMS configuration
2. Proxy server configuration

The docs describe the first part, your change describes the second part.

How about we keep both?

**Comment by rodnolan** [comment]
> Thanks @rodnolan, working with a local git repo configuration has 2 parts:
> 
> 1. CMS configuration
> 2. Proxy server configuration
> 
> The docs describe the first part, your change describes the second part.
> 
> How about we keep both?

For me, following these instructions...

image

led to errors that prevented me from starting the CMS. See below: 

```
Error loading the CMS configuration
Config Errors:
  'local_backend' should be boolean
  'local_backend' should NOT have additional properties
  'local_backend' should NOT have additional properties
  'local_backend' should match exactly one schema in oneOf
Check your config.yml file.
```

If the error message is accurate, the suggestion to add the `url` and/or the `allowed_hosts` properties to `config.yml` _should_ be removed. Does that make sense or am I still missing something?

If I'm misinterpreting the instructions, I'd like to rework them to be less confusing. I'm happy to write the update, I just need to understand the right way to configure everything.

**Comment by erezrokah** [comment]
> If the error message is accurate, the suggestion to add the `url` and/or the `allowed_hosts` properties to `config.yml` _should_ be removed. Does that make sense or am I still missing something?

I was able to use the configuration:
```yaml
local_backend:
  url: http://localhost:8082/api/v1
  allowed_hosts: ['192.168.0.1']
```
successfully.

Can you share your full config file or open an issue with a reproduction repo?

I think the error message is not conveying the underlying cause, but I believe the docs are correct

**Comment by erezrokah** [comment]
Closing the PR per my comment. For the CMS errors, please submit a new issue and include the full `config.yml` so we can reproduce.

**Comment by dev6rodn** [comment]
I've been experimenting a bit with this over the last couple of days. I did get the CMS running locally on a custom port but I still had to add the `.env` file to make it work. I'll file a new issue with my suggested updates. Cheers!

**Pull request closed without merging**
