### PR TITLE
make widget docs editable

### PR DESCRIPTION
**Pull request by erquhart**

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 9d163c23aa9442ffcd745109a9ef0ef9343a03fc

https://deploy-preview-1782--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 68d7765c96adfccd90c04163b6072c19fba13bb9

https://deploy-preview-1782--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 7427eec6edd036e0dc47c15e94011087324bce51

https://deploy-preview-1782--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 4f8dff9ba32307046a9ef9c3f65c1ac2707c3fba

https://deploy-preview-1782--cms-demo.netlify.com

**Comment by erquhart** [comment]
Awesome, and agreed, especially on structured content 👍 👍

**Pull request merged**
