### PR TITLE
fix: list markdown widgets

### LINKED ISSUE #4460: Markdown widgets in lists are duplicated when content changed after prior item is removed
**Describe the bug**

When adding multiple markdown widgets to a list and removing an item at the beginning afterwards, a change on a remaining item triggers the recreation of that list item on it's original index (an duplicating the content). This is a pretty nasty bug because uses can unintentionally change entire parts of the page without even noticing.

A simple string list behaves as expected.

**To Reproduce**

screencast 2020-10-14 19-55-29 2020-10-14 20_04_25

I have created a codesandbox, it uses the latest version of netlify cms to date (2.12.27):

https://codesandbox.io/s/netlify-cms-app-example-forked-9xn5s?file=/src/NetlifyCMS/config.json (PLEASE TRY IN CHROME)

I have tracked down the issue to this release:

https://github.com/netlify/netlify-cms/commit/b151bdfd7311472eaa1861e9fc17546a3658a083

specificly to `netlify-cms-widget-list@2.4.4` and I think the bug was likely introduced in #3611, but I don't know where to start debugging this. When I change the dependency `netlify-cms-app` in my codesandbox to `2.12.9` which uses `netlify-cms-widget-list@2.4.3` the problem is gone. I double checled this by installing `netlify-cms-widget-list@2.4.3` in a local project with the latest netlify cms version and using it for lists instead and the problem disappeared also.

So I am pretty sure `netlify-cms-widget-list@2.4.4` broke somthing here, but I am not sure why only in combination with the markdown widget.

**Expected behavior**
Should not duplicate list items after remove on change.

**Applicable Versions:**
 - Netlify CMS version: latest (2.12.27)
 - Git provider: all
 - OS: MacOS
 - Browser version: chrome 85
 - Node.JS version: 12lts

**CMS configuration**
see codesandbox

Thanks a lot guys!

### PR DESCRIPTION
**Pull request by barthc**
Closes #4460

### CODE REVIEW

**Comment by toxsick** [comment]
Hey guys, can somebody please review this?

Thanks and regards

**Comment by erezrokah** [comment]
Hi @toxsick, there are other PRs pending review before this one. We'll review this one after those

**Comment by toxsick** [comment]
Hey @erezrokah, thanks for the info. Have a good week.

**Review by erezrokah — APPROVED** [review]
Thanks @barthc, sorry for the delayed review

**Pull request merged**
