### PR TITLE
Update Docs: Backends “gitlab-backend”

### PR DESCRIPTION
**Pull request by travigd**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by travigd** [comment]
It looks like the editor made some changes that aren't directly a part of what I meant to change (changing indentation, changing `_foo_` to `*foo*`).

At any rate, I ran into an issue where other users could not make edits (with a cryptic API error) because they only had "developer" permission, not "maintainer" permission, so thought I'd share.

**Comment by erezrokah** [comment]
Thanks @travigd, I re-phrased the added text into a note so the first paragraph won't be too long.

**Comment by travigd** [comment]
While I'm here,

It's also unclear from the docs (and I'm still unsure) whether or not one can use the _Web Application Flow_ auth flow if your site is not hosted on Netlify, or if you *have* to use _Implicit Grant_.

**Comment by erezrokah** [comment]
We have that part [here](https://www.netlifycms.org/docs/external-oauth-clients/) but I haven't seen a client that supports GitLab flow (maybe that had changed).

**Pull request merged**
