### PR TITLE
Docs: Add yourself as a contributor

### LINKED ISSUE #676: Provide instructions for adding a new contributor to the README
Thanks to the work of @DirtyF, we now have an all-contributors listing on the README, recognizing contributions of a variety of types. 🎉 

Now we just need some instructions to make it easy for anyone to add new contributors to the list. I'm thinking it makes sense to add it to CONTRIBUTING.md, and link to it from the contributor list in the README.

### PR DESCRIPTION
**Pull request by DirtyF**
Fix #676 

- [x] Add instructions to `CONTRIBUTING` to add yourself as a contributor (copied from the original project)
- [x] Following those instructions and adding myself as a contributor  😄 

/cc @verythorough

### CODE REVIEW

**Comment by verythorough** [comment]
Thanks! I have a few comments on the instructions that I'll be adding shortly, between talks at GitHub Universe. :)

**Comment by verythorough** [comment]
@Benaiah I was thinking so, but you know, it's already an improvement as is, so I guess we're good to merge!

As for my comments, I'm thinking of ways to make this process simpler for people who don't have the repo cloned and installed locally, but that can certainly wait.

Merging!

**Comment by DirtyF** [comment]
@verythorough Alternatively you can add yourself to the `.allcontributors.rc` JSON file but this means a maintainer will then have to run the generate contributors script (by hand or through a hook).

As this is a node project, I thought the majority of contributors were familiar with npm scripts.

**Comment by verythorough** [comment]
@DirtyF Yeah, I'm more thinking of people who write external tutorials or file detailed bug reports, for example. Or maybe they corrected typos using the Github web UI. All of these contributions are valued in the all-contributors spec, but in all of these cases, you don't need to clone the repo to make a contribution.

In these cases, perhaps filing an issue to add a person is a feasible alternative, since it's pretty easy for any regular contributor who's already cloned and installed to just run the command an push it.

**Comment by DirtyF** [comment]
I agree it would be more effective to have a script that fetch the data from GitHub and not asking users about this, but it isn't what allcontributors do.

There are other similar projects on Github like https://github.com/LABHR/hatrack

With all the people who ever left a comment you're over 200:
https://labhr.github.io/hatrack/#repo=netlify/netlify-cms

**Comment by verythorough** [comment]
Interesting concept. I hadn't seen that tool. I do like the human interaction required with all-contributors, though, because, for example, not all contributors might comment, and not all "+1 fix now plz" comments really qualify as contributions.

In the end, the all-contributors process is pretty low friction, and I really appreciate your integrating the cli tool to make it so. My penchant for making sure docs address as many use cases as possible shouldn't detract from that. Thanks again for making this happen!

**Pull request merged**
