### PR TITLE
fix: double slashes when gateway_url contained a backend

### PR DESCRIPTION
**Pull request by tech4him1**
**Summary**

For example, if the `gateway_url` is set to `https://www.my-netlify-site.com/.netlify/git/github`, it was being changed to `https://www.my-netlify-site.com/.netlify/git//github` (notice the double slash).  This commit stops adding the extra slash.

**Test plan**

Test manually.

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 2b9d7291536131d66db71364a78338c6b2eef1f2

https://deploy-preview-1712--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 2b9d7291536131d66db71364a78338c6b2eef1f2

https://deploy-preview-1712--cms-demo.netlify.com

**Comment by erquhart** [comment]
Oh just noticed the WIP, I'll hold off.

**Comment by tech4him1** [comment]
@erquhart I just haven't tested it yet, once it's tested it's good to go.

**Pull request merged**
