### PR TITLE
Update widget docs

### PR DESCRIPTION
**Pull request by verythorough**
**- Summary**
Adds a complete reference for each type of built-in widget. Covers most of the outline in https://github.com/netlify/netlify-cms/issues/619#issuecomment-335689598, but still needs screenshots, and could probably use some improvements in the Custom Widgets (formerly Extending) page. Provides a temporary improvement until @hcavalieri finished the bigger improvements he's working on in #866.

Closes #157.

**- Test plan**
I've based the configuration samples on the widget code and existing configs where available, but I haven't had a chance to actually apply and test all of them. Adding them all to a single collection in the cms-demo config could be an option for testing them directly.

You can check rendering by visiting the updated pages:
- [Updated Widgets doc](https://docs-update-widgets--netlify-cms-www.netlify.com/docs/widgets/) with new widget reference and basic validation info included
- [Renamed Custom Widgets doc](https://docs-update-widgets--netlify-cms-www.netlify.com/docs/custom-widgets/) (formerly Extending), with advanced validation section included

**- Description for the changelog**
Updated widget configuration docs

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit abe9001d746b0f03a49f1bb84aaba1062360bd30

https://deploy-preview-876--netlify-cms-www.netlify.com

**Comment by tech4him1** [comment]
@verythorough Maybe add something about how you can use either object format for any of the widgets, i.e.:
```
  - {label: "Draft", name: "draft", widget: "boolean", default: true}
```
or
```
  - label: "Draft"
    name: "draft"
    widget: "boolean"
    default: true
```
Right now it kind-of looks like you can only use one type for some, and the other type for others.

**Comment by verythorough** [comment]
Yeah, I know what you mean. I debated including it, though, because it's really a matter of yaml syntax, and applies to any place where implementers are using yaml.

What do you think about if I add a sentence to the intro about how all fields are in yaml, and can be written in block or inline form, with a link to a yaml syntax reference?

For references, Ansible has a nicely formatted [doc](http://docs.ansible.com/ansible/latest/YAMLSyntax.html), but could cause confusion. The [description on wikipedia](https://en.wikipedia.org/wiki/YAML#Basic_components) is nearly as clear, and probably a better reference. (The actual YAML page is not that helpful.) I can also link (here, and in other config docs) the [YAML linter](http://www.yamllint.com/).

**Comment by verythorough** [comment]
Added this new note:

> Widgets are specified as collection fields in the `config.yml` file. Note that [YAML syntax](https://en.wikipedia.org/wiki/YAML#Basic_components) allows lists and objects to be written in block or inline style, and the code samples below include a mix of both.

**Comment by tech4him1** [comment]
> What do you think about if I add a sentence to the intro about how all fields are in yaml, and can be written in block or inline form, with a link to a yaml syntax reference?

That sounds good, and I don't know if we even need a reference link, just something to the effect of "Some of the examples are in a block format, and some are in a YAML inline format, but either works the same."

**Pull request merged**
