### PR TITLE
Open Authoring bugfixes and pagination improvements

### PR DESCRIPTION
**Pull request by Benaiah**
**Summary**

Fixes bugs introduced by Open Authoring changes, and correctly handles paginated endpoints in the GitHub API. Also renames Fork Workflow to Open Authoring throughout the whole codebase, including renaming `backend.fork_workflow` to `backend.open_authoring`.

**Test plan**

Tested manually.

### CODE REVIEW

**Comment by erezrokah** [comment]
Hey @Benaiah thank you for these fixes.
I think there are some more potential changes/fixes:

- https://github.com/netlify/netlify-cms/pull/2456#discussion_r308687145
- https://github.com/netlify/netlify-cms/pull/2456#discussion_r308695658
- https://github.com/netlify/netlify-cms/pull/2456#discussion_r309632154
- https://github.com/netlify/netlify-cms/pull/2456#discussion_r309633387


I think the last two are more important than the first two.

**Comment by Benaiah** [comment]
@erezrokah thanks so much for finding those and letting me know! I'm looking through the bugs you noted in that PR to make sure I get them all taken care of in this one.

**Comment by Benaiah** [comment]
All the bugs noted by @erezrokah should now be fixed (thanks so much for finding those!). This PR should now be ready to merge.

**Comment by erquhart** [comment]
Just noticed failing tests, investigating.

**Comment by erquhart** [comment]
Failed linting, not sure how that only happened in CI, but not CD.

**Comment by melbourne2991** [comment]
@erquhart You might already be across this but there seems to have been some sort of regression (I  haven't pinpointed which commit is responsible exactly) but I am getting a 401 when loading entries because the incorrect URL is being requested:

```
/.netlify/git/github/repos//contents/src/pages/blog?ts=1567345646611&ref=master
```
Should be:
```
/.netlify/git/github/contents/src/pages/blog?ts=1567345646611&ref=master
```

**Comment by barthc** [comment]
@melbourne2991  I am also seeing this issue, could you open an issue for it?

@Benaiah `entriesByFolder`  `entriesByFiles` etc

**Comment by melbourne2991** [comment]
@barthc 
https://github.com/netlify/netlify-cms/issues/2629

**Pull request merged**
