### PR TITLE
Add blog post about implementing the CMS with Jekyll, add support for canonical URLs

### PR DESCRIPTION
**Pull request by sddaniels**
**Summary**

This is a guest blog post from Dwolla that contains a short review and a tutorial on how to migrate a standard Jekyll GitHub Pages site to Netlify + Netlify CMS. It also contains a small new feature to add support for canonical URL links in blog posts.

**Test plan**

Run the website and view the blog post.

### CODE REVIEW

**Comment by erquhart** [comment]
Thanks so much for adding the canonical url to the template! I don't think the build failure is related to this PR, will confirm.

**Comment by erquhart** [comment]
Forgot we're linting the website directory, it was just a formatting thing. Fixed.

**Comment by erquhart** [comment]
Added the link to the original post as well, will merge once builds pass.

**Comment by sddaniels** [comment]
> Added the link to the original post as well, will merge once builds pass.

Thanks for catching, I must have missed that. Is it maybe worth adding a note in the website readme along with the yarn commands?

**Comment by erquhart** [comment]
Yeah that would be great :)

**Pull request merged**
