### PR TITLE
fix: Implement Relative Sizing in SearchBar

### PR DESCRIPTION
**Pull request by tinfoil-knight**
**Summary**
This PR replaces the absolute sizes in  spacing and fonts with relative sizes wherever necessary as suggested by @austincondiff.

**Test plan**
None

### CODE REVIEW

**Comment by tinfoil-knight** [comment]
Please review and merge the PR @austincondiff

**Comment by erezrokah** [comment]
Hi @tinfoil-knight, what's the status of this PR?

**Comment by tinfoil-knight** [comment]
@erezrokah Please resolve the conflicts and merge it.

**Comment by erezrokah** [comment]
Going to close the PR since it looks like those changes were done in https://github.com/netlify/netlify-cms/commit/6d2f19b4d2fdf7dc5873549d82e09a51869477fa

**Pull request closed without merging**
