### PR TITLE
chore: timeout-requests closes #3605

### LINKED ISSUE #3605: Chore: add timeout mechanism to our fetch API calls
On some occasions fetch API calls can hang for quite some time before they fails.
We should implement a timeout mechanism around our fetch calls to fail faster.

See:
image
 The last request took a couple of minutes to fail while showing nothing in the CMS UI.

### PR DESCRIPTION
**Pull request by tinfoil-knight**
**Summary**
Fixes #3605

**Test plan**

`yarn test` failed 3 tests because the tests now expect different outcomes.

### CODE REVIEW

**Comment by tinfoil-knight** [comment]
@erezrokah I don't know how to test if this is working or not.

**Comment by erezrokah** [comment]
Thanks for this @tinfoil-knight, cool usage of the AbortController.
I think if you implement it here https://github.com/netlify/netlify-cms/blob/cf57284f40141712e3265992bdf6966a5c81f838/packages/netlify-cms-backend-proxy/src/implementation.ts#L86 and add fake timeouts in the proxy server:
https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-proxy-server/src/middlewares/localFs/index.ts you could test it using the `local_backend: true` flag.

**Comment by erezrokah** [comment]
For testing purposes maybe we can create a separate util function (maybe add it to `unsentRequest`)  that wraps `fetch` with an abort controller then we can add unit tests for that functionality.

Then we could even have a single where we override the global fetch (probably `bootstrap.js`) with the abortable one (then we won't have to remember to do it on every usage).

**Comment by tinfoil-knight** [comment]
Adding a polyfill for IE will add 3 dependencies since IE doesn't support the fetch API.
Here's a polyfill package I found: [abortcontroller-polyfill](https://www.npmjs.com/package/abortcontroller-polyfill)
Does that work?
Or should I look into `XMLHttpRequestEventTarget.ontimeout` ?

**Comment by erezrokah** [comment]
Hmm, how about we drop the `polyfill` and implement the timeout only if we see that the browser support abort controller?

**Comment by tinfoil-knight** [comment]
@erezrokah Help needed.
The pre-defined tests are receiving an empty signal. I don't know how to fix the tests.
```js
github API › request › should fetch url with authorization header

    expect(jest.fn()).toHaveBeenCalledWith(...expected)

    - Expected
    + Received

      "https://site.netlify.com/.netlify/git/github/some-path",
      {"cache": "no-cache", "headers": {"Authorization": "Bearer token", "Content-Type": "application/json; charset=utf-8"}},
    + {"signal": {}},
```

**Comment by erezrokah** [comment]
Hi @tinfoil-knight, not sure but we're mocking the fetch API in those tests https://github.com/netlify/netlify-cms/blob/6c229c5149e3beff05bcfb42ca286d3e9170e54e/packages/netlify-cms-backend-github/src/__tests__/API.spec.js#L94.
We will need to check if/how the Abort Controller is implemented/mocked in a jest.

**Comment by tinfoil-knight** [comment]
I couldn't find anything related to aborting requests that would send a correct `AbortSignal` in jest.

**Comment by erezrokah** [comment]
Ok, how about you commit your latest changes, then let me know and I'll try to fix the tests.

**Comment by tinfoil-knight** [comment]
@erezrokah All the code has been already committed.

**Comment by tinfoil-knight** [comment]
@erezrokah I've already pushed the code in the PR. I manually tested using the backend-proxy-server as you said. The timeouts were working. You can fix the tests now. Thanks!

**Comment by erezrokah** [comment]
@tinfoil-knight, sorry for the delayed response, I made a few changes and fixed the tests. Let me know what you think

**Comment by tinfoil-knight** [comment]
Thanks @erezrokah for fixing things. Everything's great.

**Pull request merged**
