### PR TITLE
feat(netlify-cms-core) Overwrite language

### PR DESCRIPTION
**Pull request by d62remi**
**Summary**

You can overwrite the default language of the environment with two means:
- with global window variable `CMS_OVERWRITE_LANG`
``` html
<script>
    window.CMS_OVERWRITE_LANG = {
      locale: 'fr',
      phrases: {
        app: {
          header: {
            content: 'Contenus',
            workflow: 'Flux de travail',
            media: 'Médias',
            quickAdd: 'Ajout rapide'
          }
        }
      }
    }
</script>
<!-- import netlify-cms after -->
<script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>
```
- with [manual initialization](https://www.netlifycms.org/docs/beta-features/#manual-initialization)
``` js
  init({
    config:{
      overwriteLang: {
        locale: 'fr',
        phrases: {
          app: {
            header: {
              content: 'Contenus',
              workflow: 'Flux de travail',
              media: 'Médias',
              quickAdd: 'Ajout rapide'
            }
          }
        }
      }
    }
  })
```
**You can access all the variables available [here](https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-core/src/constants/defaultPhrases.js)**

`locale` represents the expected language

`phrases` will be merged with existing phrases object, and any part that conflicts with existing phrases will be overwritten.

Sorry for my english, i'm french =D

#789 
#2128

### CODE REVIEW

**Comment by d62remi** [comment]
You can add programmatic logic :
```js
window.CMS_OVERWRITE_LANG = [
    {
        locale: 'fr',
        phrases: {}
    },
    {
        locale:'de',
        phrases: {}
    }
].find(function(e){
   return e.locale === navigator.language
})
```

**Comment by Mayaela** [comment]
any news on this ?

**Comment by d62remi** [comment]
I am still waiting

**Comment by erezrokah** [comment]
closing due to https://github.com/netlify/netlify-cms/pull/2870

**Pull request closed without merging**
