### PR TITLE
Docs: change unpkg links to pull latest release

### PR DESCRIPTION
**Pull request by verythorough**
**- Summary**
html snippets in the docs demonstrate loading the CMS via an unpkg.com link that's pinned at v0.3 (or 0.x in a few places). This changes the link to point to the latest release instead.

**- Test plan**
None

**- Description for the changelog**
Docs: update links to unpkg.com to pull the latest release of Netlify CMS.

**- A picture of a cute animal (not mandatory but encouraged)**
http://i.imgur.com/rDiVe2z.gifv (technically not an image, but too cute)

### CODE REVIEW

**Comment by verythorough** [comment]
After discussion, it seemed to make more sense to pin to the minor version than to pull latest. Note that we'll need to update this whenever there's a minor version release (or set up a method like Webpack's Define plugin to handle it).

**Comment by bdougie** [comment]
FYI, my serverless docs deploy hook is broken. I am going to look into it tomorrow morning, this got busy :)

**Comment by bdougie** [comment]
@verythorough and @erquhart I am happy to say, the cms docs webhook works now. So as soon as this is merged it should trigger a deploy to the cms-www. 

https://github.com/netlify/netlify-cms-docs-webhook

The webhook is hosted on my AWS account, I will ask about getting this on the Netlify creds on Monday, but for now, try to stay under 1 million merges this month :)

**Comment by bdougie** [comment]
I stand corrected, I got another error, but I will fix

**Pull request merged**
