### PR TITLE
feat: add preDeployPreview hook

### LINKED ISSUE #3964: Add deploy preview hook to CMS
**Is your feature request related to a problem? Please describe.**
I need to format the preview link given from the target_url statuse api.
Indeed, my deploy provider is giving it in the wrong format.

**Describe the solution you'd like**
A simple hook that would allow me to edit the deploy preview url

**Describe alternatives you've considered**

**Additional context**
Could be done like https://github.com/netlify/netlify-cms/pull/3812

### PR DESCRIPTION
**Pull request by maxerbox**
Close #3964

**Summary**

Allow better preview url customization
The base url was not editable with the config

**Test plan**

Tested with a local build, working fine :

Code used : 
```js
CMS.registerEventListener({
  name: 'preDeployPreview',
  handler: ({ deploy, ...all }) => {
    console.log(deploy.get('url'), all)
    return 'https://reddit.com'
  },
})
```

**A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

**Comment by erquhart** [comment]
@maxerbox thanks for this! I do think adding support for your use case makes sense, but I'm not sure an event is the right entry point. This is not an event driven transformation, so it would be better to find a more suitable API surface.

The right primitive in the context of our current API is probably `registerDeployPreviewUrlFormatter()`. Yes this is a long and terrible name, can't think of a great way to shorten.

Let me know what you think and whether you're up for implementing. I'd also recommend waiting for a thumbs up from @erezrokah before doing so, in case he has other thoughts.

**Comment by erezrokah** [comment]
Agree with @erquhart and sorry for taking a long time to respond. I wanted to make sure I give it some thought.

It would be great if we could leverage the [existing method](https://www.netlifycms.org/docs/deploy-preview-links/#configuring-preview-paths) of configuring preview urls, to avoid having two ways of doing the same thing, but I wasn't able to think of anything yet.

Maybe `preview_url_formatter: ['regex', 'replacer']`.
Since you can reference `regex` groups in `replacer` that would resolve the issue and close to the existing API.
WDYT?

**Comment by erquhart** [comment]
I was also trying to think of way to handle it through static config, agreed it would be ideal but couldn't find a suitable approach - this could work really well.

@maxerbox your use case would look something like this:
```yaml
preview_url_formatter: ["([\w-]+)\/(\w{9})$", "https://{{$2}}-{{$1}}.xxxx.app"]
```

**Comment by erezrokah** [comment]
Closing as we would like to see this implemented as `preview_url_formatter: ['regex', 'replacer']`

We would be happy to accept a new PR for this, have this one modified.

**Pull request closed without merging**
