### PR TITLE
Editorial Workflow support for GitLab

### PR DESCRIPTION
**Pull request by erquhart**
Replaces #1817 (abandoned).

The code in this PR was authored by a community contributor, with the intent to add editorial workflow support for the GitLab backend.

This PR needs proper testing both in code and in practice to ensure against regressions. It's also highly likely that more work needs to be done in general, but again, that's difficult to ascertain without testing.

Rebased onto latest master as of 6/26/19, which provides some regression tests.

### CODE REVIEW

**Comment by jaredvacanti** [comment]
Is there a roadmap or plan for this feature development? I am willing to contribute with a little feedback on current intentions (Note: I haven't contributed to Netlify before but I work with GitLab extensively)

**Comment by erquhart** [comment]
Just needs to be completed and tested thoroughly - backend API methods have very few tests currently, so merging as is isn't safe. Also, a lot of the code was copy/pasted from the GitHub backend, which lowers my confidence, as GitHub and GitLab certainly have API differences. Some bugs are documented in comments on the original PR #1817, such as pull request merging not taking into account open/unresolved discussions, likely a symptom of reusing GitHub backend code.

**Comment by theetrain** [comment]
Linking this to #568 for contextual awareness.

**Comment by erezrokah** [comment]
Closing in favor of https://github.com/netlify/netlify-cms/pull/3014

**Pull request closed without merging**
