### PR TITLE
Field unique id branch

### PR DESCRIPTION
**Pull request by xifengjin88**
**- Summary**
Closes issue #423
Current PR fixes a11y issues by adding a unique ID to form fields 

**- Test plan**
Tested locally, as I type into the input field, label, and its corresponding input field all have the same unique id

screen shot 2018-02-06 at 9 09 25 pm

screen shot 2018-02-06 at 9 09 08 pm

**- Description for the changelog**

added a unique id to the input field and its label

**- A picture of a cute animal (not mandatory but encouraged)**

cute

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 2e0a3923736b051d02296a3cc0502b9576553bf8

https://deploy-preview-1087--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 2e0a3923736b051d02296a3cc0502b9576553bf8

https://deploy-preview-1087--cms-demo.netlify.com

**Comment by erquhart** [comment]
This is great @xifengjin88, thanks! Mind adding yourself to the all contributors list? Instructions here: https://github.com/netlify/netlify-cms/blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor

**Comment by xifengjin88** [comment]
@erquhart Just added myself as a contributor. thanks for your help.

**Comment by xifengjin88** [comment]
@erquhart Hi, just want to make sure this PR is successfully approved. I still see some conflicts.

**Comment by erquhart** [comment]
Fixed, will merge in a sec.

**Pull request merged**
