### PR TITLE
Fix #789: Add cms translation support

### LINKED ISSUE #789: Translation
**- Do you want to request a *feature* or report a *bug*?**
feature

**- What is the current behavior?**
the cms is only in english
**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**
it might be possible to select the default language in Netlify and also be able to change it in CMS.
**- Please mention your CMS, node.js, and operating system version.**

### PR DESCRIPTION
**Pull request by chrfritsch**
**Summary**
Adding support for multiple languages in the cms. 
I would propose that we add translated phrases to the cms and the user can choose by config which language he wants to load. 

**Test plan**

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by chrfritsch** [comment]
My current problem is, I don't know how to load the config during the bootstrap.

**Comment by benavern** [comment]
Hi,
I am very  interested in translating the CMS in french.
Is it the place to do it, or should I wait for the PR to be merged ?
Thanks in advance! :)

**Comment by benavern** [comment]
By the way, for your problem:
I think the config is already there in the at line 21 or in the store line 57. You should just get it from the config file.

**Comment by erquhart** [comment]
Hey @chrfritsch - apologies for the delay on reviewing this!

The plan for translating the UI is here: https://github.com/netlify/netlify-cms/issues/789#issuecomment-417174441, but it should also be stated that we don't want to hardcode all languages, they should be registered as extensions. So a bit of API architecture thinking will be required.

**Comment by erezrokah** [comment]
closing due to  https://github.com/netlify/netlify-cms/pull/2870

**Pull request closed without merging**
