### PR TITLE
Increase gitlabs' merge requests fetched to 100

### PR DESCRIPTION
**Pull request by nevans**
Fixes netlify#5307 (or at least, attempts to improves it)

Summary

The Gitlab workflow only shows 20 items. It's very confusing and concerning to users when there is a large backlog of drafts (e.g. during the initial content-loading period of a new website) but only a "random" assortment of drafts is shown. This simply increases that limit up to 100.

Test plan

I have not tested this yet, at all. Not one bit. It might do nothing, or it might simply crash. Nor does it look like there are any previously existing tests for this function in the __tests__ dir. Please don't merge this without verifying I haven't broken things! (I'll eventually test it myself, but I've no time for that today.)

### CODE REVIEW

**Comment by erezrokah** [comment]
Thanks @nevans, it will be great if someone can test this, or provide a repo to test this before we merge.

**Comment by erezrokah** [comment]
> Thanks @nevans, it will be great if someone can test this, or provide a repo to test this before we merge.

You can do this by loading the CMS from `https://deploy-preview-5320--cms-demo.netlify.app/dist/netlify-cms.js`

**Review by erezrokah — APPROVED** [review]
It's all good :) I confirmed this works using a repo I created.

**Comment by nevans** [comment]
THANKS @erezrokah! I probably wasn't going to get to it until Thursday/Friday, but now I can probably show it off to some of the users on Frday. :)

**Pull request merged**
