### PR TITLE
Fix missing line breaks in code example in Custom Widgets documentation

### PR DESCRIPTION
**Pull request by delucis**
**- Summary**

The [Custom Widgets docs page](https://www.netlifycms.org/docs/custom-widgets/) has a code example missing line breaks, making it hard to read.

**- Description for the changelog**

Fix missing line breaks in Custom Widgets docs page.

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 1002b9fb1ca38fa1f546a1ffc1f29c2f128fd9d8

https://deploy-preview-1010--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 1002b9fb1ca38fa1f546a1ffc1f29c2f128fd9d8

https://deploy-preview-1010--cms-demo.netlify.com

**Comment by verythorough** [comment]
Thanks, @delucis! Could you [add yourself](https://github.com/netlify/netlify-cms/blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor) to our all-contributors list?

**Comment by delucis** [comment]
Thanks for merging @verythorough, and sorry for missing the contributors list step. Just opened a PR for that now.

**Pull request merged**
