### PR TITLE
Update gotrue

### PR DESCRIPTION
**Pull request by biilmann**
This updates gotrue-js to the latest version

### CODE REVIEW

**Comment by tech4him1** [comment]
@biilmann mind if I rebase this? or are you still working on it?

**Comment by erquhart** [comment]
@tech4him1 should be fine to rebase.

**Comment by tech4him1** [comment]
Rebased, please squash on merge.

**Comment by tech4him1** [comment]
@Benaiah does this fix the token refresh issue that you mentioned?

**Comment by Benaiah** [comment]
@tech4him1 I'm not sure if it does yet, but I'm hoping so. I'll update here when I know for sure.

**Pull request merged**
