### PR TITLE
Fix relation lists (regression #359)

### LINKED ISSUE #359: Only partial relation metadata available on list previews
**- Do you want to request a *feature* or report a *bug*?**
* BUG

**- What is the current behavior?**
* When adding a field with the `relation` widget to a `list`, the metadata available (see https://github.com/netlify/netlify-cms/blame/7aa77baea9e64aaaf3f1a610543263426dc661b4/docs/customization.md#L181) from the list field is not complete, the only metadata available at any given time refers to the last child updated.

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Add a "collection1" with a field that can be referenced and some content in its directory.
2. Add a "collection2" with a `list` field, whose children refer to "collection 1" through `relation`, like:
```
- label: "People"
        name: "people"
        widget: "list"
        fields:
          - label: "Person"
            name: "person"
            widget: "relation"
            collection: "collection1"
            searchFields:
              - "title"
            valueField: "title"
```
3. Add a custom preview class through `CMS.registerPreviewTemplate` for "collection2" and monitor the values of `this.props.fieldsMetadata.get('people')` - there is only 1 entry, the last child edited on the `list` field.

**- What is the expected behavior?**
* On step 3 above, that metadata for every child of the `list` field is available, i.e., that for every item in `this.props.entry.getIn(['data', fieldName])` there is a corresponding item in `this.props.fieldsMetadata.get('fieldName')` filled with metadata.

**- Please mention your node.js, and operating system version.**
v6.9.5 on OS X 10.11.6

### PR DESCRIPTION
**Pull request by Quicksaver**
**- Summary**

Fixes #359 (regression)

**- Test plan**

- Not sure exactly when the regression happened, but the exact behavior described in #359 could be seen again for a few releases now.
- Tested manually in exactly the same way as in #360: adding, removing and updating any child of the list works, switching back and forth between pages and reloading the page has the correct metadata now.
- Tested also simple string relation fields, work as expected with the new code as well.
- Nothing to be changed in the docs, they don't really cover relation widgets much anyway.
- This definitely needs automated tests to prevent further regressions, but there's absolutely nothing covering relation fields already (that I could find), and I'm not familiar enough with the test platform or existing tests to jump in with no base.
- I'm having trouble running lint, it fails monumentally (~300k errors) even on the current master, so I'm skipping that.

**- Description for the changelog**

(Fix regression) Handle metadata for all children of a list field

**- A picture of a cute animal (not mandatory but encouraged)**
cute-baby-chickens-wearing-knit-hats1

### CODE REVIEW

**Comment by erquhart** [comment]
@Quicksaver thanks for this! Looks like relation previews are totally broken, both in the latest release and in this PR - this fix would have to go on top of a fix for the basic issue of relation previews not loading. Would you be able to take a look?

1. Check out the kitchen sink entry in the [deploy preview](https://deploy-preview-719--cms-demo.netlify.com/#/collections/kitchenSink/entries/a-big-entry-with-all-the-things) for this PR
2. Note that the preview for the Related Post field (first field in the entry) is missing
3. Change the value to the current post (search for "TOML" and reselect)
4. Note the preview is still missing
5. Change the value to a different post (search for "JSON" and select the post that pops up)
6. The preview is now present

If you can't look into this it's totally fine, someone will just need to before we can move forward with this PR.

**Comment by Quicksaver** [comment]
@erquhart sorry for not responding sooner. I did take a look at the kitchen sink example but I get a slightly different behavior than you. On step 4 I get the correct preview already, tried with the very latest master and with my patch, same behavior. But it is also missing when first loading the page for me. 

```fieldsMetaData``` is empty in the ```RelationKitchenSinkPostPreview``` component when first loaded apparently. I'll try to take a more thorough look over the next week to see if I can track it down, but if anyone wants to before I can please go ahead. 😃

**Comment by erquhart** [comment]
Some of this seems to have been (inadvertently) resolved in the UI overhaul, at least the base issue of the relation widget not working. Will follow up after UI overhaul is merged.

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit d76c90fdc41052d1662bc9496859a3d44edccb17

https://deploy-preview-719--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit d76c90fdc41052d1662bc9496859a3d44edccb17

https://deploy-preview-719--cms-demo.netlify.com

**Comment by Quicksaver** [comment]
@erquhart I rebased the commit and found out perhaps a better way of fixing the issue. Not sure if this was possible before or only now after the UI overhaul. But I've tested locally in the same way as before, all seems fine.

I should note that the relation widget in the kitchen sink entry doesn't appear during the first page load for me, not sure why that is although admittedly I haven't investigated too deeply. All of my custom relation widgets work just fine though, so that is likely a problem with the demo preview widget itself rather than with the CMS.

**Comment by Quicksaver** [comment]
@erquhart it was my pleasure, thanks for merging it in. 😃

**Pull request merged**
