### PR TITLE
Fix default value support in editor components

### LINKED ISSUE #1406: Specifying a default value doesn't work for fields in editor components
**- Do you want to request a *feature* or report a *bug*?**

*bug*

**- What is the current behavior?**

`string` Fields in editor components that specify the `default` option don't get populated with the default value when a new component is added. Seems to happen with all widgets (I tried with `string`, `number`, and `boolean`).

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Declare an editor component that contains a field with a `default`:

```js
CMS.registerEditorComponent({
  id: "youtube",
  label: "Youtube",
  fields: [{
    name: 'id',
    label: 'Youtube Video ID',
    widget: 'string',
    default: 'dQw4w9WgXcQ'
  }],
  pattern: /^youtube (\S+)$/,
  fromBlock: function(match) {
    return { id: match[1] };
  },
  toBlock: function(obj) {
    return 'youtube ' + obj.id;
  },
  // Preview output for this component. Can either be a string or a React component
  // (component gives better render performance)
  toPreview: function(obj) {
    return (
      '<img src="http://img.youtube.com/vi/' + obj.id + '/maxresdefault.jpg" alt="Youtube Video"/>'
    );
  }
});
```

2. Add an instance of the component to a markdown editor

Observe that the field is empty rather than being populated with the default value.

**- What is the expected behavior?**

That the field is populated with the specified default value, similar to how default values work for fields defined on collections.

As a sidecar feature request, it would be nice to be able to specify the default value as a function that returns it -- I would like to use a hidden field for automatically generating a uuid.

**- Please mention your versions where applicable.**

Netlify CMS version: 1.8.4
Browser version: Chrome 67.0.3396.62/OSX

Node.JS version: 9.5.0
Operating System: OSX 10.13.4 (High Sierra)

**- Please link or paste your `config.yml` below if applicable.**

### PR DESCRIPTION
**Pull request by papandreou**
**- Summary**

Fix #1406 -- see the description in the issue.

Also includes a simple implementation of #1407 that's at least compatible with custom components (but there's no way to achieve dynamic default values via config.yml). I needed this myself to get my automatically issued uuids to work, but feel free to ignore that commit if a solution for https://github.com/netlify/netlify-cms/issues/1409 is required to be a part of that feature.

**- Test plan**

I've tested it manually in my own application and found that the default values work with various widgets, including `hidden`.

**- Description for the changelog**

Editor components: Fix support for default field values

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit fe9c3fcd2acff6b7d9f7d8bb2d5d5bfb8cdbf829

https://deploy-preview-1511--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit fe9c3fcd2acff6b7d9f7d8bb2d5d5bfb8cdbf829

https://deploy-preview-1511--cms-demo.netlify.com

**Comment by papandreou** [comment]
I chose to pass the plugin definition/collection to the default value function, but I don't actually need that myself, and it might be a bit too opinionated :)

**Comment by erquhart** [comment]
We should hold off on the dynamic part in this PR and just support static default values. Fields in editor components should work exactly the same as fields that are not in an editor component, which is the basis for #1406 being considered a bug.

**Comment by papandreou** [comment]
@erquhart, fair enough. Feel free to only pull in the first commit (3560a61), then.

**Comment by tech4him1** [comment]
I'm pulling the static part of this out into a seperate PR, #1616. I'm going to close this one for now and just reference it in #1407 so we can look back at it later.

**Pull request closed without merging**
