### PR TITLE
GitHub access token

### LINKED ISSUE #1415: Can't access private repos
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Log in with github backend to access a private repo. My user has the correct privileges.

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Add NetlifyCMS to a private repo
2. Configure CMS to use github backend and provide `repo`
3. Try to Log In with github
4. Not Found notif is triggered

**- What is the expected behavior?**
Be able to login. My user has access to the repo

Netlify CMS version: 1.8.0
Browser version: Version 66.0.3359.181 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by pbrandone**
**Please be aware that this was a quick-fix that solved the problem for me. It wasn't properly tested and I don't know if this is the correct approach.**

I was having problems connecting to private repos even tho my user had the correct permissions.
- Created a personal access token in github
- Added a `token` field in `config.yml` under github's backend
- Updated github's `implementation.js` to give priority to that token

Closes #1415 

**- Summary**
Couldn't access private repos with github backend. Changed github's implementation to accept a token field in config.yml

**- Description for the changelog**
Allows `token` field in github's backend configuration

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 75a20e11b3f8b363e9030b6024781b6cd51c1c1b

https://deploy-preview-1416--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 75a20e11b3f8b363e9030b6024781b6cd51c1c1b

https://deploy-preview-1416--netlify-cms-www.netlify.com

**Comment by pbrandone** [comment]
On second thought this probably is a terrible idea unless we can somehow use some kind of env variables in the config file (to prevent the token from being committed)

**Comment by tech4him1** [comment]
> On second thought this probably is a terrible idea unless we can somehow use some kind of env variables in the config file (to prevent the token from being committed)

Yup, that's the main problem with this. Even if we generate it into the file as part of the build, the `config.yml` is then publicly accessible, so anyone can get your token (😱).

**Comment by tech4him1** [comment]
I'm going to close this for now and discuss in the issue, if that's alright with you.

**Comment by pbrandone** [comment]
@tech4him1 of course! thanks! 👍

**Comment by talves** [comment]
@pbrandone Thanks for taking the time to contribute. Sometimes things don't seem clear until we have a use case to review.

**Comment by pbrandone** [comment]
@talves sure! sorry for not thinking it through 😓

At least I managed to start building the cms while I don't have the proper org setup

**Comment by tech4him1** [comment]
@pbrandone Yes, definitely thanks for trying!

**Pull request closed without merging**
