### PR TITLE
WIP: Ship sources in NPM package.

### LINKED ISSUE #553: Ship source code with npm package
Currently running into an issue with an unhelpful help message:  `Collection must have a field name that is a valid entry identifier`

While investigating I found that ncms only ships with the minified source code. Also, the source mapping comment is missing from the js source so the source map provided will not be loaded by default.

It be great to be able to use the actual source code while I am debugging the cms with our apps.

### PR DESCRIPTION
**Pull request by tech4him1**
**- Summary**

Fixes #553.

**- Test plan**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 5754aac1b1fed118b958da9c7af909b33d087bfe

https://deploy-preview-1062--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 5754aac1b1fed118b958da9c7af909b33d087bfe

https://deploy-preview-1062--cms-demo.netlify.com

**Comment by erquhart** [comment]
@tech4him1 still happening?

**Comment by tech4him1** [comment]
@erquhart I still need to work on the sourcemap part of it -- thanks for the bump.

**Comment by tech4him1** [comment]
Closed in favor of https://github.com/netlify/netlify-cms/pull/1095.

**Pull request closed without merging**
