### PR TITLE
fix collection entries loaded check

### PR DESCRIPTION
**Pull request by barthc**
**Summary**
A simple fix for the widget `collectionEntriesLoaded` check.

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 77285be8a09235a494ab37e7b5c423b41be0ffee

https://deploy-preview-1881--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 77285be8a09235a494ab37e7b5c423b41be0ffee

https://deploy-preview-1881--cms-demo.netlify.com

**Comment by erquhart** [comment]
This looks correct, but can you explain the bug that this is fixing?

**Comment by erquhart** [comment]
It's just looking to see if any entities exist for the given collection - I'd have to look deeper to recall _exactly_ why I did this, but I'm almost certain it was a last minute hack when I was pushing 2.0 out the door to fix some aspect of state management when loading the editor. Checking for the collection to be loaded from the editor doesn't even make sense, pretty sure it's for a side effect.

But again, pretty sure this _won't_ always return false - there are deeper state management issues to tackle that I believe this points to. If there's a specific bug this is causing, we can definitely discuss that, but otherwise we should leave it for now until we take the time to dig through to the cause.

**Comment by barthc** [comment]
I tried inspecting the check `collectionEntriesLoaded` on the console while interacting with the app. It always returned false for me. The check is not causing any bug really, I am just looking to cut down the number of unnecessary API requests. Anyway, since the check is a fix for some aspect of state management, no problem. Closing this for now.

**Pull request closed without merging**
