### PR TITLE
fix: display UI to fork a repo only when fork doesn't exist

### LINKED ISSUE #2535: authoring beta feature Netlify CMS requires forking repo every time
**Describe the bug**

User is required to fork the repo every time they log in to the project, no only on the first time.
netlifycms_forkbug

- Related to ['Open Authoring beta feature'](https://www.netlifycms.org/docs/open-authoring/)
- Related PR
  - Beta Feature GitHub Fork Workflow #2430 
  - Forking in the Editorial Workflow #2096 

**To Reproduce**

1. Go to https://axway-open-docs.netlify.com/docs/
2. Click **Edit on Netlify CMS** (upper right corner)
3. Click **Login with GitHhub** to log in with your GitHub account
4. Click **Fork the repo** to fork the project (supposedly this is the first time you access it)
5. Do your updates, or not, and **Log out**.
6. After log out, click **Login with GitHhub** on the center of the page.

**Issue:** You're redirected to Fork again. And will continue to be every time you log out and log in to the project again.

**Note**: This does not actually create new/ numerous forks but's not a good UX.

**Expected behavior**
User should be asked to Fork the project just once, the first time they collaborate to it.

**Applicable Versions:**
- netlify-cms-app 2.9.8-beta.0
- netlify-cms-core 2.13.0-beta.0
 - Git provider: GitHub
 - OS: Windows 10
 - Browser version: chrome 76.0.3809.100, Edge 11]

**CMS configuration**
- Please link or paste your CMS `config.yml` here:
https://github.com/Axway/axway-open-docs/blob/master/static/admin/config.yml 

**Additional context**
NA

### PR DESCRIPTION
**Pull request by erezrokah**
Fixes #2535

Skip the UI part of asking to fork in case the fork exists.

### CODE REVIEW

**Comment by erquhart** [comment]
The issue here is that the user can have a fork with a different name than the origin repo, so the only surefire way to check for an existing fork is via the `fork` API, which creates a fork if it doesn't exist but always returns a fork. This is why we never created a straight method for checking for an existing fork.

**Comment by erezrokah** [comment]
Let me play a bit with the changed name scenario. Maybe we can list all user repositories and check against the `parent` property without relying on the name

**Comment by erquhart** [comment]
Code looks good, let me know when this is able to work for users who created the fork with a custom name (or if it does already).

**Comment by erezrokah** [comment]
I did a bit of testing. 

When you rename a repository and try to access the old name GitHub redirects to the new repository, so the code still works.

I tried to reproduce the scenario we disscused - setting a new name while forking, but when I try to fork a repository GitHub doesn't let me choose a new name - it just uses the origin repo name.

Do you mind trying to do the latter? Maybe I missing something here. If a user can't set a repository name while forking, and can only change it post forking, I think we're good.

Another option is to go over all of the user repositories and see if we have a matching fork (will be a bit slower, as we will need to fetch all repositories, filter by forked ones and fetch each one separately to get all the data as the `parent` property is only available when getting a single repo).

**Comment by erquhart** [comment]
Wow, yeah, same here. I really thought renaming was a thing but I guess not - looks like we’re good!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
