### PR TITLE
Upload images as part of editorial workflow

### PR DESCRIPTION
**Pull request by s0**
This pull request is still a bit of a work-in-progress, but I wanted to open a PR here to start a discussion on what needs to be done before we can get this merged in.

This Addresses issue #1344 by allowing users to upload images as part of an editorial workflow, which adds the images to the same branch as collection content, allowing for a couple of things:

* The default branch of the repo can be protected (e.g. only certain people approved to merge, require status checks before merge).
* Images can be made part of the review process in addition to the entry content.

This has currently only been tested with GitHub, it probably doesn't work on other backends at the moment, this will need to be tested first. It's based on the work of @ro-savage in https://github.com/Encrypt-S/netlify-cms/commit/a86b5e87655dfcb60b3ae743219a614dca034157, but has been rebased ontop of the latest code, and cleaned up a little bit.

Later on down the line, if the editorial workflow is updated to be compatible with fork-and-pr workflows on GitHub, these changes should automatically work there too.

### CODE REVIEW

**Comment by wakeless** [comment]
Hey @samlanning thanks for your hard work on this one, looks certainly like something that we want to use (uploading images as part of the PR as we don't allow commits direct to master)

I've straight away run into a problem wherein it looks like I've accidentally changed my PR into a `mediaOnlyPr` and now I can't see it in the editorial workflow or edit it :( I think I did this because I did a image uploader upload.

**Comment by erquhart** [comment]
@samlanning any thoughts on what @wakeless ran into?

**Comment by samlanning** [comment]
Sorry for not replying to this sooner.

Yeah that makes sense, I think the best way to solve for this would probably be to only allow media to be uploaded once a draft post has been "saved", and a PR opened, then using that existing PR.

**Comment by erezrokah** [comment]
Closing this as I'm working on the same issue #1344.
My initial commit is here: https://github.com/netlify/netlify-cms/commit/94934c29bba552543e8d9504bd4fd79043031ccf

I'm taking a slightly different approach of linking the media file to the draft entry and persisting everything together on save. It is still WIP though

**Pull request closed without merging**
