### PR TITLE
WIP: Add gitea backend support

### PR DESCRIPTION
**Pull request by lunny**
Fixes https://github.com/netlify/netlify-cms/issues/1109

### CODE REVIEW

**Review by erezrokah — CHANGES_REQUESTED** [review]
This is huge @lunny!
Great work.
Do you mind adding some docs as well so I (and others) can test it?
Also a checklist of items left to move this from `WIP` to `Ready For Review` would be helpful.

**Comment by erezrokah** [comment]
Not sure what to do with this. This would be great to have as a core backend, but needs some follow up.
@lunny can you share some setup instructions?

**Comment by lunny** [comment]
@erezrokah It seems there is no Gitea javascript SDK package. And I haven't set up the dev environment local. I will find more time to finish this PR.

**Comment by erezrokah** [comment]
Closing this PR, feel free to re-open when you have time to finalize it

**Comment by DevAhmedRagab** [comment]
Any update ?!

**Comment by lunny** [comment]
Sorry I have no enough time currently to finish it. Please pick up this if it's useful for your PR.

**Comment by DevAhmedRagab** [comment]
@lunny Can you please tell me from where i should start ?! or what you have done ?! and what should i do ?!

**Pull request closed without merging**
