### PR TITLE
Fix #1486 & #1466 & add contributor

### LINKED ISSUE #1486: Use HTML elements for accessibility #a11y
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

Many HTML elements used in the app are `<div>`s rather than semantically correct and accessible HTML elements (such as `<main>`, `<aside>`, `<li>` etc.). This means accessibilty software such as screen readers can't navigate the screen as effectively.

This is a refinement on https://github.com/netlify/netlify-cms/issues/1333 Accessiblity #a11y issues 

**- If the current behavior is a bug, please provide the steps to reproduce.**

Use a screen reader with the app. Alternatively, view source and see that eg the main content area `nc-collectionPage-main` uses a `<div>` rather than `<main>`.

**- What is the expected behavior?**

Use semantically correct HTML elements where possible 🙂

**- Please mention your versions where applicable.**

Netlify CMS version: 2.0.0-dev-dev
Browser version: 61.0

Node.JS version: v8.9.1
Operating System: MacOS 10.13.5

**- Please link or paste your `config.yml` below if applicable.**

### PR DESCRIPTION
**Pull request by growdigital**
**- Summary**

* Replaces divs with HTML elements #1486 
* Create HTML lists for list of collections in sidebar & EntryListing and EntryCard in main
* Add myself as a contributor

**- Test plan**

AFAIK, this has to be tested manually to see if any layout issues, as I'm not aware of any visual regression tests for project.

**- Description for the changelog**

Use semantic HTML elements in structure of app

Small chestnut horse peering out of a wood

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 3ebe695abc2ae274afe5a4e062d90bc839bc1bf8

https://deploy-preview-1501--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 3ebe695abc2ae274afe5a4e062d90bc839bc1bf8

https://deploy-preview-1501--netlify-cms-www.netlify.com

**Comment by erquhart** [comment]
@growdigital mind rebasing this onto the latest? It would go in the `netlify-cms-core` package. If not I'll find time eventually lol.

**Comment by growdigital** [comment]
@erquhart the very word “rebase” sends shivers down my spine!! I’ll have a `$ bash` at it, will let you know how I get on.

**Comment by erquhart** [comment]
Might be easier to just open a new PR, not a ton of changes to move.

**Pull request closed without merging**
