### PR TITLE
dev: add GitHub detailed issue templates

### PR DESCRIPTION
**Pull request by tech4him1**
Update GitHub issue and PR templates. See details of how these work here: https://help.github.com/articles/about-issue-and-pull-request-templates/.

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 931e4c87469677dab712d4eecd1341a5237bb62f

https://deploy-preview-1591--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 9ca4b09094dedb03c9a0eb87a45e691758eccf8d

https://deploy-preview-1591--cms-demo.netlify.com

**Comment by tech4him1** [comment]
I did cheat and use GitHub's default templates a lot, but they are way better! 😁

**Comment by tech4him1** [comment]
@Benaiah @talves If I can get a couple other maintainer reviews, that would be great!

**Pull request merged**
