### PR TITLE
fix(backend-bitbucket): fix media library not loaded on BitBucket

### PR DESCRIPTION
**Pull request by erezrokah**
Fixes https://github.com/netlify/netlify-cms/issues/3058

### CODE REVIEW

**Comment by ymslavov** [comment]
@erezrokah what is the estimated release date of this change?

**Comment by erezrokah** [comment]
We'll need @erquhart for that. We've had a few regressions in the latest release, so probably soon

**Comment by fabianrios** [comment]
is it integrated into netlify-cms-app ?

**Comment by erezrokah** [comment]
Yes in `netlify-cms-app@2.11.1`

**Pull request merged**
