### PR TITLE
Add crgeary, contributor of SEO plugin

### PR DESCRIPTION
**Pull request by verythorough**
@crgeary made this really cool plugin which gives Yoast SEO analysis of a post directly within the editor preview: https://github.com/indigotree/netlify-cms-yoast-seo

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit bff272b6e0013934b28003e2cb1edeb95899885a

https://deploy-preview-1238--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit bff272b6e0013934b28003e2cb1edeb95899885a

https://deploy-preview-1238--netlify-cms-www.netlify.com

**Comment by tech4him1** [comment]
@verythorough We do need to come up with a way to post these on the website as well.

**Comment by verythorough** [comment]
@tech4him1 Yeah, absolutely. I'll make a note to add an issue for it later today.

**Comment by tech4him1** [comment]
@verythorough Actually, I think there already is one, unless you want something more specific/actionable: https://github.com/netlify/netlify-cms/issues/919.

**Comment by verythorough** [comment]
@tech4him1 Thanks, I thought I remembered something similar. I'll build on that one. I think I may also create a separate meta-issue for how we'd like to include all sorts of community content, like templates, examples, and tutorials.

**Pull request merged**
