### PR TITLE
Add ability to set custom options length for relation widget

### PR DESCRIPTION
**Pull request by zslabs**
**Summary**

Decided to take a swing at https://github.com/netlify/netlify-cms/issues/2519 which provides the ability to customize the amount of options that are presented to the user within the searchable select.

**Test plan**

1. Add `optionsLength` (with number value) to relation widget config. 
1. Should update number of results.

zoe_addie

### CODE REVIEW

**Comment by erquhart** [comment]
Thanks @zslabs! The PR is good, but I'm really trying to tamp down on adding an option for everything, and this is the first I've heard of this being a problem for anyone. Are you sure we can't solve this at the UX level, maybe through better communication that this is a type-to-filter search field? Or even a bump to the default level, say, 50?

**Comment by zslabs** [comment]
Appreciate the reply! So in my use-case this was around a field of tags; something that we have a larger list for, but wanted them pre-defined so there was no chance of misspellings or subtle variations. Unlike a field such as "Authors" for example, where the options are generally known and a search would make sense, we want to use this area for discoverability; to find options that may suit the needs of the content they weren't thinking about previously. 

I think bumping it up to 50 is a good first-step; but I see it potentially as a compounding issue based on the amount of options.

**Comment by erquhart** [comment]
Alright, that's fair. Would you mind adding this option to the relation widget docs? Good to merge after that.

**Comment by zslabs** [comment]
Awesome! Just added to the docs. Thanks again for chatting with me about this. 🚀

**Comment by chocobuckle** [comment]
@zslabs It would be much appreciated if you could possibly shed any light on issue [#2849](https://github.com/netlify/netlify-cms/issues/2849) :)

**Pull request merged**
