### PR TITLE
Upgrade to React 16

### LINKED ISSUE #664: Upgrade to React 16
React 16 was just released! This will be a running issue to keep track of our progress upgrading to it and the decisions we make.

Changelog: https://reactjs.org/blog/2017/09/26/react-v16.0.html

### PR DESCRIPTION
**Pull request by tech4him1**
**- Summary**

Upgrade to React 16 (and upgrade other React-related libs).

Closes #664.

**- Test plan**

TODO: All tests pass, and manual testing reveals no regressions.

**- Description for the changelog**

Upgrade React (and related deps) to v16.

**- A picture of a cute animal (not mandatory but encouraged)**
[
gary-bendig-288538
](https://unsplash.com/photos/6GMq7AGxNbE)

### CODE REVIEW

**Comment by tech4him1** [comment]
There is a small regression here: If someone creates a new entry, then (without making any changes), clicks the "Home" button, they are presented with two confirm dialogs, instead of just one.

**Comment by Benaiah** [comment]
@tech4him1 what are the effects of the breaking change you listed for `enzyme` in #664?

**Comment by tech4him1** [comment]
@Benaiah Enzyme was updated in d2a0477.

**Comment by tech4him1** [comment]
Out of the peer-dep warnings, these are the only React 16 ones that are actually for one of our deps, not sub-deps:
**@kadira/storybook@1.41.0** -- This can be done after merge, since it is just a dev dependency.
**react-toolbox@2.0.0-beta.12** -- This still works fine, they just haven't released the new version yet.
**slate@0.25.3, slate-react@0.1.10** -- A new version was released, but this one still works fine, so we can just wait on it.

**Pull request merged**
