### PR TITLE
Fix widget example code layout on Site

### PR DESCRIPTION
**Pull request by talves**
Fix layout of code in examples for widgets.

- Aligns code in valid YAML format
- Indents  code block to match the line item

### From:

image

### To:

image

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit b056535dc1af49ad8a351df614df581032099834

https://deploy-preview-1606--netlify-cms-www.netlify.com

**Comment by tech4him1** [comment]
☹️ This is an issue with Prettier vs Remark here: if I run Prettier it reverses every change you made here. Do you think it is worth just turning Prettier off for MD files, or trying to get a patch upstream to one of them?

**Comment by talves** [comment]
I am not sure this was 100% Prettier causing all the problems, but we **shouldn't** be using prettier on content files. We will never get it right no matter how hard we try. There are too many nuances and will just cause more problems than it is worth.

**Comment by tech4him1** [comment]
> We will never get it right no matter how hard we try.

Not sure I completely agree with that, but it's definitely not worth it right now. Removing.

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit b5a9afc93ba2434adb043ff93ea5a2c48c253dcf

https://deploy-preview-1606--cms-demo.netlify.com

**Comment by tech4him1** [comment]
I guess the reason I saw it as less of an issue is that you can just run Prettier when you're done. It's not forcing you to *write* the MD a certain way, it just changes it when you are done.

**Comment by tech4him1** [comment]
There were some other bugs Prettier was causing, so I created https://github.com/netlify/netlify-cms/pull/1612 to just revert all the Prettier changes on docs.

**Pull request merged**
