### PR TITLE
WIP: Gentle re-authentication modal/popup.

### LINKED ISSUE #569: Re-Auth Error Messages for GitHub
This is a bit of a bug report and feature request. 

When you get logged out of github there is no error message letting you know to log in. It would be nice if failed http requests triggered some sort of login dialog or notice.

### PR DESCRIPTION
**Pull request by tech4him1**
**- Summary**

We need to have a way to gently re-authenticate the user, especially for backends for which the OAuth token times out or is otherwise invalidated.

With this implementation, **we don't re-run the user's action at all,** we just re-authenticate on API failure. For example, if the user is saving a post and we get a 401, we re-authenticate the user, but then they have to click the "Save" button again. Do you guys think that is clear enough?

This is not currently implemented at all, but it is needed (will be used) by both #517 and #525.

~~#559 needs merged before this can be finished.~~ *Done*
~~We can also use the `Dialog` from #554 for this as well.~~ *Done*
~~This PR fixes #569.~~ *No longer applicable.*

**- Test plan**:

Current authentication works correctly.

**- Description for the changelog**

Add gentle re-auth modal for backends (not currently implemented).

**- A picture of a cute animal (not mandatory but encouraged)**
[](https://unsplash.com/photos/xgTMSz6kegE)

### CODE REVIEW

**Comment by tech4him1** [comment]
We can also use the `Dialog` from #554 for this as well.

**Comment by erquhart** [comment]
@tech4him1 thought this was WIP for some reason, will review next week. In the meantime, can you rebase?

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit bba13612e12ef0d2557920760b7ff83bdbc539ea

https://deploy-preview-560--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit bba13612e12ef0d2557920760b7ff83bdbc539ea

https://deploy-preview-560--cms-demo.netlify.com

**Comment by tech4him1** [comment]
@erquhart @neutyp @ziburski I'd like some input on the design, I'm not sure exactly what the sizing should be. Should it adapt to the different sizes of the backend logins? Or just be a standard size (maybe like the media library).
localhost_8080_

**Comment by tech4him1** [comment]
Spoke too soon on reviewing this, looks like it is broken with Identity on 1.0.

**Comment by erquhart** [comment]
@tech4him1 I thought I remembered there being complications with this, but not seeing any mention in the PR. Can you confirm one last time whether this is ready for review?

**Comment by tech4him1** [comment]
@erquhart This was originally intended for GitHub, because it seemed that the token was sometimes being timing out if you logged out of GitHub.com in a different tab. That couldn't be consistently reproduced, however (and shouldn't logically be happening), so the PR was put on hold. We did decide to leave it open for use in any other new backend that may have token timeouts, such as BitBucket (and likely GitLab).

**Comment by erquhart** [comment]
Awesome, thanks @tech4him1

**Pull request closed without merging**
