### PR TITLE
feat(editor): add field option `when` to be able to show fields conditionally

### PR DESCRIPTION
**Pull request by LoicMahieu**
### Summary

**Add field option `when` to be able to show fields conditionally.**

It could be useful to conditionally show/hide some fields depending on the data. This PR allows to specify a new option `when` which could be:
- string: use of [`conscript.js`](https://github.com/lamansky/conscript.js) for simple language for writing potentially-complex sets of conditions.
- function: write own condition directly in javascript.

### Test plan

WIP...

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 56a10581d1664eb9887be64241635d06593bcc9b

https://deploy-preview-1894--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 3b182b1246d1755fa451a5617a706b8785b805b6

https://deploy-preview-1894--cms-demo.netlify.com

**Comment by LoicMahieu** [comment]
I found `conscript` by change. It seems pretty new and so not battle tested. I think it is promising.

Anyway, in my use-case, I don't use this syntax but only the function style. In fact, I configure only by JS, see #1866

**Comment by erquhart** [comment]
Yeah - I'm not saying it isn't functional, but I'd like to avoid bringing outside specs into our API. For example, Immutable.js is a part of our API right now, meaning folks need to understand how that library works to do any customization in the CMS, and that's a decision I regret (planning to remove it in an upcoming major release).

Totally agree on the goal of this PR, we just need to find a different approach.

**Comment by erquhart** [comment]
Closing as stale due to lack of activity and/or interest. Please comment if you feel this should be reopened.

**Pull request closed without merging**
