### PR TITLE
Update GitLab OAuth documentation

### PR DESCRIPTION
**Pull request by dee-see**
**Summary**

Hello team! I work at GitLab and a user [opened an issue](https://gitlab.com/gitlab-org/gitlab/-/issues/299240) following some integration trouble with netlify-cms so I'm opening this PR to update the documentation.

The OAuth implicit flow doesn't work anymore when the OAuth application is configured as "confidential". I've also updated some terms that have changed in the documentation (web application flow -> authorization code flow)

**Test plan**

Documentation change only

**A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

**Review by erezrokah — COMMENTED** [review]
Thanks @dee-see, this looks great :)
Should we clarify the `implicit` is not recommended?

**Comment by dee-see** [comment]
That would be good yes, for a client-side Auth scenario it's still possible to use the Authorization code with PKCE flow but I have 0 familiarity with `netlify-cms` and I'm not quite sure how to write the docs for that part unfortunately.

**Comment by erezrokah** [comment]
> That would be good yes, for a client-side Auth scenario it's still possible to use the [Authorization code with PKCE flow](https://docs.gitlab.com/ce/api/oauth2.html#authorization-code-with-proof-key-for-code-exchange-pkce) but I have 0 familiarity with `netlify-cms` and I'm not quite sure how to write the docs for that part unfortunately.

We only support implicit and Web App Flow at the moment...

How does https://github.com/netlify/netlify-cms/pull/4878/commits/b9d9647e5ae6c861ee35183588ffc5c42c5bd887 look?

**Comment by dee-see** [comment]
Oh that makes it easier then :D

The link you used explains why the integration stopped working for `Confidential` applications but not necessarily why the implicit grant in general is not recommended. I updated the message with new links, thanks!

**Comment by vnourdin** [comment]
Thanks for your changes, this is clearer!
Nevertheless, if Implicit grant is deprecated, I don't see how to do without Netlify, for a site hosted on GitLab Pages for example.
Should I open a documentation issue about this ?

**Comment by erezrokah** [comment]
> Should I open a documentation issue about this ?

We could point to https://www.netlifycms.org/docs/external-oauth-clients/ as a way to do it

**Pull request merged**
