### PR TITLE
Add media_library.config.max_file_size option

### PR DESCRIPTION
**Pull request by mb21**
see #1322

seems to work, feedback welcome!

### CODE REVIEW

**Comment by erquhart** [comment]
Thanks for the quick turnaround! Just noticed you were talking about applying this validation to the media library - I was thinking the file and image widgets, as widgets already have a validation API. Will give this a proper look next week.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mb21** [comment]
Ah yes, that would make sense as well. Not sure if it's not already too late at that point (large file committed to git, or we don't have the `File` object any more where we can do `file.size`)?

**Comment by erezrokah** [comment]
@erquhart and I discussed the approach in this PR and while widgets have validation logic so it makes sense to put image validation in the relevant widget, since the media library can be used outside the context of the editor we’ll merge this as a beta feature and revisit once we get more feedback.
I'll try to go over it today/tomorrow.

**Comment by mb21** [comment]
@erezrokah cool! I've added a documentation commit.. feel free to change it..

**Pull request merged**
