### PR TITLE
feat(editor-components): add title to image component

### LINKED ISSUE #1775: Add possibility to include image title in editor
**Is your feature request related to a problem? Please describe.**
Currently, there's no option to take advantage of markdowns image title feature. It is especially important, while preparing the website content for SEO optimization.

**Describe the solution you'd like**
Improve editor-component-image to parse image title syntax (i.e. `alt`) and allow user to edit its content in the WYSWIG editor.

**Describe alternatives you've considered**
I've recently tried to make a custom widget which supports title attribute, but the regex pattern used in interal implementation is more generic and overwrites it, thus it's not possible to fullfill the request without the edition of cms' source code.

### PR DESCRIPTION
**Pull request by zvinless**
Adds a "title" attribute to the built-in image editor component. There might be more robust ways to handle the regex or escaping though?

closes #1775

**Test plan**
Can someone point me to a relevant file to test this? I also noticed the docs are still in progress for this package, but is there somewhere I should add documentation?

title
title2

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 4024fc6bdf4401bcd852519762ef461c9b46f255

https://deploy-preview-1862--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 4024fc6bdf4401bcd852519762ef461c9b46f255

https://deploy-preview-1862--cms-demo.netlify.com

**Comment by erquhart** [comment]
Looks great, thanks for this!

We're pushing to get our testing up - to add tests for the `netlify-cms-editor-component-image` package, just add a `__tests__` directory inside of it's `src` and add any test files there. Check out the `path` spec in the `netlify-cms-lib-util` package for example: https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-lib-util/src/__tests__/path.spec.js

We use Jest for testing, you can run `yarn jest` from the root to run the suite.

For docs we're currently just adding them to the website via [content files](https://github.com/netlify/netlify-cms/tree/master/website/content/docs). Creating an actual readme for that package would be awesome if you're up for it, but not a requirement for this PR.

Also just noticing our editor components aren't documented anywhere at all 🤦‍♂️, need a docs section for that at some point.

**Comment by zvinless** [comment]
@erquhart thanks for the guidance! I went ahead and added tests.

I found documentation about [registerEditorComponent](https://github.com/netlify/netlify-cms/blob/master/website/content/docs/custom-widgets.md#registereditorcomponent), but not about the default Image component in particular. Are you thinking there should be a section specifically for default components (I think this is the only one)?

**Comment by erquhart** [comment]
Yeah we need to add docs, but I won't require it for this PR. Looks great, thanks!

**Comment by verythorough** [comment]
As with all the docs, there are roughly three types of uses to cover: **editing** (using the Natlify CMS UI), **configuring** (mostly entering settings into config.yml and optionally styling the preview pane), and **extending** (creating new plugins/widgets/etc. or making core feature contributions like this one).

For content editing, @ademuro is working on a user guide now for https://github.com/netlify/netlify-cms/issues/1340. The guide includes user instructions for the image component.

It's not in the configuration areas of the docs because there aren't really any config options.

As the "extending" sections of the docs are starting to expand, some information on the actual code behind the image component could be helpful!

**Pull request merged**
