### PR TITLE
Inlined React Split Pane Usage

### LINKED ISSUE #5376: netlify-cms-app fails to install with react 17 as version 6 of react-aria-menubutton in incompatible with react 17
**Describe the bug**

When installing netlify-cms-app with react 17 the install fails with the following error:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"17.0.2" from react-dom@17.0.2
npm ERR!   node_modules/react-dom
npm ERR!     react-dom@"^17.0.2" from the root project
npm ERR!     peer react-dom@"^16.8.4 || ^17.0.0" from netlify-cms-app@2.15.6
npm ERR!     node_modules/netlify-cms-app
npm ERR!       netlify-cms-app@"*" from the root project
npm ERR!     8 more (netlify-cms-widget-date, ...)
npm ERR!   react@"^17.0.2" from the root project
npm ERR!   38 more (netlify-cms-app, @emotion/core, @emotion/styled, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"0.14.x || ^15.0.0 || ^16.0.0" from react-aria-menubutton@6.3.0
npm ERR! node_modules/netlify-cms-ui-default/node_modules/react-aria-menubutton
npm ERR!   react-aria-menubutton@"^6.0.0" from netlify-cms-ui-default@2.13.1
npm ERR!   node_modules/netlify-cms-ui-default
npm ERR!     netlify-cms-ui-default@"^2.13.1" from netlify-cms-app@2.15.6
npm ERR!     node_modules/netlify-cms-app
npm ERR!       netlify-cms-app@"*" from the root project
npm ERR!     23 more (netlify-cms-backend-azure, ...)
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
 ```

It seems like `react-aria-menubutton` in `netlify-cms-ui-default` needs to be upgraded to version 7.0.1 see: https://github.com/davidtheclark/react-aria-menubutton/issues/140

**To Reproduce**

Run `npm init -y && npm i react react-dom &&  npm i netlify-cms-app` in an empty directory.
See Error

**Expected behavior**

`netlify-cms-app` installs without having to use `--legacy-peer-deps`

**Screenshots**

NA

**Applicable Versions:**

 - Netlify CMS version: 2.15.6
 - Git provider: NA
 - OS: Arch Linux
 - Browser version NA
 - NPM version: 7.12.1
 - Node.JS version: 16.1.0

**CMS configuration**

NA

**Additional context**

Seems like a dependency that didn't get updated while fixing
https://github.com/netlify/netlify-cms/issues/5111

### PR DESCRIPTION
**Pull request by LuisOsta**
**Summary**
Fixes #5376. I've inlined the usage of SplitPane and removed all references to the library in the codebase.
As described in the issue the library that provided that component `react-split-pane` is no longer being maintained and causes React 17 compatibility issues.

Both to the compatability issues and the library being unmaintained it was deemed that the ideal path was to inline the usage of the components. Thank you to @jeremyGrieshop for modernizing the library in his own implementation and hence making it a painless migration.

There is still one reference to the old dependency in the yarn.lock under the website folder. But I'm unsure of how y'all want to go about removing that since it seems to come from it using the published version of netlify core:  `netlify-cms-core@^2.54.3`

**Test plan**

- Ran the full suite of tests locally via the `test:all` script

**Checklist**

Please add a `x` inside each checkbox:

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x] Code is formatted via running `yarn format`.
- [x] Tests are passing via running `yarn test`.
- [ ] The status checks are successful (continuous integration). Those can be seen below.

**A picture of a cute animal (not mandatory but encouraged)**
As requested
Cat

### CODE REVIEW

**Comment by LuisOsta** [comment]
@erezrokah Can you approve the CI workflows?

**Review by erezrokah — CHANGES_REQUESTED** [review]
Hi @LuisOsta and thank you for this.

We've had issues in the past with using hooks in the CMS due to https://github.com/facebook/react/issues/13991.

The CMS has its own version of React (as it's a self contained react app), so if someone has another version running on their site, it all goes 💥 

How about we descope this PR to using the known to be working version of `react-split-pne` from https://github.com/tomkp/react-split-pane, and have the hooks upgrade in another PR.
It will help us avoid the rabbit 🕳️ of supporting hooks in the CMS.

**Comment by erezrokah** [comment]
Another (probably better) option is to use https://github.com/selenehyun/react-split-pane, as it's forked from the original repo.

It's published as `react-split-pane-r17`, see https://github.com/tomkp/react-split-pane/pull/681

**Comment by erezrokah** [comment]
Closing this PR as stale. Please comment if still relevant.

Going forward I'd recommend inlining split pane as is without the hooks upgrade.

**Pull request closed without merging**
