### PR TITLE
Fixes #1486

### LINKED ISSUE #1486: Use HTML elements for accessibility #a11y
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

Many HTML elements used in the app are `<div>`s rather than semantically correct and accessible HTML elements (such as `<main>`, `<aside>`, `<li>` etc.). This means accessibilty software such as screen readers can't navigate the screen as effectively.

This is a refinement on https://github.com/netlify/netlify-cms/issues/1333 Accessiblity #a11y issues 

**- If the current behavior is a bug, please provide the steps to reproduce.**

Use a screen reader with the app. Alternatively, view source and see that eg the main content area `nc-collectionPage-main` uses a `<div>` rather than `<main>`.

**- What is the expected behavior?**

Use semantically correct HTML elements where possible 🙂

**- Please mention your versions where applicable.**

Netlify CMS version: 2.0.0-dev-dev
Browser version: 61.0

Node.JS version: v8.9.1
Operating System: MacOS 10.13.5

**- Please link or paste your `config.yml` below if applicable.**

### PR DESCRIPTION
**Pull request by growdigital**
**- Summary**

Fixes #1486 

**- Test plan**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 7b5b5f9bfe31b29eca78520c030656b115afe1a4

https://deploy-preview-1487--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 7b5b5f9bfe31b29eca78520c030656b115afe1a4

https://deploy-preview-1487--cms-demo.netlify.com

**Comment by growdigital** [comment]
Creating new Pull Request, as I haven't created separate branches for separate issues!

**Comment by verythorough** [comment]
Been there, done that! 😛

**Comment by growdigital** [comment]
The plus side is that the new PR has a photo of a lovely pony in a wood 🙂

**Pull request closed without merging**
