### PR TITLE
Add node module type include of the CMS

### PR DESCRIPTION
**Pull request by richtera**
Add new npm module called "netlify-cms-node" which externalizes all peer imports and requires the rest of the modules as peers. Had to change netlify-cms-core to have peer dependencies and lerna.json to change the build sequence.
This is to resolve issue #1715.

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit b20e85afe1796c3662544f187be3d30a3bb2ccfd

https://deploy-preview-1718--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit b20e85afe1796c3662544f187be3d30a3bb2ccfd

https://deploy-preview-1718--cms-demo.netlify.com

**Comment by richtera** [comment]
Fixed peer dependency problem causing EditorialWorkflowError not to match across modules. All will now have a peer dependency to netlify-cms-lib-util instead of a dependency.

**Comment by erquhart** [comment]
This means the consuming project is responsible for installing their own copy of every peer dependency, which isn't the approach we want to take. Too cumbersome and great potential for installing incompatible versions.

Netlify CMS as a whole should always include it's own dependencies up to and including React. We just need to share those dependencies with Netlify CMS extensions. Closing, but feel free to comment further.

**Pull request closed without merging**
