### PR TITLE
Update Docs: Account “external-oauth-clients”

### PR DESCRIPTION
**Pull request by deepbass**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by deepbass** [comment]
Hi, apologies if this doesn't fit the required structure. I was experimenting with adding my Azure-based External OAuth Client and didn't clock that this would send in a PR!

**Review by erezrokah — CHANGES_REQUESTED** [review]
Hi @deepbass, very cool to have an Azure OAuth client.
One question though - will users need to update the `base_url` address after deploy their function here. I'm referring to the following line in `config.yml`
https://github.com/deepbass/serverless-cms-azure/blob/ca9b3d22c667882dbd0e33e315638c15d91a2a43/static/admin/config.yml#L5

If so, can we clarify that in the README? Otherwise I believe users will authenticate with your GitHub OAuth app.

**Comment by deepbass** [comment]
Hi @erezrokah, thanks for taking a look! I've put in a change to highlight that in my readme, the diff is highlighted here: https://github.com/deepbass/serverless-cms-azure/pull/3/files

**Comment by erezrokah** [comment]
> Hi @erezrokah, thanks for taking a look! I've put in a change to highlight that in my readme, the diff is highlighted here: https://github.com/deepbass/serverless-cms-azure/pull/3/files

Nice touch with the repo comment too :)

**Review by erezrokah — APPROVED** [review]

**Pull request merged**
