### PR TITLE
Hide create new button for single files.

### LINKED ISSUE #1183: "Publish and create new" on file collection
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
"Publish and create new" on a file collection is present in the publish dropdown menu, "create: false" is set in the config file even though a single file should always have this setting).

**- If the current behavior is a bug, please provide the steps to reproduce.**
config example:
```
- name: "info"
        label: "Info"
        file: "_data/info.yml"
        delete: false
        create: false
        fields:
          - {label: "Title", name: "title", widget: "string", required: false }
          - {label: "Name", name: "name", widget: "string", required: false }
          - {label: "Street", name: "street", widget: "string", required: false }
          - {label: "Postal", name: "postal", widget: "string", required: false }
          - {label: "Locality", name: "locality", widget: "string", required: false }
          - {label: "Phone", name: "tel", widget: "string", required: false }
          - {label: "Mobile", name: "mobile", widget: "string", required: false }
          - {label: "Email", name: "email", widget: "string", required: false }
```
**- What is the expected behavior?**
"Publish and create new" shouldn't be in the publish dropdown for single files... 

**- Please mention your CMS, node.js, and operating system version.**
CMS 1.3.5 / OSX 10.13.3

### PR DESCRIPTION
**Pull request by tech4him1**
**- Summary**

Hides the "Publish and Create New" button for single-file collections. Uses the code from the "Quick Add" button.

Fix #1183.

**- Test plan**

Manually tested with both simple and editorial workflows.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by tech4him1** [comment]
@erquhart Do we need to be checking for this somewhere farther down than the UI, so that even if a "create new" button was left, it wouldn't work?

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 7f516f78ef49ed55878db9922c47ea07561b8b23

https://deploy-preview-1200--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 7f516f78ef49ed55878db9922c47ea07561b8b23

https://deploy-preview-1200--cms-demo.netlify.com

**Comment by erquhart** [comment]
@tech4him1 I agree it should be more centralized, but this is fine for now.

**Pull request merged**
