### PR TITLE
improvement: use clear error if Git Gateway off

### PR DESCRIPTION
**Pull request by tech4him1**
**Summary**

If Git Gateway is disabled, the current error is *very* unclear: `Unexpected token < in JSON at position 0`. This PR changes to Git Gateway initial settings check code to validate that the request is OK (200 code) and is actually JSON. If not, we output a clear error message.

**Test plan**

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by tech4him1** [comment]
@tomrutgers Would you mind reviewing the error messages here?

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 4894e93eae75bde8fbb7392a2bd1905405ad9f17

https://deploy-preview-1695--netlify-cms-www.netlify.com

**Comment by erquhart** [comment]
@tech4him1 linting error:

```shell
10:34:03 PM: /opt/build/repo/packages/netlify-cms-backend-git-gateway/src/implementation.js
10:34:03 PM:    96:23  error  'APIError' is not defined  no-undef
10:34:03 PM:   106:23  error  'APIError' is not defined  no-undef
10:34:03 PM: ✖ 2 problems (2 errors, 0 warnings)
```

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 6b10642633bf35c2fd5f30d981f93c207d3bc05b

https://deploy-preview-1695--cms-demo.netlify.com

**Comment by erquhart** [comment]
Good change @tech4him1. It also occurs to me that we're trusting backends to send valid json instead of testing it, but we can make that improvement outside of this.

**Pull request merged**
