### PR TITLE
Update examples.md to include one more example

### PR DESCRIPTION
**Pull request by ragasirtahk**
I have created a blog on Netlify CMS and created a guide for it. Including links for it.

**- Summary**

**- Test plan**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit e5644bf18a1586f1166112805fb347c1bb7ff93f

https://deploy-preview-1048--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit e5644bf18a1586f1166112805fb347c1bb7ff93f

https://deploy-preview-1048--cms-demo.netlify.com

**Comment by ragasirtahk** [comment]
Should I add myself as a contributor?
I wish to contribute to the docs.

**Comment by ragasirtahk** [comment]
I did not add myself as contributor when I submitted this pull request. Is it still possible to be done. Do guide me.

**Comment by erquhart** [comment]
@ragasirtahk absolutely, good catch! Steps to add yourself are here, you can open a new pull request for it: https://github.com/netlify/netlify-cms/blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor

**Comment by ragasirtahk** [comment]
I have another thing to point out. The first list of links i.e. of "This Developing Journey" has a link that returns a 404 error. The blog-post link returns a 404 error.

**Comment by erquhart** [comment]
Yeah I noticed that too, there's another pr open to address.

**Comment by ragasirtahk** [comment]
Can you please give me the link of that PR?

**Comment by erquhart** [comment]
This one here: https://github.com/netlify/netlify-cms/pull/1049

**Pull request merged**
