### PR TITLE
[WIP] Uploadcare media library

### PR DESCRIPTION
**Pull request by nd0ut**
Hello! That is our work with @owenhoskins. We made an update to [Uploadcare media library](https://github.com/netlify/netlify-cms/pull/1602) which allow users to select and search files that they have uploaded earlier. (ref https://github.com/netlify/netlify-cms/issues/1794)

The file index is stored in the user's repository as simple json file named `uploadcare-index.json` with array of `fileInfo` objects. 

I think it's not ready for production use yet, so I'll make a checklist of what we need to do before it can be merged.

Code checklist:
- [x] rewrite store reducer extending
- [x] fix imports from core (pass actions and store through `init` method)
- [ ] set-up demo page
- [ ] check tests
- [ ] formatting
- [ ] update cloudinary plugin according to updated external library api (nothin extraordinary, I just passed store and bound media library actions)

Functionality checklist:

- [x] ability to remove files
- [x] batch adding of files
- [x] batch remove
- [x] do not add files if it is already in the index
- [ ] add ability to set default url operations for all images
- [ ] add ability to specify url operations for the image in editor
- [ ] handle private uploads
- [ ] pretty UI

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 865929bc9b9893a3c12df8780138aa472dfbd6a8

https://deploy-preview-1825--netlify-cms-www.netlify.com

**Comment by nd0ut** [comment]
Because we can't currently merge this PR in, we're going to extract the Media Library functionality as a separate extension for the our widget and make Netlify integration based on it.

**Comment by erquhart** [comment]
Can't wait for that!!

**Comment by kalwalt** [comment]
Hi @nd0ut i would to know if you have an idea when these features will be available. Thanks!

**Comment by nd0ut** [comment]
@kalwalt 
It's hard to say, but the Media Library definitely won't be there by March-April, right now we have different priorities.

**Comment by kalwalt** [comment]
@nd0ut thank you for the answer, i can wait no worries or pressure, at all!

**Comment by jericopingul** [comment]
@nd0ut is there any new information about the release of these features? Thanks

**Comment by erquhart** [comment]
@jericopingul check out the Uploadcare integration: https://www.netlifycms.org/docs/uploadcare/

**Pull request closed without merging**
