### PR TITLE
feat: duplicate published entry

### LINKED ISSUE #981: Duplicate an existing entry
**Feature request**

User story: When I am an editor creating new content in the CMS, I want to be able to duplicate an existing document, So I can reduce the number of redundant fields to fill out when creating new documents with similar information.

### PR DESCRIPTION
**Pull request by barthc**
**Summary**
Closes #981.
So basically added a new dropdown item `Publish and duplicate`  that brings the user to  create a new collection page prefilled with values from previously published entry. The user can make further changes before publishing the new duplicate entry.

Before:
before-dup

After:
after-dup

### CODE REVIEW

**Comment by erquhart** [comment]
Thanks for this @barthc! What do you think about duplicating when you're not at publish time, would it be simple enough to add a duplicate function that doesn't require publishing?

**Comment by barthc** [comment]
> What do you think about duplicating when you're not at publish time, would it be simple enough to add a duplicate function that doesn't require publishing?

Ok let's move the duplicating away from publishing time. I will update the PR shortly.

**Comment by barthc** [comment]
Moved the duplicate item.

workflow:
new-after-dup

Non workflow:
new-after-non-workflow

**Comment by erquhart** [comment]
Nice! Ideally it would be outside of that dropdown, but maybe its best to just do this for now as that entire toolbar needs to be reworked at some point anyway.

**Comment by erquhart** [comment]
Just tested the demo and it works great! Since we're putting it in the publish dropdown, would you mind re-adding the Publish and Duplicate button as well? You were right on with that, just wanted to also allow duplication when not publishing.

**Comment by barthc** [comment]
> Since we're putting it in the publish dropdown, would you mind re-adding the Publish and Duplicate button as well?

Ok sure.

**Comment by erquhart** [comment]
Thanks @barthc! A lot of folks are going to be happy to see this!

**Comment by mtully** [comment]
Thank you @barthc!

**Comment by miguelt1** [comment]
Please put the option to duplicate without publishing it

**Comment by toxsick** [comment]
Is there any way to disable the duplicate feature? In my case this breaks things since I have hidden fields that I don't want to have duplicated.

**Pull request merged**
