### PR TITLE
feat: add setting locale in frontmatter

### LINKED ISSUE #5969: Allow setting locale in frontmatter
**Is your feature request related to a problem? Please describe.**
I am using astro's dynamic routing to build up my urls, and it would be really nice if I could add a hidden `locale` field to my collection so that it appears in the frontmatter.  As it stands, it seems the only way to determine a file's locale is from the path/filename, unless I'm missing another option.

**Describe the solution you'd like**
Ideally, this would be as easy as adding a field like `{ name: "locale", label: "Locale", widget: "hidden", default: "{{locale}}", i18n: true},`

**Describe alternatives you've considered**
I tried to create a `preSave` handler, but it seems to only run once per entry, and expects `data` to be returned, not the i18n map which contains the data for the localized versions.

### PR DESCRIPTION
**Pull request by imskr**
Closes #5969 

**Summary**

- Add setting locale in frontmatter

**Test plan**

**Checklist**

Please add a `x` inside each checkbox:

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x] Code is formatted via running `yarn format`.
- [x] Tests are passing via running `yarn test`.
- [ ] The status checks are successful (continuous integration). Those can be seen below.

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by imskr** [comment]
@erezrokah 1 test is failing!

**Review by erezrokah — CHANGES_REQUESTED** [review]
Hi @imskr, I believe the feature request in the issue is to be able to set the default value of a hidden widget to the current locale of the entry.

Can you explain how the change in this PR accomplish that?

I don't see any changes to the CMS codebase, other than configuration files.
FYI. default i18n values are injected here:
https://github.com/netlify/netlify-cms/blob/efd81ac48e50d9122833d5b8e91bea63793ef8fb/packages/netlify-cms-core/src/actions/entries.ts#L833

**Comment by imskr** [comment]
@erezrokah Oh i misunderstood the issue. I will make the changes. thanks :)

**Comment by erezrokah** [comment]
Thanks @imskr, going to close this until we get the implementation up to speed.
Please feel free to open a new PR or comment on this one so I can re-open it, if relevant.

**Pull request closed without merging**
