### PR TITLE
Migrate ListControl from react-sortable to react-sortable-hoc

### LINKED ISSUE #431: Use drag handles for list control drag/drop
**- Do you want to request a *feature* or report a *bug*?**

bug

**- What is the current behavior?**

Each object in a list control can be dragged from any point. When attempting to select text inside of a list control, you'll often drag the entire object of controls instead.

**- If the current behavior is a bug, please provide the steps to reproduce.**

* Open the editor for a CMS entry that utilizes the list widget (list widget must contain a text field
* Hit the "+ new" button in the list widget to create a new list item
* Enter text in a text field for the newly created item
* Attempt to select entered text using a mouse or touchpad

**- What is the expected behavior?**

* Text should be selected without activating drag mode on the list item

**- Requirements**
* Limit drag mode activation to a drag handle area (a handle is already depicted at the top of each list item in the UI, but it's just styling).
* When a list item is collapsed, the entire item should still be treated as a drag handle.

### PR DESCRIPTION
**Pull request by Benaiah**
**- Summary**

Migrates ListControl from `react-sortable` to `react-sortable-hoc` and enables drag handles. Closes #431.

(this may be closed in favor of a PR using https://github.com/atlassian/react-beautiful-dnd)

**- Test plan**

Manually tested, including nested lists.

**- Description for the changelog**

Migrate ListControl from react-sortable to react-sortable-hoc

**- A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

**Comment by Benaiah** [comment]
@erquhart sounds good, will do!

**Comment by erquhart** [comment]
Found a style regression, probably due to rebasing over the CSS migration:

screen shot 2017-10-23 at 12 08 25 pm

Whole bar should appear gray and seamless.

**Comment by erquhart** [comment]
Never mind, looks like that's on master. Fixing.

**Comment by Benaiah** [comment]
@erquhart thanks for pushing that fix! That commit looks good to me.

**Pull request merged**
