### PR TITLE
feat: pass strikethrough markdown for hint message on field

### LINKED ISSUE #5717: Support strikethrough markdown in widget hint text
**Is your feature request related to a problem? Please describe.**
There is markdown support in field hints for inline features like **bold**, _italic_, and links, but not strikethroughs. Niche use case but should be easy to do and fits in with the other features.

Example:
I'm using the hint to give the editors instructions on how to format an external link, showing the whole context and which parts to remove:
`https://www.linkedin.com/pulse/complex-world-early-interventions~~?trk=public_profile_article_view~~`

**Describe the solution you'd like**
Support adding Markdown strikethroughs `~~delete me~~`

**Additional context**
#5559 closed with #5584
@erezrokah gave this code as reference:
https://github.com/netlify/netlify-cms/blob/610421ea6722276e37fe3c6123386d20fbbac1cf/packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControl.js#L333

### PR DESCRIPTION
**Pull request by JonasMatos0**
**Summary**

This adds the option to include strikethrough HTML in the hint message on a field. Closes #5717
The issue creator requested support for Strikethrough Markdown

**Test plan**
Please guide me to the testing details if any for this modification. Thanks in advance.

**Checklist**

Please add a `x` inside each checkbox:

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x] Code is formatted via running `yarn format`.
- [x] Tests are passing via running `yarn test`.
- [x] The status checks are successful (continuous integration). Those can be seen below.

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by erezrokah — CHANGES_REQUESTED** [review]
Hi @sidilabs and thanks for the PR.

Based on https://github.com/remarkjs/react-markdown/tree/6.0.3#use we'll need to add the `remark-gfm` plugin to get `strikethrough` support.

Can you confirm if that's the case?

**Comment by JonasMatos0** [comment]
Hey, @erezrokah, updated dependencies, please re-review. Thanks in advance!

**Comment by erezrokah** [comment]
Hi @JonasMatos0, our CI is failing as a result of the last change (both the build and tests are failing).

**Comment by JonasMatos0** [comment]
Hey, @erezrokah . I've been facing lots of dependency issues related to updating this package.
Is there an specific version for npm/node suggested?

**Comment by erezrokah** [comment]
Hi @JonasMatos0, we use [`yarn@1`](https://classic.yarnpkg.com/lang/en/) to manage dependencies, due to the monorepo + workspaces support.

**Comment by JonasMatos0** [comment]
Thank you, @erezrokah . I updated the dependency via yarn instead of direct update on the module via npm. Please re-review.

**Review by erezrokah — CHANGES_REQUESTED** [review]
Thanks @JonasMatos0, can we undo the changes to add `packages/netlify-cms-core/package-lock.json`

Also `remark-gfm` should be installed for `packages/netlify-cms-core/package.json` and not at the workspace (root) level

**Pull request closed without merging**
