### PR TITLE
feat(docs): add docs settings, fix group values, refactor post summaries, add weight sorting

### PR DESCRIPTION
**Pull request by silverwebb925**
Docs (bug fix | content | refactor): change separately hardcoded group values to settings collection and relational widget to fix value discrepancies, update group values and collection filter mapping values, refactor post "weights" as sortable subsection ordering and update to match current docs menu

### CODE REVIEW

**Comment by silverwebb925** [comment]
NOTE: This is my first pull-request (ever), so my apologies for any hiccups as I figure out this process. Such as... I could not figure out how to fix the Required PR Labels error even after querying for a guide. Links & references would be helpful. Happy to RTFM as long as I can find one.

For context, I'm a technical designer specializing in documentation and spec writing, and am currently upping my UX engineering skills.

I approached this PR as a “Phase 1” in an effort to overhaul the Docs. In Phase 2 I'd like to implement a better route to updating the section headings and post organization, and perhaps even update the frontend navigation (ie: it might be nice if the main section headings were links which displayed the "Overview" posts instead of static headings)

Overall I'm interested in helping to create an infrastructure more easily editable via Open Authoring, and generally make the entire Docs easier to maintain... pardon my candor, but the Docs are a bit of a mess at the moment. The individual pieces of content are pretty excellent, but the structure somewhat muddled on the frontend and hard to work with on the backend. I've noticed numerous little outdated discrepancies while trying to learning Netlify CMS, and making the Docs easier to maintain will directly translate to even better content.

Extended explanation of changes encompassed in this PR:

Section (group) names were hardcoded two separate places (site.yml & config.yml)… and had become mismatched with their options, which will result in improperly categorized posts.

Ensured inherent compatibility by adding a “settings” file collection which links to site.yml and replacing the static values in config.yml with a relational link.

Site.yml may still be updated manually, so no functionality is lost, but I hid the “Settings” collection for now because editing summary group names through the collection will not update the filter criteria hardcoded for each collection-mapped section. (ie: updating and adding sections still requires manually editing the config.yml file as far as the backend organization is concerned)

Ideally, we would use nested collections or a more robust sorting structure to handle the backend organization (vs filters & collection mapping), but any route forward will require additional coding beyond the scope of updating the mismatched group names. Also, I think there may be additional work required on nested collections before it can be fully adopted.

Thank you for reading through this (I'll work on brevity in future PR's)

**Comment by tomrutgers** [comment]
Don't let the failing tests throw you off. As your changes are documentation based I reckon they have very little to do with your work. The maintainers of this repo will review your changes and provide feedback, although it can take a couple of days.

**Comment by silverwebb925** [comment]
From [Contributing.md](https://github.com/netlify/netlify-cms/blob/master/CONTRIBUTING.md)
Items to address:
**3. If you've added code that should be tested, add tests.**
How do I know if it needs to be tested? I changed the website config.yml file with minor updates and linked a collection to the site.yml file... does that qualify?

**5. Run yarn test and ensure the test suite passes.**
`Test Suites: 3 failed, 2 skipped, 79 passed, 82 of 84 total`
`Tests:       24 failed, 650 skipped, 846 passed, 1520 total`
`Snapshots:   90 passed, 90 total`
The failed tests appear to be entirely related to the `xhr-mock` module not being found and because the rewind() function can only be called on the server.

**7. PR's should be rebased on master when opened, and again before merging.**
Checking out the linked BitBucket guide now...

Additionally: 
Is there a definitive guide for PR comments? I wasn't able to find one, and don't know how to properly PR Label this...
Thanks!

**Comment by erezrokah** [comment]
Thanks @silverwebb925, we recently had some work done on the docs in https://github.com/netlify/netlify-cms/pull/3766 as a part of https://github.com/netlify/netlify-cms/issues/3764
Also related https://github.com/netlify/netlify-cms/issues/1692.

If you could add your thoughts in https://github.com/netlify/netlify-cms/issues/3764 that would be great.

I agree the docs need some work and thank you for this initiative.

I'll have some time to review this beginning of next week.

**Comment by silverwebb925** [comment]
@erezrokah Thank you! #3764 is just the thread I was looking for. Will review all the links you provided and add my thoughts to #3764. Appreciate your quick response.

**Review by erezrokah — CHANGES_REQUESTED** [review]
@silverwebb925, the PR looks good to me and is a very good step forward.
Only request is to re-open it from a specific branch on your fork (and not the `master` branch).

As for nested collections - yes it's very new and may need some more work.
We have an experimental parent widget https://github.com/netlify-labs/netlify-cms-widget-parent which might make it easier to manage content (assuming you'd want complete control on site structure from the CMS, the widget lets you select a parent entry which if the site derives the menu based on directory structure could work pretty well - https://about.gitlab.com/handbook/ is a good example).

**Comment by silverwebb925** [comment]
Closing this PR in favor of a new PR from a different branch, as requested.
Please see #4280 
Thank you, @erezrokah.

**Pull request closed without merging**
