### PR TITLE
Documentation Update

### PR DESCRIPTION
**Pull request by jorgson**
**Summary**
According to https://content.nuxtjs.org/displaying the <nuxt-content> component will only work on Markdown files. Having json files will result in no output. Defaulting to Markdown files will result in correct rendered output.

### CODE REVIEW

**Review by erezrokah — CHANGES_REQUESTED** [review]
Looks like we are referring to using `<nuxt-content>` here:
https://www.netlifycms.org/docs/nuxt/#example-blog-post

Also, the rest of the doc is referencing the json format too

**Comment by jorgson** [comment]
> Looks like we are referring to using `<nuxt-content>` here:
> https://www.netlifycms.org/docs/nuxt/#example-blog-post
> 
> Also, the rest of the doc is referencing the json format too

Indeed the whole document is referencing json. I will recheck, the functionality and propbably update the doc to only use markdown files as long as `<nuxt-content>` does not support json.

**Comment by jorgson** [comment]
I redid the whole guide, as it turns out .json will not work with nuxt content. I updated the document to be functional. Also fixed a typo and prevented a vue error in the blog template example.

**Review by erezrokah — APPROVED** [review]
Thanks @jorgson for following up with these changes.
Added another commit with some minor typos fixes.

**Pull request merged**
