### PR TITLE
Consistant npm yarn

### PR DESCRIPTION
**Pull request by hasanavi**
**- Summary**
as we've agreed @erquhart , @tech4him1 - I've used npm all places instead of yarn.

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 603be4f135279e14a8a1f3cb779e9db37b0537cb

https://deploy-preview-1264--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 603be4f135279e14a8a1f3cb779e9db37b0537cb

https://deploy-preview-1264--netlify-cms-www.netlify.com

**Comment by erquhart** [comment]
Thanks @hasanavi!

@tech4him1 @Benaiah @talves speak up if you disagree, I'm not certain if directing folks to use yarn has been beneficial in terms of install times, or to what extent recent improvements in npm makes this moot.

Thoughts?

**Comment by Benaiah** [comment]
I was under the impression that we recommended `yarn` installation due to the fact that we keep a consistent `yarn.lock`. So far, we haven't kept the `package-lock.json` up-to-date as consistently (I actually didn't realize it had been added to the repo, as I've been using yarn the whole time). I'd personally prefer to keep recommending yarn, but I'm fine with either one, and npm is definitely a lower barrier to entry. What I would like to do is make sure that the `package-lock.json` and `yarn.lock` are always up-to-date and resolve to consistent versions - perhaps we can add a check to the CI system to ensure they're always updated together.

**Comment by verythorough** [comment]
I do agree that making the command consistent every where is absolutely a good idea.

From a documentation/new user standpoint, I think npm is better because yarn requires an additional install. If a contributor knows and prefers yarn, they're going to know how to substitute the commands, and we've got the yarn.lock so that they can do it consistently.

Even though many of us may prefer yarn, npm will still work, I think the more we can reduce the steps to entry, the better.

**Comment by talves** [comment]
I don't use npm any longer on Windows because it was so unstable for me in the past and yarn fixed it. I only use it in the rare cases I need it.
Not sure if all the old problems have been resolved, but am afraid to even go back.

**Comment by Benaiah** [comment]
@verythorough running yarn instead of npm (even when you don't have yarn installed) is as simple as `npx yarn` instead of `npm install` if you're using any recent version of Node (`5.2.0` and later).

**Comment by tech4him1** [comment]
> I'd personally prefer to keep recommending yarn, but I'm fine with either one, and npm is definitely a lower barrier to entry.

Completely agree.

> What I would like to do is make sure that the `package-lock.json` and `yarn.lock` are always up-to-date and resolve to consistent versions - perhaps we can add a check to the CI system to ensure they're always updated together.

@Benaiah I don't think we need to be maintaining lockfiles that we're not using -- if the locked versioning is causing problems, we need to know. That could just cause more confusion for new users.

**Comment by verythorough** [comment]
Yeah, it's true that maintaining two lockfiles is less than ideal, and we probably don't want to standardize on package-lock.json.

It's true that we could use `npx` to avoid the install step, though we'd then have to make sure people have the right Node version.

In the end I don't think it's a huge deal either way, as long as we're consistent, and give any added instructions that might be needed depending on what we choose.

**Comment by hasanavi** [comment]
With the recent npm 5 release - npm closes the gap with yarn. There's not much significant advantage of using yarn now, and npm 5 offers pretty much all extra features that yarn provides. Personally, I do still use yarn but as @Benaiah said, there's no point adding an extra step for a new user.

**Comment by ekoeryanto** [comment]
vote for npm

**Comment by hasanavi** [comment]
Any thought on the npm / yarn guys? Let's decide one and reflect the doc

**Comment by talves** [comment]
@erquhart @Benaiah @tech4him1 I have been looking at yarn workspaces and Lerna for the mono-repo and this is not on that path.

**Comment by Benaiah** [comment]
Thanks to everybody who added to this issue for your input! My thoughts on this issue now are this: I think we should officially move to `npm`. While I personally prefer `yarn`, there's already consistency issues with running `npm` tasks through `yarn`<sup>1</sup>, and `npm` definitely seems to be a lower barrier to entry for most. Keeping lockfiles in sync doesn't appear to be a good solution either, so I propose moving our current `yarn.lock` to a `package-lock.json`<sup>2</sup> and changing the docs to use `npm` consistently.

<sup>1</sup> Some of the `npm` tasks in our `package.json`, notably `start`, call `npm run` within the task, which causes `CTRL-C` to quit the `yarn` process while leaving the underlying `npm` process running, with no convenient way to stop it.

<sup>2</sup> I'd prefer not to create a new `package-lock.json` from scratch if possible, as that's capable of introducing lots of hard-to-find bugs all at once.

**Comment by tech4him1** [comment]
@talves Are you sure Lerna only works with Yarn? Their instructions use `npm`.

**Comment by ekoeryanto** [comment]
@talves, you are right. Lerna works with npm.
but my experience this week on lerna (latest) using `npm` even with `nohist` option, it ran very slow.
but lerna + yarn workspace it's fair for my intel core i5 and 12GB RAM

**Comment by erquhart** [comment]
The Lerna project does seem to be moving decisively toward npm: https://github.com/lerna/lerna/issues/1349#issuecomment-377036951

@talves can you take a look at that issue and comment on whether that changes things for you at all?

**Comment by talves** [comment]
I think it is a matter of time to see which becomes stable enough. Most issues point toward publish which I have not tested. If it is true that npm becomes more stable than yarn I am all for it.

**Comment by ekoeryanto** [comment]
@erquhart please don't wait lerna to be stable enough, there's nothing perfect.

**Comment by ekoeryanto** [comment]
What branch is the active development?

**Comment by erquhart** [comment]
Ah you mean development towards a mono repo - I don't believe there is one, but if there is, @talves would know.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tech4him1** [comment]
Closed by https://github.com/netlify/netlify-cms/pull/1523. Thanks for the input here, everybody!

**Pull request closed without merging**
