### PR TITLE
App bundle `netlify-cms-app`

### PR DESCRIPTION
**Pull request by talves**
**Summary**

This is the CMS with React as a peer dependency.

**Test plan**

Use the beta release in an external app with react and a widget built with hooks.

**A picture of a cute animal (not mandatory but encouraged)**
🐓🙈

### CODE REVIEW

**Comment by talves** [comment]
@erquhart So we just leave the changelog out and it will get created? Awesome.

**Comment by talves** [comment]
There is not really a devServer develop unless you change the index.html. 

@erquhart Do you want that completed prior to releasing this or leave it for when we are happy with it? I can release my test website for this as an example once we feel good about it.

**Comment by erquhart** [comment]
@ekoeryanto ☝️☝️

**Comment by ekoeryanto** [comment]
great to know this.

thanks @erquhart

**Pull request merged**
