### PR TITLE
feat: populate new entry from URL params

### LINKED ISSUE #3322: Pre-populate fields in the New Entry Forms using URL Parameters
I have a link on my page that says “Create New Page” which currently goes to `/admin/#/collections/pages/new` and shows a form.

I’d like to be able to change the link on my page to `/admin/#/collections/pages/new?title=A+prepopulated+title` and have the form fields use those default values from the search parameters I set.

### PR DESCRIPTION
**Pull request by erezrokah**
Fixes #3322

populate_from_url

Didn't want to leave it to the widgets to verify that the URL params values are safe to use, so added html escaping.

### CODE REVIEW

**Comment by barthc** [comment]
If both defaults are set, which one should take precedence? Looks the URL defaults will overwrite the config default. Go with config first?

**Comment by erezrokah** [comment]
> If both defaults are set, which one should take precedence? Looks the URL defaults will overwrite the config default. Go with config first?

URL params will go first, config defaults are static while URL ones are dynamic hence they go first. if you don't want the URL param to override the config default, just remove the param for that specific link (as if config always go first you won't be able to override them).

But @zachleat has a preference.

**Comment by erquhart** [comment]
Inputting values via URL is not far removed from manually typing them in - I don't think we need to distinguish too heavily between them, other than for security. A default value can be overwritten through the UI, so it makes sense that it can be overwritten through the query string. Maybe we release it as a beta feature and iterate on feedback (beta in case it becomes obvious that this shouldn't be default behavior).

**Comment by barthc** [comment]
> Not working with Date(time), Markdown, and Boolean fields, all of which are known to have issues with state, defaults or both. Do we care?

I think it should work for all widgets. Here is a sample for markdown https://deploy-preview-3343--cms-demo.netlify.com/#/collections/posts/new?body=some%20content

**Comment by erquhart** [comment]
Markdown fails when using formatting characters: https://deploy-preview-3343--cms-demo.netlify.com/#/collections/posts/new?body=#%20some%20content

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by barthc** [comment]
Encoding the character would work https://deploy-preview-3343--cms-demo.netlify.com/#/collections/posts/new?body=%23%20some%20content

**Comment by erquhart** [comment]
Hmm maybe we can require undecided strings and encode in the CMS

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by erezrokah** [comment]
Date seems to work. https://deploy-preview-3343--cms-demo.netlify.com/#/collections/posts/new?date=2020-01-01T08:46:01.200Z

I'll fix the boolean bug and update the docs per encoding requirement.

**Pull request merged**
