### PR TITLE
[pending webhook creation] add functions to send release note notifications

### PR DESCRIPTION
**Pull request by bdougie**
**- Summary**

Per the Issue I opened, #1036, this PR creates a Netlify function to send a tweet, sends a message, and open a new release note post on the cms site (this is premature since there is no blog on the cms page yet).  

**- Test plan**
TBD, I need to open this PR first to get a Lambda endpoint from Netlify. Once the build passes I can create a webhook in the cms repo and provide my Lambda endpoint.

The test project code is here if needed for reference:
https://github.com/bdougie/create-react-app-lambda/blob/master/src/lambda/releaseNotifier.js

screenshot 2018-02-02 11 08 42

**- Description for the changelog**

Release note notifier added to enable social notifications updates for the CMS changes.

**- A picture of a cute animal (not mandatory but encouraged)**

**TODO**
- [ ] Grab the Lambda Endpoint
- [ ] Create GitHub release note webhook
- [ ] Get @erquhart or @Benaiah to add the GITTER_TOKEN for the Netlify Bot to the netlifycms.org's site dashboard.

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 3dfe32fa893ade0637f197706a6175573150b252

https://deploy-preview-1071--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 3dfe32fa893ade0637f197706a6175573150b252

https://deploy-preview-1071--netlify-cms-www.netlify.com

**Comment by bdougie** [comment]
Update: Getting the functions feature to identify my functions is proving to be a challenge. Since the website folder is deploy from a nested location, it is preventing my function from being deployed. I don't think the function should be in the root directory of the CMS, but it is the only way to make this work. I am going to temporarily test a different set up for my function before I bail out of this completely.

**Comment by erquhart** [comment]
Closing as stale, but leaving issue open.

**Pull request closed without merging**
