### PR TITLE
i18n round 2

### PR DESCRIPTION
**Pull request by vencax**
Hi, this is continuation of https://github.com/netlify/netlify-cms/pull/403/. I have made another PR because the I was not sucessfull with rebase. This could be easier to merge IMHO.
Cheers, and happy New Year!

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit 4bea83011883b9ddd6d7d7c09fd1a0932881c3ae

https://deploy-preview-974--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit 4bea83011883b9ddd6d7d7c09fd1a0932881c3ae

https://deploy-preview-974--cms-demo.netlify.com

**Comment by vencax** [comment]
https://github.com/netlify/netlify-cms/pull/403#issuecomment-326753066 mentions "expose i18n to widget authors, so that they can provide an object of translation objects with the widget". IMHO this could be added later. The core needs to be i18n-ed IMHO asap.

**Comment by derevandal** [comment]
Hi, when I run `npm run extract --lang pt-br` on your PL, I got nothing.
The code stops on
```js
  if (file === enFile || file === 'index.js') {
    return
  }
``` 

@vencax could u tell me how I should extract strings?

**Comment by vencax** [comment]
@derevandal this was undone, thank for pointing at it. See the last commit for details. Cheers!

**Comment by derevandal** [comment]
@vencax your code didn't work here.
i'm using node v8.9.4.
I change your code to
```js
const LangParam = process.argv[2];
if (LangParam) {
  const filePath = path.join(i18nFolder, `${ LangParam }.json`);
  const translations = {};
  keys.map(i => translations[i.key] = i.key);
  writeTranslations(filePath, translations);
}
```
and it works.
see [doc](https://nodejs.org/docs/latest-v8.x/api/process.html#process_process_argv)

**Comment by derevandal** [comment]
@vencax could u tell me how do i change lang of cms by extracted lang?

**Comment by vencax** [comment]
@derevandal 
It works as it was. At least for me. Why it didn't work for you? HAve you run it --lang pt-br ??
And you can set the lang with putting into your config.yam:
lang = pt-br

**Comment by derevandal** [comment]
@vencax when i used `npm run extract --lang` didn't work, but it works with `node extract.js --lang pt-br`.
i'm going to test the cms with pt-br translation and i'll post a review.

**Comment by derevandal** [comment]
why don't u use `languageCode` instead of `lang` if `config.yaml` already had `languageCode`?
and i extract pt-br lang, add `lang: "pt-br"` in config.yaml, transtale some parts and I didn't found tranlated entries. could u help me?

pt-br.json
```
  "Draft": "Draft",
  "New Post": "Nova Publicação",
```

**Comment by erquhart** [comment]
@derevandal did you ever get this working?

@vencax I do want to get this in, just wanted at least one more person to review, especially someone that has a translation use case.

That said, I think the only real blockers are:

* the issue outlined by @derevandal 
* the string keys are the full current english text of the strings they replace rather than just being short, camel cased descriptors.

This change has a big impact on the codebase, as the translation function is in almost every UI file, so I want to make sure it's maintainable. Thanks again for your work on this!

**Comment by derevandal** [comment]
@erquhart nope. nor was I able to extract or use the extracted file manually.

**Comment by erquhart** [comment]
Closing as stale.

**Pull request closed without merging**
