### PR TITLE
The play button was causing problem in edge. Replacing it with css triangle

### PR DESCRIPTION
**Pull request by eduplessis**
…iangle

**A picture of a cute animal (not mandatory but encouraged)**
capybara-wallpapers 1

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 31d300db4ba1fdd5d3d6fa5beadca53b32d8dd19

https://deploy-preview-1640--netlify-cms-www.netlify.com

**Comment by erquhart** [comment]
I'd rather see us find another way - the current icon looks nicer, css triangle is a pretty rough approach. Can you describe the problem(s) you're seeing with the current icon in Edge?

**Comment by eduplessis** [comment]
Sorry :) Just coming back from vacation… so here's a screenshot


image

On the left side is the current version of Edge on top and Chrome bottom.
Right side Edge with the css triangle

**Comment by eduplessis** [comment]
If you don't like the css triangle version… we can use a svg

**Comment by eduplessis** [comment]
And I've notice another problem with the character solution... It's the inconsistencies of the line height that cause some issues with the placement of the arrow in mobile 

https://photos.app.goo.gl/V696P1ybBN7nEwHT9

**Comment by erquhart** [comment]
Yep, Unicode is not the way to go here, definitely agreed on svg!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eduplessis** [comment]
@erquhart I've changed the play button to a svg.

**Comment by erquhart** [comment]
Thanks @eduplessis - last bit, can you update the svg to be identical to the current triangle? It's shaped a bit differently and rounded.

**Comment by eduplessis** [comment]
@erquhart hum sure… can you send me a screenshot. Because since it's a Unicode arrow… and I presume you're on a Mac and I'm on a PC… it's not the same arrow that I see  :)

**Comment by erquhart** [comment]
Ah, didn't even consider that. Apparently it's from Apple's San Francisco. I pushed up a commit that adds the svg.

**Comment by eduplessis** [comment]
@erquhart it's ready!!!


fenec

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 91afef046dd48d10f596412480c415bdbf2044cd

https://deploy-preview-1640--cms-demo.netlify.com

**Pull request merged**
