### PR TITLE
Update Docs: Widgets “image”

### PR DESCRIPTION
**Pull request by eliasm307**
Automatically generated by Netlify CMS

Related to https://github.com/netlify/netlify-cms/issues/3671

### CODE REVIEW

**Review by erezrokah — APPROVED** [review]
Thanks @eliasm307!

**Comment by eliasm307** [comment]
@erezrokah hi, I didn't read the edits you had made properly but the absolute paths don't work if the media folder path starts with a single '/', it needs to be two slashes ie '//', this was not a typo in my original post.

The reasoning for this comes from the file at [/packages/netlify-cms-lib-util/src/path.ts](https://github.com/netlify/netlify-cms/blob/e0db5ea19a1a9b82b194c7e23b38a1f9cc1bbe20/packages/netlify-cms-lib-util/src/path.ts#L1) which defines an isAbsolutePath function using regex which matches for any strings starting with "//" (I was unsure if this was meant to be an escaped slash ie "\/"however "//" is valid in some cases so I assumed it was intentional) 
image

The isAbsolutePath function is used in the file at [/packages/netlify-cms-core/src/reducers/entries.ts](https://github.com/netlify/netlify-cms/blob/e52e29034ec508e1b371e4a2a733418f0c813e60/packages/netlify-cms-core/src/reducers/entries.ts#L755)  in the selectMediaFilePath function, see below. As you can see, if the input media path is an "absolute" path then this function does nothing and just returns the path, otherwise, it processes the path as normal where the path would be made relative to a media folder.
image

The selectMediaFilePath is then used in the file at [packages/netlify-cms-core/src/actions/media.ts](https://github.com/netlify/netlify-cms/blob/89848e034451baed52fb8911d3778a2f469462f8/packages/netlify-cms-core/src/actions/media.ts#L98) to get generate a "resolvedPath" which is then used for finding assets. 
image

From following this chain, my understanding was that prefixing the path with a double slash '//' allowed the CMS to look at absolute locations for assets, so as it stands the suggestion in the documentation of using a single slash '/' won't work, unless if the regex in the isAbsolutePath function is actually meant to be '\/' instead of '//'.

So either the documentation or the code needs to change in order to align, from my understanding.

Apologies if I have misunderstood something.

**Comment by erezrokah** [comment]
> The reasoning for this comes from the file at [/packages/netlify-cms-lib-util/src/path.ts](https://github.com/netlify/netlify-cms/blob/e0db5ea19a1a9b82b194c7e23b38a1f9cc1bbe20/packages/netlify-cms-lib-util/src/path.ts#L1) which defines an isAbsolutePath function using regex which matches for any strings starting with "//" (I was unsure if this was meant to be an escaped slash ie "/"however "//" is valid in some cases so I assumed it was intentional)

Hi @eliasm307, thank you for following up on this.
That function is actually testing absolute URLs (e.g. `https://`) and not paths - we should probably rename it.

The test for paths starting with `/` is done here:
https://github.com/netlify/netlify-cms/blob/e0db5ea19a1a9b82b194c7e23b38a1f9cc1bbe20/packages/netlify-cms-core/src/reducers/entries.ts#L741

**Comment by eliasm307** [comment]
Hi @erezrokah thanks for your reply. I'll have a look again however previously when I had tried to use a single '/' for the media folder path the result was that images were saved relative to the collection folder. I'll see if I was doing something wrong

**Comment by erezrokah** [comment]
> Hi @erezrokah thanks for your reply. I'll have a look again however previously when I had tried to use a single '/' for the media folder path the result was that images were saved relative to the collection folder. I'll see if I was doing something wrong

Thanks, please open a bug if it reproduces.

**Pull request merged**
