### PR TITLE
Allow setting publish_mode to 'simple' in config.yml

### LINKED ISSUE #1811: Not possible to set `editorial_mode` to `simple`
**Describe the bug**

I normally have `publish_mode` set to `"editorial_workflow"`, but for local editing I've set up a file-system API. I'm using the `CMS_ENV` variable  in cms.js to provide config overrides during development, and thus I needed to unset the editorial_workflow. I tried setting `publish_mode: null` and `undefined`, found that the default was `simple` in the source code, but neither works.

**To Reproduce**
1. in config.yml, add a line `publish_mode: simple`. 
2. refresh the admin page

**Expected behavior**
Admin should run without editorial workflow enabled. Instead, the following error is shown:

```
Config Errors:
'publish_mode' should be equal to one of the allowed values
Check your config.yml file.
```

### PR DESCRIPTION
**Pull request by Benaiah**
**Summary**

Closes #1811 - see issue for details.

**Test plan**

Tested manually.

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit e0577cb0fdcd63832e1ef677b60fb1a0acb3670a

https://deploy-preview-1827--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit e0577cb0fdcd63832e1ef677b60fb1a0acb3670a

https://deploy-preview-1827--cms-demo.netlify.com

**Comment by Brondahl** [comment]
+1 for this - please could we have it released ASAP! :) #optimism

**Comment by Brondahl** [comment]
@erquhart Is it possible to get this change reviewed and merged?

**Comment by Brondahl** [comment]
See Issue #1811 for discussion of error this causes and cases where it can't be avoided.

**Comment by verythorough** [comment]
Seems like we should add this to the docs?

**Comment by tomrutgers** [comment]
We should, I can take a shot at it. If I understand correctly, the `simple` value is a more declarative way of saying you don't want to use the editorial workflow. It's just more reliable than commenting it out?

**Comment by erquhart** [comment]
The default value of `publish_mode` is `"SIMPLE"`, but you can also set it to `"EDITORIAL_WORKFLOW"`, that's all. It always worked I believe, just not documented that `"SIMPLE"` is the value used when you omit the property. This PR just added the value as a valid option in our newish config validator.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
