### PR TITLE
Display public_folder path in Media Library

### PR DESCRIPTION
**Pull request by Jinksi**
**- Summary**

It can be useful for content editors to see the path to uploaded media / files. I have added on the `public_folder` to the displayed filename.

This may not be desired for all users, maybe we can add an option in the config? 

**- Test plan**

Visual confirmation:

screen shot 2018-04-18 at 9 22 26 am

**- Description for the changelog**

Display public_folder path in Media Library

**- A picture of a cute animal (not mandatory but encouraged)**

wallaby-joey

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 7961027681583c225d6923a5ce6dc9b4c71280cc

https://deploy-preview-1281--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 7961027681583c225d6923a5ce6dc9b4c71280cc

https://deploy-preview-1281--netlify-cms-www.netlify.com

**Comment by erquhart** [comment]
Can you say the specific benefit(s) for you of seeing the path? Do you ever need to copy/paste it for some reason?

**Comment by Jinksi** [comment]
Yeh, we've had clients who wish to link to the asset directly in the markdown editor.

**Comment by erquhart** [comment]
Sorry, kinda slow over here I guess - help me understand exactly what they're wanting to do. Link to the asset directly how? And to what end?

**Comment by Jinksi** [comment]
No worries, I didn't explain it well.

For example:
- User uploads a PDF file to the Media Library
- User wishes to link to this file in Markdown Editor:  
  `More info [/assets/uploads/file.pdf](here)`

Displaying the path in the Media Library makes it more obvious for non-devs to find the file's path.

**Comment by tech4him1** [comment]
Is there a reason they can't just upload through an image block in MarkDown?

**Comment by Jinksi** [comment]
@tech4him1 this was my first response as well 😅 

We created a file block component for them (the image block only allows image files). However, editor blocks cannot be placed inline like this:

```
This is a paragraph, the user wants to link to [filename.pdf](/assets/uploads/filename.pdf) inside this paragraph.
```

If we could link to media using the Link button in the Markdown Editor, this would also solve the problem.

**Comment by erquhart** [comment]
That's a reasonable feature request.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by erquhart** [comment]
@Jinksi I don't think we should go with this PR as the solution, but the problem is definitely worth solving. Can you convert this to an issue?

**Comment by Jinksi** [comment]
@erquhart Will do. Agreed, the ability to add a dropdown with useful media meta-info would be great for certain client projects.

**Pull request closed without merging**
