### PR TITLE
Bug/fieldshandling

### LINKED ISSUE #1139: Select widget inside List widget crashing
**Bug**

**What is the current behavior?**

I've got a List widget with a Select widget as the field:

```yaml
- label: "Tags"
 name: "tags"
 widget: "list"
 field:
   - label: "Tag"
     name: "tag"
     widget: "select"
     options: [
       '11 Plus','A-Level Results','API','Accounting','Analytics','Business Management','CRM','Compare','Edtech',
       'Education','Exam','Features','Grammar Schools','Internship','Language Learning',
       'Managing a tutoring agency','Marketing','Mobile','National Tutoring Conference','Newsletter',
       'Online Tutoring','Open Source','Oxbridge Admissions','Recruitment','SEO','SaaS','Sales',
       'Small Business','Small business','Starting a business','Startup','Stripe','Teaching',
       'Technology','Testimonial','TutorCruncher','Tutoring','User Experience','VAT'
     ]
```
It renders like so:

image

Which I presume is wrong? The standard drop down renders properly when not in a List widget.

The field that should be a Select here renders as a text field, and when I input two letters (or add one and delete one), I get an error in the console (in `ListControl.js:156`)

```js
Uncaught TypeError: t.getObjectValue(...).set is not a function
    at ListControl.js:156
    at onChange (EditorControl.js:68)
    at onChange (StringControl.js:30)
    at Object.s (react-dom.production.min.js:25)
    at Object.invokeGuardedCallback (react-dom.production.min.js:24)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.production.min.js:24)
    at p (react-dom.production.min.js:29)
    at v (react-dom.production.min.js:31)
    at y (react-dom.production.min.js:31)
    at Array.forEach (<anonymous>)
```

I'm using Jekyll, Netlify CMS version 1.2.2 and I've tried Chrome and Firefox on Ubuntu and Windows.

I seem unable to find an example of this on someone's site working, so if anyone can point me towards that I'd be happy to take a look.

### PR DESCRIPTION
**Pull request by brianlmacdonald**
Closes #1139. Fixes handling of ```config```'s `field` in `ObjectControl.js` where before using `field` would break the widget.

**- Summary**

```
    const { field, forID, classNameWrapper, forList } = this.props;
    const { collapsed } = this.state;
    const multiFields = field.get('fields');
    const singleField = field.get('field');

    if (multiFields) {
      return (
        <div id={forID} className={c(classNameWrapper, 'nc-objectControl-root')}>
          { forList ? null : <TopBar collapsed={collapsed} onCollapseToggle={this.handleCollapseToggle} /> }
          { collapsed ? null : multiFields.map((f, idx) => this.controlFor(f, idx)) }
        </div>
      );
    } else if (singleField) {
      return this.controlFor(singleField);
    }

    return <h3>No field(s) defined for this widget</h3>;
  }
}
```

The `singleField` being passed on to `ObjectControl` 's `controlFor` function wasn't able to be properly parsed. Since the handling of `fields` was working in a pinch for `field`, which passed its elements to `controlFor` using `multiFields.map`, I passed `singleField.first()` to `controlFor` and it fixed the issue. 

An alternate could be to have `singleField` and `multiFields`handled the same way in a single `if` statement:

```
if (multiFields || singleField) { 
     const fieldsForControl = multiFields ? multiFields : singleField
    return (
        <div id={forID} className={c(classNameWrapper, 'nc-objectControl-root')}>
          { forList ? null : <TopBar collapsed={collapsed} onCollapseToggle={this.handleCollapseToggle} /> }
          { collapsed ? null : fieldsForControl.map((f, idx) => this.controlFor(f, idx)) }
        </div>
      );
```

**- Test plan**
Behold, the working `field' !

screen shot 2018-03-08 at 12 13 42 pm
screen shot 2018-03-08 at 12 13 52 pm
screen shot 2018-03-08 at 12 13 59 pm

**- Description for the changelog**

Fixes bug in handling of `field`.

**- A picture of a cute animal (not mandatory but encouraged)**

Behold, a small wombat!
wombat

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit f77c82c8bb22d330ba4928c29ad3a54c037d975d

https://deploy-preview-1165--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit f77c82c8bb22d330ba4928c29ad3a54c037d975d

https://deploy-preview-1165--cms-demo.netlify.com

**Comment by erquhart** [comment]
Thanks for this!

Would you mind updating this to use an `if` statement as you mentioned? That will fix the UI appearance so the field is wrapped in the draggable box.

**Comment by erquhart** [comment]
@brianlmacdonald did you try typing in the field? Getting errors there, the field stops accepting input after one character. Looks like we're not outputting the kind of value expected.

**Comment by brianlmacdonald** [comment]
@erquhart I'll check it out and report back soon!

**Comment by brianlmacdonald** [comment]
The problem in `handleChangeFor(index)` was, again, trying to do something different with `field` vs `fields`.  

There was a check `const parsedValue = (this.valueType === valueTypes.SINGLE) ? newObjectValue.first() : newObjectValue;` that would hand `onchange` `parsedValue` which was a string, instead of an immutable.js `Map` . Removing this check and handing the onChange the same value that it yields from `fields` fixes it. Therefore it wasn't necessary to parse a different value from `newObjectValue` anymore.

While playing around with all the widgets in kitchen sink, all of them work with this change.

```
handleChangeFor(index) {
    return (fieldName, newValue, newMetadata) => {
      const { value, metadata, onChange, forID } = this.props;
      const newObjectValue = this.getObjectValue(index).set(fieldName, newValue);
      const parsedMetadata = {
        [forID]: Object.assign(metadata ? metadata.toJS() : {}, newMetadata ? newMetadata[forID] : {}),
      };
      onChange(value.set(index, newObjectValue), parsedMetadata);
    };
  }
```

**Comment by erquhart** [comment]
Thanks for the quick fix Brian!

Starting to notice a few red flags:

1. Values entered this way aren't showing up in the preview pane
2. There are other areas of code that treat a single field value differently than "fields", e.g. the [`handleAdd` function](https://cms-demo.netlify.com/#/collections/kitchenSink/entries/a-big-entry-with-all-the-things)
3. This change is essentially making "field" identical in output to "fields", except that it only accepts a single value and wraps it in a map, versus just accepting a map - I'm concerned we're wiping out functionality without fully understanding why it was included in the first place

One thing that comes to mind is the resulting data structure. I have a feeling that the list widget was using this to produce an array of values, so we should confirm that the data structure is still the same. I'm guessing it isn't.

We should check an old version of the CMS, maybe pre-1.0, and see how this used to behave.

**Comment by brianlmacdonald** [comment]
@erquhart Cool! I'll start doing more detective work. While I'm at it, why don't I add some tests for everything ListControl does, so that the next time there's a change like this it'll get snuffed out quickly.

**Comment by erquhart** [comment]
Testing would be awesome! We definitely need to step up our coverage.

**Comment by brianlmacdonald** [comment]
@erquhart I checked out each release of Netlify until eventually arriving at PR #175 where the code was introduced, and `field` still breaks the widget. I emailed Cassio, who authored the code, (he's my former teacher) to make sure that field is being used as intended. I'll let you know when I hear back.

**Comment by erquhart** [comment]
Alright, cool. I won't be shocked if he doesn't remember, it's been a while :)

**Comment by brianlmacdonald** [comment]
@erquhart haven't gotten a response yet. I've sent two emails. How would you like me to proceed?

**Comment by brianlmacdonald** [comment]
@erquhart I'll jump back on this, this week. Thanks!

**Comment by brianlmacdonald** [comment]
Despite my best efforts to rebase, this went chaotically bad. It was late, I had a minor meltdown, and closed this and did a new pr with #1373.

**Pull request closed without merging**
