### PR TITLE
very minor padding adjustments

### PR DESCRIPTION
**Pull request by gil--**
**- Summary**

I felt there were two instances where bottom padding was missing and added them in this PR.  They're very minor adjustments for the editor pane controls. 

**- Test plan**

### Before/After Control
control_padding

### Before/After EditorPaneRoot
root_padding

**- Description for the changelog**
- Add missing bottom padding to editControl
- Adding missing bottom padding to editorPaneRoot

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 12b2610b7053cf28439aab48ee5856521b43cfa4

https://deploy-preview-1420--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 12b2610b7053cf28439aab48ee5856521b43cfa4

https://deploy-preview-1420--cms-demo.netlify.com

**Comment by tech4him1** [comment]
The object control fix looks great, thank you!

On the editor padding fix, I'm already seeing 16px of padding between the bottom of the window and the last control, on `nc-entryEditor-controlPane`, so this would make it 32px. What browser are you testing on? I don't have a problem with changing it, just want to be consistent if possible.

**Comment by tech4him1** [comment]
Just checked in Safari as well -- the padding on the outer element is already there as well.

**Comment by gil--** [comment]
Latest commit 22c5e6b69fbd6e732b59039bbdab0a693a1dbbd0 appears to work consistently across Firefox and Chrome.

**Pull request merged**
