### PR TITLE
[wip] convert website from postcss to emotion 

### PR DESCRIPTION
**Pull request by zebapy**
As mentioned in https://github.com/netlify/netlify-cms/pull/1707, here's conversion of site from postcss to using emotion package (combinations of emotion/styled and `css` from emotion/core). 

- upgrade react to 16.8
- convert most React.Component usage to hooks
- set all gatsby packages to a version instead of `next`
- update deprecated functions in `gatsby-node.js`
- renamed grey variables to gray 
- all css variables are in `theme.js` now
  - ideally we get ThemeProvider working properly so you can use a helper to get theme variables instead of importing the theme file every time (though you'd need to import the helper so 🤷‍♂️)
- use 1 nav for mobile and desktop now (as mentioned in #1707)
- ~~❓I moved search from header to above docs nav~~
  ~~1. original site hides it on all other pages except docs anyway~~
  ~~2. it's hidden on mobile on live site. This way we can expose it on mobile without needing to rework the header much to add a search toggle (I started with this approach. If we want to go that way, I can do that too)~~
- changed code previews to not bleed out of their container (dependent on magic number negative margins). I think it's easier to leave it as is. 
- styling body content from the cms is simplified via a `<StyledMarkdown>` component which styles all appropriate children (h2, p, li, etc)
- change mobile nav to hamburger button and search button

Overall I think this makes things a little more manageable as it eliminates most of the specificity issues the previous css had. The level up to this is using something like https://github.com/jxnblk/styled-system (huge fan of this, makes things scale better and you truly don't have to write css ever and you can easily adhere to your "design system"-lite / theme.js)

Please let me know of any major issues. 

## todo
- [x] change sticky header background color on scroll like live site? 
- [x] fix content expanding out of container (see cloudinary page) https://github.com/netlify/netlify-cms/pull/2068#issuecomment-462147498
- [x] fix icon alignment on homepage video

### CODE REVIEW

**Comment by erquhart** [comment]
Awesome, glad to see this @zebapy!

Fwiw, I think the search bar _should_ be on every page, including the home page. That's the norm on every docs site, and it's annoying when I run there to find something quick and have to navigate to docs before searching.

**Comment by zebapy** [comment]
I do agree. I'll take a stab at it soon.

**Comment by zebapy** [comment]
any issues with converting to hooks?

**Comment by erquhart** [comment]
Sounds awesome, go nuts 👍🏼👍🏼

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by talves** [comment]
@zebapy when moving to emotion, do you think it would be overkill to consider allowing the master theme to be over-ridden at the time of a manual init?

I don't want to squelch your progress, just wondering your thoughts on the proposal.

**Comment by zebapy** [comment]
@talves what would use case be for that? If that were to be added, preferably after these changes as a different branch.

**Comment by erquhart** [comment]
@talves this is just for the docs site, not the CMS itself.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by talves** [comment]
@erquhart ahh, I was not thinking about the scope of the changes. Got excited here.

**Comment by zebapy** [comment]
ok, couple issues I could maybe use a hand if anyone has time. 

1. Looks like some package upgrades are messing with prism
  prism-issue-code
  renders as 
  prism issue preview
 Removing the space in between the lines fixes it but doesn't seem ideal to go through all code examples to fix it.. 

2. When routes change, header rerenders (due to new gatsby v2 layout changes, causing github button to rerender/flash quickly. This doesn't seem to happen on the live site, so not sure what it's causing it now.

**Comment by erquhart** [comment]
Got it 👍 Worst case you can finish up the PR with those two issues outstanding and we can address before merge (if someone hasn't dug in by then).

**Comment by zebapy** [comment]
Can we get a preview deploy again? Not sure why it's not updated. It was in a pretty good place.

**Comment by erquhart** [comment]
Looks like it failed linting (you can click Details for a log) - if you run `yarn format` it should be able to fix up the issues.

**Comment by zebapy** [comment]
This should be in a good place for another review

**Comment by zebapy** [comment]
are there any areas that are major deal breakers you could point out?

**Comment by erquhart** [comment]
@zebapy any thoughts on my comment?

**Comment by zebapy** [comment]
Yes I see them and will try to get to it soon. Sorry for hold up!

**Comment by erquhart** [comment]
No problem at all, looking forward to getting the updates in!

**Comment by zebapy** [comment]
@erquhart I think I got things a little bit closer if you can take a look

**Comment by erquhart** [comment]
Sorry, this one slipped through the cracks @zebapy - we'll need to get this PR down to a clean refactor. The code improvements are fantastic, we need to tweak the styling so the site UI not be impacted.

A couple of the more obvious differences are represented in the gifs below (switching between the current site and deploy preview). Ideally everything would remain the same when switching between the two. There's definitely some amount of change that's acceptable, but I think the differences you see below are worth improving.

**Home**
cms-www-emotion-diff-home

**Docs**
cms-www-emotion-diff-docs

**Comment by erquhart** [comment]
@zebapy guessing you're not still looking into this but wanted to double check? Might just merge as is unless you'd advise against doing so. Rebasing and testing locally now.

**Comment by zebapy** [comment]
I haven't had time for OSS but if there's anything super critical for these
changes I could try to take a look

**Comment by erquhart** [comment]
Do you remember feeling like it was probably okay to merge, like anything flat out broken that wasn't ready for primetime?

**Comment by zebapy** [comment]
I believe the only parts left were the slight layout differences in the
gifs you supplied in previous comments

**Comment by erquhart** [comment]
Cool - we'll take what we've got here and worry about the rest later. Thanks for responding!

**Comment by erquhart** [comment]
Rebased, some changes still need to be properly reconciled:
- [ ] fix linting errors
- [ ] port updated community page styles
- [ ] port Slack button (shows at first but ends up hidden)
- [ ] header gradient comes down a lot lower than in production
- [ ] docs width should be wider
- [ ] a/b test for other size and spacing differences across the site
- [ ] update dependencies

**Pull request merged**
