### PR TITLE
Update Docs: Intro “start-with-a-template”

### PR DESCRIPTION
**Pull request by wernerglinka**
**Summary**

**Test plan**

**Checklist**

Please add a `x` inside each checkbox:

- [ ] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [ ] Code is formatted via running `yarn format`.
- [ ] Tests are passing via running `yarn test`.
- [ ] The status checks are successful (continuous integration). Those can be seen below.

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by erezrokah — CHANGES_REQUESTED** [review]
Thanks for the follow up @wernerglinka, we might want to chose a logo with better ratio, see 
image

https://deploy-preview-6327--netlify-cms-www.netlify.app/docs/start-with-a-template/

Also, what do you think about renaming the title from "Metalsmith Netlify Starter" to "Metalsmith Starter" so save some screen space?

Another thing I noticed is that the demo site linked from https://github.com/wernerglinka/metalsmith-netlify-starter is broken, see https://metalsmith-netlify-cms-starter.netlify.app/

**Comment by wernerglinka** [comment]
Changed logo and shortened title

**Comment by erezrokah** [comment]
Thanks @wernerglinka, can you check https://metalsmith-netlify-cms-starter.netlify.app/? I might be confusing for users reading the README that the link is broken.

**Comment by wernerglinka** [comment]
I fixed the link

**Comment by erezrokah** [comment]
> I fixed the link

Great, I think I used the stale one from the PR. https://metalsmith-netlify-starter.netlify.app/ works!

**Comment by erezrokah** [comment]
Thanks for the follow up @wernerglinka 🚀

**Pull request merged**
