### PR TITLE
Drop outdated Gatsby note from quick start docs.

### PR DESCRIPTION
**Pull request by tech4him1**
**- Summary**

This note doesn't seem to be necessary anymore, and seems to be causing way more problems than it's worth.

**- Test plan**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by verythorough** [comment]
Weird. That text was replaced in a previous PR (from you!): https://github.com/netlify/netlify-cms/pull/652/files

Checking to see where it got dropped, but blame is weird after removing the docs and then reverting.

**Comment by verythorough** [comment]
Of course it was in my git-gateway re-write. Didn't catch it in the rebase. 🙈 

So what do you think we should do, @tech4him1?
Remove the note completely, or re-replace it with your newer text (below)?
> Gatsby treats the `static` folder more strictly when you are using `gatsby develop` and will not render the admin page if you go to `/admin` like the other generators. Instead, you must go to `/admin/index.html`. When you actually build the site with `gatsby build`, it should resolve correctly.

**Comment by tech4him1** [comment]
@AustinGreen Sorry to ping you without any context here, but I'm not a Gatsby dev 😄.We're trying to rework our docs on Gatsby, and I want to be sure that they are accurate. I noticed on your template that a production build had to be used to use the CMS. What was the problem there?

**Comment by AustinGreen** [comment]
Gatsby allows you to add files outside of the module system by including a static directory at the project's root. Adding the admin directory here keeps it separate from the public-facing aspect of your site, but it can only be accessed when viewing a production build.

This issue has come up a few times, so I'd be curious to hear @KyleAMathews thoughts on the topic. Should a CMS admin page be processed by webpack or does it belong in the static directory?

I've had a good experience using `gatsby develop` to build the site components, and only running a prod build when testing the CMS locally (doesn't happen often). The doc's language should make the distinction between the two.

**Comment by KyleAMathews** [comment]
It's a separate standalone app so `/static` seems appropriate.

**Comment by tech4him1** [comment]
@AustinGreen Interesting, when I played with Gatsby before, I *was* able to access the static files while running `gatsby develop`, I just had to access the actual `/admin/index.html` page instead of going to the dir root `/admin/`. I filed that issue (https://github.com/gatsbyjs/gatsby/issues/2352), but never had a chance to get around to fixing it. Does that work for you?

**Comment by AustinGreen** [comment]
@tech4him1 going to `/admin/index.html ` appears to work just fine! I was able to make a change in the CMS. Need help crafting the paragraph to explain this?

**Comment by tech4him1** [comment]
That would be awesome!

**Comment by AustinGreen** [comment]
Cool, I'll create a new PR and you can read it over

**Comment by AustinGreen** [comment]
Hmm after reading the page I think the helper paragraph should just be removed. This would be a good spot to add a link to community starter templates, but that can be added later. You can remove the * next to Gatsby, and this PR should be good to go.

**Comment by verythorough** [comment]
Ah, good catch, @AustinGreen!

**Comment by tech4him1** [comment]
Thanks @AustinGreen!

@verythorough I was actually thinking of that myself -- do you like the idea of putting the starter sites in this table, or do you want them somewhere else?

**Pull request merged**
