### PR TITLE
File-system backend fixes and support JWT

### PR DESCRIPTION
**Pull request by igk1972**
**- Summary**

The need for Netlify-CMS to work with a remote file-system backend.
In plans, implement a standalone backend on nodejs and go lang. With the generation of jwt tokens.

**- Test plan**

- Run yarn build.
- Download and run preview api code in from https://gist.github.com/igk1972/367b68b26495f47c1b571cdd38f720c5

**- Description for the changelog**

- remove obsolete file logo.
- update AuthenticationPage - html & css.
- add support netlify identity - jwt token.
- fix tokenPromise - not work with fetch.

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 5929454a8e5267ff3dc3fed843817748f988745c

https://deploy-preview-1029--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 5929454a8e5267ff3dc3fed843817748f988745c

https://deploy-preview-1029--netlify-cms-www.netlify.com

**Comment by talves** [comment]
***Note:*** A branch for having [external register of a backend has been proposed here as #1011](https://github.com/netlify/netlify-cms/pull/1011)
  - I have successfully exported the `file-system` backend for use using #1011 with a couple caveats.

@igk1972 I think this is a viable solution and good idea. Not sure the development targeted `file-system` would require auth. Needs discussion.

I have also created a stand alone express server solution for using the `file-system` and realized the requirement for a stand alone server will be project specific and should stand as a project/solution on it's own.

Takeaways:
- Discussion for the [development file-system](https://github.com/netlify/netlify-cms/pull/786) #786 being removed to an external backend should be discussed
- This is definitely a solution that should be exported to make a stand alone server using a backend to support file-system with auth.

cc/ @erquhart , @Benaiah , @tech4him1

**Comment by igk1972** [comment]
@talves then I will focus on go lang implementation stand alone server.

**Comment by talves** [comment]
@igk1972 you could use the example backend repo as a skeleton and export your solution into an external backend. Use netlify/netlify-cms#1011 as the cms build to test it.

**Comment by erquhart** [comment]
@talves should we close this?

**Comment by talves** [comment]
Yes, this should be closed. There is now a solution to be able to take this to an external backend.

#1011 has been accepted, so this solution can be exported like [my example](https://github.com/talves/netlify-cms-backend-fs/tree/master). Note the `cms-server` branch also.

**Pull request closed without merging**
