### PR TITLE
3266 - Themes

### LINKED ISSUE #3266: Add or update theme for use in all components
Based on the design in #2557, update the header UI in the project. Feel free to use [this CodeSandbox](https://codesandbox.io/s/netlify-cms-editor-design-j1cg3) for reference.

- [ ] Architect and plan style theme for scalable use across the app
- [ ] Add colors, fonts, and other commonly referenced theme items
- [ ] Open a pull request

### PR DESCRIPTION
**Pull request by pniedzwiedzinski**
I think that this will close #3266 

**Summary**

I added `themes.js` with themes from @austincondiff's sandbox. These themes are later used in storybook thanks to `storybook-multiple-themeprovider`, so when creating new stories the themes will be automatically available in the storybook.

I added `color` as dependency as it is used in themes. I also needed to add `styled-components` since plugin `storybook-multiple-themeprovider` is using it. I wrote to the author about it, so as soon as it will be fixed I will remove it. And also `react-hot-loader` was needed to start storybook.

By mistake added here this button, that I'm working on. Should I remove or is it okay to leave it here?

**Test plan**

Run storybook and enjoy 😄

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by austincondiff** [comment]
Are we using this theme in the project (not only in Storybook) via a `<ThemeProvider />`?

https://emotion.sh/docs/theming

**Comment by fpunny** [comment]
I have some experience with Storybook, and I'm not sure if the ThemeProvider is used properly, I can take a look at the package to make sure

**Comment by fpunny** [comment]
Also insteading of using color, perhaps we can try polished instead? It offers a wider range of tools which might be useful for other tasks beyond this

https://polished.js.org/docs/

**Comment by erezrokah** [comment]
The cypress tests are expected to fail and that's fine.
Fixed the other build issues:
1. Uploaded `yarn.lock` file generated with yarn version `1.22.0`. Upgrading to yarn version 2 means all developers have to do it too (I think) and we would need to apply the migration to the master branch.
2. Fixed some lint errors.

We should look into removing that `styled-components` dependency before merging.

**Comment by austincondiff** [comment]
@pniedzwiedzinski Any way we can remove `styled-components`? Any response from `storybook-multiple-themeprovider`? Can you link us to the issue?
@erezrokah Is this the only thing holding us back?

**Comment by pniedzwiedzinski** [comment]
> @pniedzwiedzinski Any way we can remove `styled-components`? Any response from `storybook-multiple-themeprovider`? Can you link us to the issue?
> @erezrokah Is this the only thing holding us back?

No response, this repo has disabled fork so I send it via email.

> What if we used this instead?
> https://github.com/JumboInteractiveLimited/storybook-addon-emotion-theme

Sound good! Even better! I will change it. And thanks to that maybe we will get rid of `styled-components`

**Comment by erezrokah** [comment]
> What if we used this instead?
> https://github.com/JumboInteractiveLimited/storybook-addon-emotion-theme

Per this issue comment https://github.com/JumboInteractiveLimited/storybook-addon-emotion-theme/issues/10#issuecomment-526393858 I'm not sure we should introduce that dependency.

Can we add theming without the storybook support for them? I understand it is very useful to change themes inside storybook but not very keen on adding unmaintained dependencies.

**Comment by austincondiff** [comment]
@erezrokah I saw that and tried using the add-on @pniedzwiedzinski was using. We are both not able to get it to work even when we include the `styled-components` dependency.

**Comment by erezrokah** [comment]
I'll work on finding a solution without the styled components dependency

**Comment by erezrokah** [comment]
FYI, also found this https://github.com/eBay/storybook-addon-themepicker.
Seems like we can just write an addon ourselves.

**Comment by erezrokah** [comment]
Closing as this change was included in this branch https://github.com/netlify/netlify-cms/tree/v3-ui-redesign

**Pull request closed without merging**
