### PR TITLE
fix(i18n): data is not duplicated for default value setting

### LINKED ISSUE #4356: i18n: data is not duplicated for default value setting
**Describe the bug**
when setting **i18n: duplicate** in string widget, the value is not duplicated from the defalut locale if there is a default value setting

**To Reproduce**
1. Setting:
```yaml
backend:
  name: gitlab

i18n:
  structure:  multiple_files
  locales: [en, th]
  defaultLocale: en

collections:
- name: "test"
  folder: "content"
  path: "{{slug}}/index"
  media_folder: ''
  public_folder: ''
  create: true
  i18n: true
  fields:
  - {label: Author, name: author, widget: string, default: "tester", i18n: duplicate}
```
2. create content without touching the "Author" field(if it was edited, the value will be duplicated).
3. see the non-default locales, there is no  "Author"field.

**Expected behavior**

when setting **i18n: duplicate** in any widgets, the value shall duplicated from the defalut locale.

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

netlify-cms-app 2.12.24
netlify-cms-core 2.30.7
netlify-cms 2.10.60

**CMS configuration**

```yaml
backend:
  name: gitlab

i18n:
  structure:  multiple_files
  locales: [en, th]
  defaultLocale: en

collections:
- name: "test"
  folder: "content"
  path: "{{slug}}/index"
  media_folder: ''
  public_folder: ''
  create: true
  i18n: true
  fields:
  - {label: Author, name: author, widget: string, default: "tester", i18n: duplicate}
```

**Additional context**

### PR DESCRIPTION
**Pull request by blackb1rd**
Closes #4356 

I'm not familar with React if any going wrong let me know.

### CODE REVIEW

**Comment by blackb1rd** [comment]
simple_workflow_spec_proxy_git_backend.js failed, it seems not releted to the code change. running local and passing

For i18n_simple_workflow_spec_proxy_fs_backend.js
> 1) I18N Proxy Backend Simple Workflow - 'fs' mode
>       can create entry with translation in locale_folders mode:
>
>      Timed out retrying
>     + expected - actual
>
>     -'---\ntemplate: post\ntitle: de\ndate: 1970-01-01T00:00:00.000Z\n---\n'
>     +'---\ntitle: de\ndate: 1970-01-01T00:00:00.000Z\n---\n'

I'm not so sure what we are expecting for `template: post`...

**Comment by blackb1rd** [comment]
> simple_workflow_spec_proxy_git_backend.js failed, it seems not releted to the code change. running local and passing
> 
> For i18n_simple_workflow_spec_proxy_fs_backend.js
> 
> > 1. I18N Proxy Backend Simple Workflow - 'fs' mode
> >    can create entry with translation in locale_folders mode:
> >    Timed out retrying
> >    
> >    * expected - actual
> >    
> >    -'---\ntemplate: post\ntitle: de\ndate: 1970-01-01T00:00:00.000Z\n---\n'
> >    +'---\ntitle: de\ndate: 1970-01-01T00:00:00.000Z\n---\n'
> 
> Not sure what we are expecting this test...

Seems we expecting template: post all locales.

**Review by erezrokah — CHANGES_REQUESTED** [review]
Thank you for jumping on this @blackb1rd.

The tests were failing since this fix will result in any field with a default value to be a part of the `i18n` entries (even if they are not configured as ones).

With this fix the `template` field is written to the `i18n` entries:
https://github.com/netlify/netlify-cms/blob/736ca57d6edfa0c7520db6be7978c3352463b839/dev-test/backends/proxy/config.yml#L21

and it shouldn't.

We'll need to duplicate only fields that has `i18n` as `translate` or `duplicate` set on them.

**Comment by blackb1rd** [comment]
> We'll need to duplicate only fields that has `i18n` as `translate` or `duplicate` set on them.

@erezrokah  done as your requested.

**Review by erezrokah — APPROVED** [review]
Thanks @blackb1rd, I added another commit with some code cleanup - mostly to extract the `i18n` specific logic from `createEmptyDraftData`

**Comment by blackb1rd** [comment]
@erezrokah awesome :grinning: and waiting for release version with this fix :kissing_heart:

**Comment by erezrokah** [comment]
This is now released https://github.com/netlify/netlify-cms/releases

**Comment by frankharrison** [comment]
@erezrokah should this be working in the current version? I've tried adding `i18n: duplicate` and `i18n: true` to my hidden fields, but only the default locale gets them. My collections config looks like this:

```
collections:
  - name: 'webviews'
    create: true
    i18n: true
    label: 'Webview'
    folder: 'src/_cms-data'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'webview', i18n: duplicate }
      - { label: 'Tags', name: 'tags', widget: 'hidden', default: 'webview', i18n: duplicate }
      - { label: 'Permalink', name: 'permalink', widget: 'hidden', default: '/{{ locale }}/webviews/{{ title | slug }}', i18n: duplicate }
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
```

Thanks in advance for any pointers.

**Pull request merged**
