### PR TITLE
blob function on assets

### PR DESCRIPTION
**Pull request by taussoe**
Corrupt images when uploading to bitbucket

### CODE REVIEW

**Comment by zanedev** [comment]
LGTM merging

**Comment by tortilaman** [comment]
@zanedev Considering one of the tests on travis-ci is failing because it's written for github integration, might it be a good idea to address that before merging? Perhaps check which backend is being used, and have the test run accordingly?

**Comment by zanedev** [comment]
@tortilaman sure will fix it on my next push, I'm still in way experimental mode and need to get into the tests more.  Thanks for bringing it to my attention

**Comment by tortilaman** [comment]
@zanedev no problem. I'm not the biggest tester either, so I can understand.

**Pull request merged**
