### PR TITLE
Remove extra 'the'

### PR DESCRIPTION
**Pull request by robphoenix**
**- Summary**

This PR removes a superfluous occurrence of the word **the**. It contributes to solving the problem of accidental grammatical errors in documentation.

**- Test plan**

Ask someone else to read it, and ask them if it is correct. 

**- Description for the changelog**

Documentation updated for accidental grammatical error.

**- A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 0e5b3a08bc8f77dbe6e0c7a68a524b107d1d683a

https://deploy-preview-1106--netlify-cms-www.netlify.com

**Comment by tech4him1** [comment]
@robphoenix Would you mind adding yourself to our contributors list? https://github.com/netlify/netlify-cms/blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor

**Comment by robphoenix** [comment]
@tech4him1 Sorry, I didn't get a chance to add myself to the contributors list this time. I'll have a browse through the issues, see if there's something else I can do.

**Comment by talves** [comment]
@robphoenix you can just do a PR for adding yourself to the contributors list if you want

**Pull request merged**
