### PR TITLE
Issue with netlify identity initialization

### PR DESCRIPTION
**Pull request by acarl**
I was having difficulty getting netlify identity to initialize. I ran across the solution in this repository.

https://github.com/AustinGreen/gatsby-starter-netlify-cms/blob/master/src/pages/index.js

I think that it should be updated here or at least mentioned if it is necessary for this to work.

**- Summary**

**- Test plan**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 34ce3d2b16fdaa78233c154188fafe35e8dff1f5

https://deploy-preview-1030--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 34ce3d2b16fdaa78233c154188fafe35e8dff1f5

https://deploy-preview-1030--netlify-cms-www.netlify.com

**Comment by erquhart** [comment]
@acarl trouble is, this isn't necessary in all cases. What was your use case?

**Comment by acarl** [comment]
I had a feeling that might be the case. I am setting up netlify cms with netlify identity on at gatsby site. When I click on the invite link in an email it takes me to the index with the authentication token in the url, but nothing happens. Shouldn't a user be prompted to establish credentials at that point? Maybe I just missed something in the documentation.

**Comment by erquhart** [comment]
It may be necessary with Gatsby, I need to get a bead on when manual initialization is required.

**Comment by futuregerald** [comment]
@acarl When you use Identity, you need to import the identity widget script in to your sites main index.html since it's gotrue-js (that the widget is built on) processes the token to complete account verification. That's why in the cms docs (https://www.netlifycms.org/docs/add-to-your-site/#authentication) it tells you to import the widget on your site's index.html

**Comment by acarl** [comment]
@futuregerald The identity widget is being imported onto the page as shown in the linked example.
https://github.com/AustinGreen/gatsby-starter-netlify-cms/blob/master/src/pages/index.js#L27

I'll close this pull request and move the discussion to an issue instead.
https://github.com/netlify/netlify-cms/issues/1108

**Pull request closed without merging**
