### PR TITLE
docs: fix Overlay issue in docs page

### PR DESCRIPTION
**Pull request by mbj36**
There are some pages where page has horizontal scrolling  due to content being overflowed

Example - https://www.netlifycms.org/docs/gatsby/

This PR formats the docs

### CODE REVIEW

**Comment by ndalliard** [comment]
I am not sure this PR solves the issue.

20200128-094927-1920x969+0+111

**Comment by mbj36** [comment]
@ndalliard  Updated the PR

**Comment by ndalliard** [comment]
@mbj36 Look at the [deploy preview](https://deploy-preview-3153--netlify-cms-www.netlify.com/docs/cloudinary/), there is still a horizontal scroll.

**Comment by mbj36** [comment]
@ndalliard I am using 13inch MBP, I don't see any scroll

**Comment by tomrutgers** [comment]
> @ndalliard I am using 13inch MBP, I don't see any scroll

It's there though, below 1140px screen width. Try testing on several browser sizes and devices.

**Comment by erezrokah** [comment]
@mbj36 thanks for this, but I'm not sure we want to solve this just by adding line breaks in various locations as future content might have the same issue (or even existing content that we've missed).
Updating the site css or making sure the content is formatted to a certain width might be a better approach.

**Comment by mbj36** [comment]
@erezrokah I agree...i will create a new fix for this.

**Pull request closed without merging**
