### PR TITLE
EXPERIMENT w/preact

### PR DESCRIPTION
**Pull request by bdougie**
*This is an experiment and not meant to be merged!

**- Summary**
This PR is the result of an internal discussion happening in the internal Netlify Slack. Can we try Preact on the CMS and what is the limitation? This is a branch I created 2 months ago when I created this issue #328. I originally thought there were issues with it but I am not seeing any issues by just simply adding preact-compat.

**- Test plan**
Run the example app from this deploy preview and report issues with this idea.

Also feel free to suggest alternatives  

**- A picture of a cute animal (not mandatory but encouraged)**
download

### CODE REVIEW

**Comment by bdougie** [comment]
First issue I have found is that logging in does work and renders the browser unusable :)

screenshot 2017-05-03 11 32 22

**Comment by verythorough** [comment]
Not relevant to the code, but that mouse in a sweater demands comment.

**Comment by bdougie** [comment]
Feel free to reopen, but I am going to close this for now since there is a pretty gnarly bug causing the login for the example app to kill your browser tab. I will test locally later.

**Comment by jhabdas** [comment]
@bdougie I love your spikes! You may find this interesting, as a provides a scaffold for starting universal apps with React, Preact, Inferno and Rax, and could provide some insight on how best to start structuring the architecture for the eventual migration away from React: https://github.com/jaredpalmer/razzle

**Comment by bdougie** [comment]
Thanks for the tip @jhabdas. I think I might put some playtime with razzle and explore this. Seems like a great tool to start an internal side project

**Comment by talves** [comment]
@bdougie we are cleaning up old stale branches, can we delete this branch?

**Pull request closed without merging**
