### PR TITLE
fix(relation-widget): i18n options

### LINKED ISSUE #4491: Relation widget not working with new i18n multilanguage feature
Description:

- Relation widget only queries the default entry language for the required data even when the language is changed in the CMS preview.

Steps to Reproduce:
1. Configure config.toml with the new i18n feature with 2 languages (like "en" and "pt")
2. Create a collection ("test", for example) with the "path" string widget field and create and entry in cms for both languages. In "pt", the path field will receive "portuguese" as it's value, and in "en", the field value will be "english"
3. Create another collection with a field configured just like in the first screenshot
4. Open the entry with the relation widget in CMS preview, and the relation widget will only show the value from the default language in both entry languages

Expected behavior:
- The relation widget will show "english" in both entry languages

Screenshots:
image

image

image

Versions:
- netlify-cms-app 2.12.24
- netlify-cms-core 2.30.7

CMS configuration:
image

### PR DESCRIPTION
**Pull request by demshy**
**Summary**
Options in relation widget were not translated for collection or file based relations. I passed the `locale` into the component so that the function that parses these options can use it accordingly.

fixes #4491

**Test plan**
As I'm new here, I didn't feel quite comfortable adding props to the main editor blocks, but didn't find another way to access locale of the component that is rendered. If there is another (better) way, please inform me and I will update this accordingly.
 
Screenshot 2022-03-15 at 17 51 55
Screenshot 2022-03-15 at 17 53 41

Config:
```
collections:
  - name: taxonomies
    label: Taxonomies
    format: json
    i18n:
      structure: single_file
      locales: [en, de]
    files: [
      {label: Travel type ideas, name: travelTypes, file: data/travelTypes.json, i18n: true, fields: [
        {name: title, label: title, widget: string, i18n: true},
        {name: items, label: items, widget: list, label_singular: item, i18n: true, fields: [
          {name: title, label: title, widget: string, i18n: true},
          {name: items, label: items, widget: list, label_singular: item, i18n: true, fields: [
            {name: title, label: title, widget: string},
            {name: id, label: id, widget: string, pattern: ['^[a-z0-9-]+$', 'Only lowercase letters, numbers, and hyphens allowed'], hint: 'IMPORTANT: All translations of this item must have the same ID'},
          ]},
        ]},
      ]},
    ]
  - name: travel-ideas
    label: Travel Ideas (experiences)
    label_singular: travel idea
    folder: content/experiences/travel-ideas
    create: true
    i18n: true
    fields: [
      {name: title, label: Title, widget: string, i18n: true},
      {name: travelType, label: Travel idea type, widget: relation, collection: taxonomies, file: travelTypes, search_fields: ["items.*.title"], display_fields: ["items.*.title"], value_field: "items.*.id", i18n: duplicate},
    ]
```
content in data/travelTypes.json
```
{
  "en": {
    "title": "Travel types EN",
    "items": [
      {
        "title": "Art and Culture",
        "id": "art-and-culture"
      },
      {
        "title": "Food and drink",
        "id": "food-and-drink"
      },
      {
        "title": "Outdoors",
        "id": "outdoors"
      }
    ]
  },
  "de": {
    "title": "Travel types DE",
    "items": [
      {
        "title": "Kunst und Kultur",
        "id": "art-and-culture"
      },
      {
        "title": "Essen und Trinken",
        "id": "food-and-drink"
      },
      {
        "title": "Draußen",
        "id": "outdoors"
      }
    ]
  }
}
```

**Checklist**

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x] Code is formatted via running `yarn format`.
- [x] Tests are passing via running `yarn test`.
- [ ] The status checks are successful (continuous integration). Those can be seen below.

**A picture of a cute animal (not mandatory but encouraged)**
a69429a0f5a4e808171d1be9751b6a83--cute-baby-animals-farm-animals

### CODE REVIEW

**Comment by bytrangle** [comment]
@demshy Can you provide more details in your description about how to set up the config file for i18n so that one can get the same result as your second screenshot?

**Comment by demshy** [comment]
Hi, of course, I completely forgot about this. I resolved this an extension of another issue (https://github.com/netlify/netlify-cms/issues/6264) which can be closed so I used the test case from that issue.

Anyhow, I have added the collection config and example json data file to the description.

**Comment by bytrangle** [comment]
And this is what the i18n support in the relation and object widgets should look like with your proposed changes, correct?

i18n-support-for-relation-and-object-widget

**Review by bytrangle — DISMISSED** [review]
Good job in retrieving options in the correct locale. However, the `locale` prop is being passed through several intermediary components that don't explicitly use them, namely `EditorControlPane` and `EditorControl`.

What do you think about using the context API to let `Widget` subscribe to `locale` value from `EditorControlPane`?

**Comment by demshy** [comment]
Hey guys, sorry for my late response, but this was not a blocker for us and I had to attend to other matters for a while.
Thanks to both of you for taking your time. I think we have another locale related issue coming up very soon and I will try to go with @bytrangle's suggestion there. I'll make sure to tag you both to see what you think.

**Comment by bytrangle** [comment]
@erezrokah I'm fine with your suggestion.

**Comment by bytrangle** [comment]
@demshy Do you mind if I work on the context API? I'm already working on it locally and it's still fresh in my mind. It's alright if you want to work on it.

**Comment by demshy** [comment]
@bytrangle of course, that would be great! I will try to delay our thing until you're done. 
I think we have something about translatable lists widget coming up, but I don't know the details yet.

**Comment by bplmp** [comment]
Was this fix deployed to a release? I'm running `netlify-cms 2.10.192` but I'm having issues with the i18n options in the relation widget. It is only showing the default language title in the select box, even when changing locale.

**Pull request merged**
