### PR TITLE
[wip] docs site css cleanup and prep for widget gallery

### PR DESCRIPTION
**Pull request by zebapy**
## work in progress

I'm opening this PR to test the waters with these changes. I understand a large css change like this could affect other branches in progress so I'm ok with closing this if necessary. Please let me know if something like this would be mergeable. 

- 🐛fix mobile issues with notification/sticky header (large gaps of vertical space currently)
- 📱deduplicate `MobileNav` and `DocsNav` so there's 1 component now for rendering the list of links
- reduce specificity of selectors making changes easier and selectors more single purpose focused
- avoid nested selectors
- clean up shared styles between docs, blog posts (like markdown content styles) which would be used on widget readmes next
- simplify site search input css
- remove some usage of same class names intended as modifier classes (hero.landing vs page.landing are two different uses for `landing` when a modifier like `hero hero-landing` is better)
- ⚛️move data queries into component files where data is required
  - [x] notifications
  - [x] widgets
  - [x] docs nav

This is a clean up effort in preparation for #1286 

## todo
- [ ] make sticky header work again since notifications bar is now part of header (easier than managing offsets and absolute placement for ~3 elements)
- [x] fix code highlight style in paragraphs
- [ ] consider renaming `grey` css variables to `gray` as the latter is the more common american english usage?

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 350a3e3996591beed60d1e37da21ca326d6f5111

https://deploy-preview-1707--netlify-cms-www.netlify.com

**Comment by zebapy** [comment]
@erquhart I'm guessing the reactions mean "This would be fine" 😄

**Comment by erquhart** [comment]
Yep, definitely! There's more to discuss around the community widgets section itself, but I don't expect that to impact this PR.

**Comment by zebapy** [comment]
@erquhart to be frank, the css of this site could really benefit from an overhaul and/or more atomic approach .. or dare I say css-in-js. Has there been interest in this?

**Comment by tech4him1** [comment]
@zebapy Why not just use the same CSS-in-JS system we are using for the CMS itself -- Emotion?

**Comment by zebapy** [comment]
@tech4him1 I hadn't even noticed, I barely look at the cms code haha. I'd be fine with converting to that probably. Just want buy-in. I think styled-system works on top of emotion too.

**Comment by erquhart** [comment]
Hey @zebapy, just wanted to see if this is still on your radar?

**Comment by zebapy** [comment]
Totally fallen off. I can try to at least wrap up this PR soon perhaps. I don't know if I'd get to the widget gallery after

**Comment by erquhart** [comment]
No problem! Just wanted to see if it was still moving or not.

**Comment by zebapy** [comment]
@ZoltanVeres feel free, I'm not sure I'll get back to this any time soon

**Comment by erquhart** [comment]
@ZoltanVeres I'd normally mark this as abandoned, but as you said it has some great improvements. Let me know if you're thinking of picking it up.

**Comment by ZoltanVeres** [comment]
@erquhart I'm gonna pick this up, i'll try to squeeze in some time in the end of this week. In any case i won't let this PR go to waste!

**Comment by zebapy** [comment]
I've done the questionable thing and started a different branch converting the site to use emotion for css. It includes some clean up that's in this PR already. Perhaps pause on making new changes to this for now and see if I can wrap up the other? Emotion/styled makes it much easier to maintain I'd say.

**Comment by ZoltanVeres** [comment]
@zebapy Oh, ok! Thanks for letting us know :P Can you reference that PR here you are working on? Let me know if you need any help or struggle with something, i don't much about emotion, but keen to learn! @erquhart  yeah, this can be then marked as inactive.

**Comment by zebapy** [comment]
@ZoltanVeres here's the PR https://github.com/netlify/netlify-cms/pull/2068 I should be able to wrap up most of it though. If I run into any issues, I'll let you know

**Pull request closed without merging**
