### PR TITLE
feat(widget-list): add hiding list content with minimize_collapsed option

### PR DESCRIPTION
**Pull request by hanneskuettner**
**Summary**
This adds the option to completely hide list content when the list widget itself is collapsed. 
If the option `minimize_collapsed` is set to `true` all list items are hidden rather then only collapsed when the list collapse toggle is used. 

This is a direct response to https://github.com/netlify/netlify-cms/pull/3606#issuecomment-613952382. 
Instead of completely changing the behavior of the `collapsed` option as suggested in https://github.com/netlify/netlify-cms/pull/3606#issuecomment-613977784 I added the `minimize_collapsed` option such that the change is not breaking and a list with just `collapsed: true` will still expand it's items. 

I feel like there are valid use cases for having a list expand it's items when the collapsed state is toggled., e.g. object with single items in them. I'm totally open for discussion on this one though. 

Right now the behavior is:
- `collapsed: true` & `minimize_collapsed: false`: collapse but don't hide list items and the list widget collapse button toggles the collapse state of all items (as before)
- `collapsed: true` & `minimize_collapsed: true`: when opening the list widget the items are shown, but remain collapsed; when collapsing the list widget all items are collapsed and hidden
- `collapsed: false` & `minimize_collapsed: false`: item are not collapsed  by default but can be collapsed using the collapse toggle on the list widget (as before)
- `collapsed: false` & `minimize_collapsed: true`:  items are expanded by default, but can be hidden when using the collapse toggle on the list widget

**Test plan**
Added `minimize_collapsed: true` to the nested list in the object in the list (that's a handful) in the kitchen sink collection.

image

### CODE REVIEW

**Comment by erquhart** [comment]
This makes a lot of sense, great approach @hanneskuettner!

**Comment by hanneskuettner** [comment]
@erezrokah I for sure think tests would make sense. Just wanted to get feedback on it I guess before investing unnecessary work in test. 

I'll have a go at it tomorrow.

**Comment by erezrokah** [comment]
FYI, I added some tests to the List widget https://github.com/netlify/netlify-cms/pull/3697.
Hopefully that would make it a bit easier to contribute to the widget (we have 3 open PRs for list widget related issues).

**Comment by hanneskuettner** [comment]
@erezrokah Awesome! Sorry other stuff has been keeping me busy. I'll give it a look tomorrow!

**Comment by erezrokah** [comment]
Sure, no worries (not trying to push anything, just trying to make it easier to contribute)

**Comment by erezrokah** [comment]
@hanneskuettner, I hope that's ok - I finalised the PR by adding some test (also got rid of the immutable list usage where I could).

**Comment by hanneskuettner** [comment]
@erezrokah that's awesome. Thank you so much.

**Pull request merged**
