### PR TITLE
docs: add docusaurus guide

### PR DESCRIPTION
**Pull request by garrison0**
**Summary**

Adding another guide for #2092 

I went for a "code along" style. Let me know if I should make any edits!

**Test plan**

```bash
cd website
yarn lint
yarn run v1.22.10
$ markdownlint 'content/docs/**/*.md'
✨  Done in 0.61s.
```

**Checklist**

Please add a `x` inside each checkbox:

- [ x ] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [ x ] Code is formatted via running `yarn format`.
- [ x ] Tests are passing via running `yarn test`.
- [ x ] The status checks are successful (continuous integration). Those can be seen below.

### CODE REVIEW

**Comment by talves** [comment]
Great job on putting this together @garrison0 . Looks good from first glance on preview.

At first, I was thinking we could use the `netlify cli` to create the site. I'll review that myself to see where the friction would be and might be easier the way you set it up here in the doc. That doesn't mean this should not go forward. I just feel it would be nice to see if `netlify dev` would help out a user experience. Could always be added later in a new issue.

**Comment by garrison0** [comment]
@talves Ya I agree, more streamlined that way. Just changed the `Publish your project` steps to use the CLI

**Comment by garrison0** [comment]
Should anything else be added or edited?

**Review by erezrokah — CHANGES_REQUESTED** [review]
Hi @garrison0, thank you for this guide and sorry for the very late review.

Our other guides follow a different structure, see the [Gatsby guide](https://www.netlifycms.org/docs/gatsby/) as an example.

Can we use the same structure so the guides are more or less consistent?

**Review by erezrokah — APPROVED** [review]
Thanks @garrison0 and @talves ❤️ 

I'm going to merge this as I think this is much better than the current status of not having any guide.
We can work on consistency with others guides in follow up PRs (maybe even change the other guides to use the Netlify CLI).

**Pull request merged**
