### PR TITLE
Fix/fix homepage hero videolink centering

### PR DESCRIPTION
**Pull request by ChrisBrownie55**
**- Summary**
Upon visiting the netlify cms website I noticed the play button on one of the videos was not centered. So I fixed this by setting the `line-height` to the height of the element.

My **motivation** for making this change is that when a person new to your site sees that the play button isn't centered it doesn't instill a sense of confidence, so I decided to fix that.

screenshot 2018-07-05 at 3 05 57 pm

**- Description for the changelog**

Added `line-height: 90px;` to `.hero-videolink`

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit f8b426f7db8523b1aa785db92ff22a7b009b619b

https://deploy-preview-1485--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit f8b426f7db8523b1aa785db92ff22a7b009b619b

https://deploy-preview-1485--netlify-cms-www.netlify.com

**Comment by ChrisBrownie55** [comment]
Why didn't the second check pass? I only added one line of CSS on the home page.

**Comment by ChrisBrownie55** [comment]
Okay, thank you @tech4him1, do you know how long does it usually take for a PR to be reviewed?

**Comment by tech4him1** [comment]
It varies a lot depending on the content of the PR, since there needs to be two reviews.

**Comment by ChrisBrownie55** [comment]
@tech4him1 Do you have any idea why it's lowering it to the bottom in Windows Chrome, because I'm using a Chromebook, and to me that's not exactly cross-browser so I'm unsure of what's going on.

**Comment by tech4him1** [comment]
@ChrisBrownie55 Actually, to me it looks un-centered in your screenshot. Either way, your screenshot looks the same as on my computer, so it's not a cross-browser issue. Obviously we just have a difference in how we look at it (😆), so I'll request some reviews from the rest of the maintainers here. Thank you!

**Comment by tech4him1** [comment]
@neutyp @Benaiah Can you check this out?

**Comment by ChrisBrownie55** [comment]
@tech4him1 the reason why it looks uncentered in the screenshot is because whomever wrote it, used padding to try to center it horizontally, they didn't fix the vertical. If I could find the `.html` file I would be able to fix it, so if you happen to know where that is hmu.

**Comment by ChrisBrownie55** [comment]
Nvm I found the html file, correct me if I'm wrong but it should be `/website/site/layouts/index.html`

**Comment by ChrisBrownie55** [comment]
Also, @tech4him1 How do you actually run the updated site, I've been just modifying the webpage with Chrome DevTools

**Comment by tech4him1** [comment]
> How do you actually run the updated site
See `@verythorough`'s comment with the deploy preview above: https://github.com/netlify/netlify-cms/pull/1485#issuecomment-402853924.

If you want to run it locally, I believe you can use `yarn start` in the `website` directory.

**Comment by ChrisBrownie55** [comment]
Nvm, I figured out how to get the server started, there is a bug in **postcss-colour-functions/index.js:92** that has been reported and pull request made like 28 days ago but still not accepted so I just changed it manually in mine so that it would run:

```js
if (val && val.indexOf && ...)
```

Now I'll try to center the button again.

**Comment by ChrisBrownie55** [comment]
I have centered it, sorry it took so long, here is a screenshot of it on a grid for proof of actual centering:

screenshot 2018-07-16 at 1 56 48 am

**Comment by talves** [comment]
@tech4him1 If this is an issue, maybe it should be handled in https://github.com/netlify/netlify-cms/pull/1369 since this looks like it will be the site going forward. What do you think?

I kinda like the button off center a little. It reminds me that we're all just human. 😜

**Comment by ChrisBrownie55** [comment]
@tech4him1  Is it looking good for you now?

**Comment by tech4him1** [comment]
@ChrisBrownie55 Sorry for my lack of response here, I've been busy on other projects.

I do agree with @talves that it should probably go into #1369 instead, unless you want to do it over again 😄. That PR is just about ready to merge.

> I kinda like the button off center a little. It reminds me that we're all just human. 😜

@talves I'm not too concerned about it either way, but if Chris has it ready, I don't see why we shouldn't take it.

**Comment by talves** [comment]
@tech4him1 I am ok with it either way also. Just wanted to make sure we did not carry over a needed change into the other PR

**Comment by ChrisBrownie55** [comment]
@tech4him1 @talves Why not merge both? If we merge this and then they rebase their branch it should reflect on #1369 when it gets merged, correct?

**Comment by erquhart** [comment]
I believe this is addressed in the new Gatsby site.

**Pull request closed without merging**
