### PR TITLE
Entry Editor Improvements

### PR DESCRIPTION
**Pull request by okonet**
This PR has gotten bigger. Here is the list of features I'm working on at:

* [x] Render markup-it with React elements
* [x] Upload images using drag'n'drop in Raw editor
* [x] Upload images using drag'n'drop also in visual editor (low-prio but should be easy)
* [x] Editor → Preview scroll sync
* [x] Preview → Editor scroll sync
* [ ] Scroll preview to the position of where I'm typing in editor
* [x] Hide the sidebar on the entry editor page. #104 
* [x] Better visual feedback on save. #101 
* [ ] Better syntax highlight for HTML. #105 

This is still WIP so please don't merge!

### CODE REVIEW

**Comment by okonet** [comment]
This is took a pretty much good shape already and I feel like it can be reviewed. cc @cassiozen @biilmann

**Comment by okonet** [comment]
I've implemented scroll sync for the preview. At the moment it works only in one direction — from editor to preview. Probably it should work both ways and I'll try it out later.

I've also added drag'n'drop image uploading to the visual editor.

**Comment by okonet** [comment]
@cassiozen I've a few questions to the image uploading process.

Right now with the following config (part): 

```yaml
backend:
  name: github
  repo: okonet/vegandollhouse.com # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "static/images" # Folder where user uploaded files should go
```

if I create an image with the `src` attribute set to `mediaProxy.public_path` (like you did here: https://github.com/netlify/netlify-cms/blob/master/src/components/Widgets/MarkdownControlElements/VisualEditor/index.js#L257) all my URL of images will contain `/static/image/`. See https://github.com/okonet/vegandollhouse.com/commit/031a8abdf2f2b6a80e09bd5afc28a2caa3efccf6 for example.

At the same time, all image's urls in the post are starting with `/images` and it is returning the 404 error with `/static` part in it.

I'm not sure if I'm doing something wrong or we have to handle 2 URLs separately: public path should be without `/static` and path on fs should be with it.

Can you gide me in a right direction please?

**Comment by okonet** [comment]
@cassiozen I'm also not sure if this is the good way of doing it (it does feel like a hack TBH): https://github.com/netlify/netlify-cms/pull/82/files#diff-c8dd3cecb71eb14b4f8cf9e6e9f5bed7R90

**Comment by cassiozen** [comment]
@okonet: On your first question: There is an additional config key available: "public_folder". 
If it doesn't find a public_folder, it assumes it's the same of media_folder. 

To try out, your updated sample config would look like this:
```yaml
backend:
  name: github
  repo: okonet/vegandollhouse.com # Path to your Github repository
  branch: master # Branch to update (master by default)

publish_mode: editorial_workflow

media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"
```

**Comment by cassiozen** [comment]
@okonet You mean the usage of a portal? It feels like a hack to me too, but it does allow for a lot of flexibility. I liked that you moved all portal related code to a separate file.

**Comment by okonet** [comment]
@cassiozen no, by hack I meant this code:

```js
applyTransform: (transform, file) => {
          const mediaProxy = new MediaProxy(file.name, file);
          const state = Plain.deserialize(`\n\n![${file.name}](${mediaProxy.public_path})\n\n`);
          props.onAddMedia(mediaProxy);
          return transform
            .insertFragment(state.get('document'));
}
```

In particular `const state = Plain.deserialize(`\n\n${file.name}\n\n`);` that is a hard coded string literal for adding images. I feel like it should go through the one component (`mediaproxy`?) but I'm not sure how to handle it the best way.

**Comment by cassiozen** [comment]
Oh, I see now. It does look "hacky" but it's not fragile and it's easy to understand.

Remember that the MediaProxy is also used in other widgets. I think it could be a good idea to make it go though MediaProxy now, but what will happen when the CMS is (hopefully) huge and has tons of widgets and other 10 formats besides markdown?

**Comment by okonet** [comment]
That's exactly my concern: we need widgets to be able to let the editor know how to represent them in different formats. Any direction here?

**Pull request merged**
