### PR TITLE
Remove cupofdata example

### PR DESCRIPTION
**Pull request by tomrutgers**
**Summary**

Solving https://github.com/netlify/netlify-cms/issues/1725

The Cup of Data example is not online anymore. The Gatsby version of the repo, which is still on github, is also falling behind. 

Alternatively I can remove the link from the table but otherwise leave the example intact.

**Test plan**

Ran website and the example data looks fine

**A picture of a cute animal (not mandatory but encouraged)**
e2ddf29dc77bbd842147cfb77039cd51

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 0c4049ff61b7fb4f2d9958324f283e62c6d70bc1

https://deploy-preview-1726--netlify-cms-www.netlify.com

**Comment by erquhart** [comment]
Let's hold off on this, their team said it'll be back up soon.

**Comment by talves** [comment]
I think we should give the cupofdata folks the option to add a redirect for the path to a demo, give a valid path or give them the option to remove the link and put in a PR when they are ready to have it added back. Commits are cheap.

**Comment by erquhart** [comment]
Then let's do it 👍

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 0c4049ff61b7fb4f2d9958324f283e62c6d70bc1

https://deploy-preview-1726--cms-demo.netlify.com

**Pull request merged**
