### PR TITLE
feat(netlify-cms-widget-markdown): add headings dropdown, new try

### PR DESCRIPTION
**Pull request by chrfritsch**
**Summary**
I took over the work from @zacharysierakowski and fixed the problem with the switching between Markdown and the visual editor.

**Test plan**

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by erquhart** [comment]
Doesn't seem to be working: https://deploy-preview-2879--cms-demo.netlify.com/#/collections/posts/new

**Comment by chrfritsch** [comment]
Sorry. Now it should work

**Comment by erquhart** [comment]
Working! So one more issue - developers can currently specify which headings to allow (although limited to levels 1 and 2), which was a requested enhancement, and this removes that. Instead of swapping `heading-one` and `heading-two` for `headings` in the buttons config, we should allow all six to be configured. Otherwise it's a bit of a regression.

**Comment by chrfritsch** [comment]
Thanks @erquhart for the review. I implemented your suggestion

**Comment by erquhart** [comment]
Awesome, thanks for bringing this across the finish line @chrfritsch!

**Pull request merged**
