### PR TITLE
Redirect to first collection when a collection doesn't exist

### LINKED ISSUE #2155: URL to non-existent collection breaks the app
**Describe the bug**

Entering a URL to a non-existent CMS collection breaks the app. This could happen on localhost when a collection no longer exists for some reason and the URL autocompletes.

**To Reproduce**

https://cms-demo.netlify.com/#/collections/non-existent-collection

**Expected behavior**

Return to default screen (first available collection)

### PR DESCRIPTION
**Pull request by Dammmien**
**Summary**

Fixes #2155

Redirect to first collection when a collection doesn't exist.

**Test plan**

- Go to: http://localhost:8080/#/collections/non-existent-collection
- You should be redirected to: http://localhost:8080/#/collections/posts

### CODE REVIEW

**Comment by erquhart** [comment]
We should be able to handle this in the main router: https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-core/src/components/App/App.js#L180

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Dammmien** [comment]
@erquhart ok get it, I'll change that 👍!

**Comment by Dammmien** [comment]
@erquhart I moved it to the main router.

**Comment by erquhart** [comment]
Awesome, looks great! Just needs a formatting fix (run `yarn lint` locally) and it's good to go.

**Comment by erquhart** [comment]
Hmm still failing, is it passing locally?

**Comment by Dammmien** [comment]
Locally, there are a lot of warnings in files I didn't modify, but no errors:

Capture d’écran 2019-03-20 à 10 45 49

**Comment by erquhart** [comment]
Just needed to run `yarn format` and commit the resulting fix. Will merge once CI passes 👍

**Pull request merged**
