### PR TITLE
WIP: Switch slugifier to `urlize`

### LINKED ISSUE #607: Switch to a smaller slugifier.
Currently, we use the `slug` module for creating URL slugs from titles. The problem is that `slug` bundles an entire Unicode lookup table, and that gets bundled into our distributable. it currently accounts for 30.5% of our bundle size. This should probably be changed to something a little lighter weight.

Related to #328.

### PR DESCRIPTION
**Pull request by tech4him1**
**- Summary**

Fixes #607.

Reference: https://github.com/gohugoio/hugo/blob/492327368848bcf21cfd23d5490bc47b6ea44897/helpers/url.go#L100

**- Test plan**

Tests still need added.

**- Description for the changelog**

Switch from `slug` to `urlize`.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by tech4him1** [comment]
@biilmann Would you be willing to review the changes that I made to the URLize method and make sure they are all consistent with what you had originally made?

**Comment by dopry** [comment]
So how is slugify called? Will this change any existing slugs or URLs for existing users?

**Comment by tech4him1** [comment]
@dopry No, it will only change the library we use to create new slugs (see linked issue for reason).

**Comment by tech4him1** [comment]
Closed after Gitter chat: https://gitter.im/netlify/NetlifyCMS?at=59ce87ae32fc8b7e4056db1b
We are going to keep all UTF-8 chars in the filename, and the site generator can handle slug conversion.

**Pull request closed without merging**
