### PR TITLE
Add trailing newline to JSON files

### LINKED ISSUE #1382: JSON files are saved with no newline at the end of file
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Netlify CMS saves JSON data **without** a newline at the end of the file.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Configure a collection type with `format: "json"` and `extension: "json"`, then create and publish a new post in the Dashboard.

**- What is the expected behavior?**
JSON file should created **with** newline at the end of the file.

### PR DESCRIPTION
**Pull request by zurawiki**
**- Summary**

It's a convention to end files with a trailing newlines character. Even GitHub complains when files don't end in a new line. This change will remove that error from rendering in the GitHub web UI.

screen shot 2018-04-20 at 2 56 32p 1

Closes #1382.

**- Test plan**

This change will not affect parsing in the `fromFile` function. JSON parsing works with trailing whitespace.
```js
JSON.parse("{}", 2, null); // this works
JSON.parse("{}\n", 2, null); // and so does this
```

`yarn test` passed
`yarn lint` ran into errors however. The errors occured in files I did not edit.

**- Description for the changelog**

JSON formatted files now include a trailing new line.

**- A picture of a cute animal (not mandatory but encouraged)**

giphy 1

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 3c6a16fcdf58b693b62f4eb80c615bce3c6e3747

https://deploy-preview-1302--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 3c6a16fcdf58b693b62f4eb80c615bce3c6e3747

https://deploy-preview-1302--cms-demo.netlify.com

**Comment by zurawiki** [comment]
Bump. Any idea on when this PR can be merged in?

**Comment by erquhart** [comment]
@tech4him1 any reservations on this one?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Benaiah** [comment]
This makes sense to me - don’t see any reason not to merge unless someone can think of a way this would affect existing installations.

**Comment by tech4him1** [comment]
I don't see any problem with it. I would check files with JSON frontmatter, though -- the extra newline may get added to the body text.

**Comment by Benaiah** [comment]
@tech4him1 agreed. @zurawiki this block specifically probably needs to be modified to check for and trim a closing bracket _and_ the newly-added newline: https://github.com/zurawiki/netlify-cms/blob/79d3afe5065d4472f6c191375d0528f5fb5879be/src/formats/frontmatter.js#L23-L31

**Comment by erquhart** [comment]
@zurawiki the comment by @Benaiah should be addressed before we can merge.

**Comment by zurawiki** [comment]
@Benaiah I updated the PR to include your suggestion

**Comment by erquhart** [comment]
Just noticing that this adds newlines at the format level instead of to files. No need for trailing newlines in frontmatter.

@zurawiki any reason not to add a trailing newline at the file level, regardless of type?

**Comment by erquhart** [comment]
Closing as stale.

**Pull request closed without merging**
