### PR TITLE
Support extensions with multiple parts (i.e. `en.md`)

### LINKED ISSUE #877: Entries with complex extensions do not appear in collection view
**- Do you want to request a *feature* or report a *bug*?**

bug hunt 👾

**- What is the current behavior?**

Entries that have a complex extension — eg: `html.md` — can be created in the CMS, but do not appear in the collection view.

**- If the current behavior is a bug, please provide the steps to reproduce.**

Set `extension: "html.md"` and `format: frontmatter`. In the CMS, create a new entry in that collection. Entry is committed successfully, with the custom extension. Entry does not appear in the collection view.

**- What is the expected behavior?**

Entry should appear in the collection view.

**- Please mention your CMS, node.js, and operating system version.**

Netlify CMS version 0.7.6, deployed to Netlify

### PR DESCRIPTION
**Pull request by tech4him1**
**- Summary**

Fixes #877. See discussion there for context.

**- Test plan**

Manually tested. Is it worth mocking the API for `listFiles` to test this?

**- Description for the changelog**

Support extensions with multiple parts (i.e. `en.md`).
Clean leading periods from extensions.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit bbb512cb1c81082f9be17fa4dbe8f8a8343e2e6f

https://deploy-preview-1123--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit bbb512cb1c81082f9be17fa4dbe8f8a8343e2e6f

https://deploy-preview-1123--cms-demo.netlify.com

**Comment by tech4him1** [comment]
@talves @erquhart @Benaiah The user will still be required to manually specify a format here, do you think that's necessary, or should we grab the last part of the extension, and use that to infer the format?

**Comment by Benaiah** [comment]
@tech4him1 let's do the minimal change to fix #877 and handle inference in a new issue/PR.

**Comment by talves** [comment]
I agree with @Benaiah to get this moving forward, since it is a working incremental

**Comment by tech4him1** [comment]
There seems to be a bug when using the GitHub backend -- if you use `html.md` as the extension, `html` turns into part of the slug instead of the extension.

**Comment by tech4him1** [comment]
@Benaiah @talves Pushing a fix now.

**Comment by erquhart** [comment]
@tech4him1 I tested this locally and it works great 🍻 

I do think one bit of sanitization is in order, though - when trying this, I assumed the extension should include a dot, so I set ".en.md" in the config, which led to "my-file..en.md". Which actually didn't break anything, but we should at least strip any dots from the beginning of the user-supplied extension.

Once that's fixed, LGTM.

**Comment by ryantownsend** [comment]
Also validated this myself, including deploying to Netlify itself. Would be great to see this merged.

**Comment by tech4him1** [comment]
@erquhart Updated.

**Pull request merged**
