### PR TITLE
Add blog to docs site

### PR DESCRIPTION
**Pull request by verythorough**
### Summary
We wanted to be able to publish a blog post to announce GitLab support (expected Monday), so I put together some quick template handling for a blog section on the netlifycms.org website. This is definitely the quick-and-dirty version, intended to be a very short-term stopgap until the entire site is converted from Hugo to Gatsby with #1369 (thanks @zebapy!). The code will inevitably be different in Gatsby, and the design could definitely use some love!

Because we don't want to release the blog section until we have at least one blog post, this PR is marked WIP until the first post is added to this PR (thanks @yourfrienderin!). The CMS config is also temporarily altered to commit to this branch instead of master.

### Test plan
You can check the preview at https://add-blog--netlify-cms-www.netlify.com/blog/

The permalinks to individual posts are absolute links to the production site (default Hugo behavior), so they break in the preview. You can preview the sample posts here:
- https://add-blog--netlify-cms-www.netlify.com/blog/2018/05/first-sample-post/
- https://add-blog--netlify-cms-www.netlify.com/blog/2018/05/second-sample-post/

If you have push access to the repo, you can log in to the CMS at - https://add-blog--netlify-cms-www.netlify.com/admin. It's temporarily set to commit directly to this branch.

### Tasks remaining before merge
- [x] Add GitLab announcement blog post
- [x] Remove sample blog posts
- [x] Change CMS config to production settings: set branch to master and turn editorial workflow on

### A picture of a cute animal (not mandatory but encouraged)
sleepytoots
My dog Petunia, sleeping next to me right now. ❤️

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit a24ec7f2e23c70eea6dda59d2de4e73057e4af1a

https://deploy-preview-1419--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit a24ec7f2e23c70eea6dda59d2de4e73057e4af1a

https://deploy-preview-1419--netlify-cms-www.netlify.com

**Comment by zebapy** [comment]
@verythorough should I add blog functionality to #1369 ?

**Comment by verythorough** [comment]
Awesome, thank you @zebapy!

**Comment by erquhart** [comment]
If we derive the post route based on frontmatter, that can be easily changed, and we don't want that. If the filename is used for route creation and the frontmatter isn't consulted, that feels safer, less chance of url's changing unintentionally and negative SEO as a result.

@verythorough thoughts?

**Comment by zebapy** [comment]
I'd be happy to leave what I have in place which creates the url from the date in file name. Since netlify cms sets that date based on creation time, that would work, no? Of course people can still change file names so seems like the same problem

**Comment by erquhart** [comment]
Same problem, but you can't change the filename from within the CMS, so it's a bit safer is all.

**Comment by verythorough** [comment]
I think it's nice to have the date in the filename when you're browsing the files in the repo. However, like y'all, I think the source of truth should be the date field in the frontmatter. We can set the CMS config so that it pulls the date into the filename when saving.

When setting up the permalink template for blog posts, I copy-pasted the sample config in the Hugo website, then noticed that it doesn't include the day in the path - in other words, `/blog/{year}/{month}/{slug}`. I realized this is actually really convenient, because if a post is accidentally published on the wrong day, then fixed, you don't have to worry about making a redirect because the path changed. (Case in point: I've just realized we need to do this for the current blog! I'm glad that when I fix the date, it won't change the path. 😁 )

Extending that thought, I wonder if it makes sense to exclude the day from the filename, too. It's even _more_ common for a post date to change multiple times before publishing, and it's a annoying that this changes the filename every time. To that end, I'm thinking we change the `slug` field for the blog collection in the CMS config to `{{year}}-{{month}}-{{slug}}`.

**Comment by erquhart** [comment]
I suppose it goes both ways, there's convenience to changing the date based on a field in the editor. My concern isn't prepublishing, though, it's post-publishing. If someone changes the date after publishing, do they know it will change the url? It's implicit, and could lead to a link juice loss. Ideally the CMS would handle this more robustly so we could have the best of both worlds.

I'm alright with pulling the date from the frontmatter for our purposes here.

**Pull request merged**
