### PR TITLE
feat(netlify-cms-core)  add slug customization support

### LINKED ISSUE #1164: Prevent overwriting existing file
**- Do you want to request a *feature* or report a *bug*?**
BUG

**- What is the current behavior?**
When I add a file with the same title as an existing one and my slug equals title, the existing file is overwritten.

**- If the current behavior is a bug, please provide the steps to reproduce.**
make sure your slug equals title. add a file, choose a title that is already used by another file, save.
you have overwritten the existing file 

**- What is the expected behavior?**
- either: 
a new file is created (i.e. with counter to filename)
- or:
a warning that the file cannot be saved as it needs a unique title

Less urgent if #1069 were implemented.

### PR DESCRIPTION
**Pull request by barthc**
**Summary**
Closes   #1164  #445 

Picks up where #1239 left off, but instead of throwing an error for duplicate slug, it tries to generate a unique slug by append a number just like the way WordPress does it. For example assuming we already have a slug entry `title` and a sanitize_replacement option value as `-` trying to create  another entry with slug string `title` would generate a slug `title-1` , `title-2` and so on.

To enable slug customization, add a config collection setting `slug_field` with value pointing to the name of the widget field preferrable a  `string` widget. A couple of things to note regarding the slug field behaviour. On new entry, once the identifier field looses focus, if the slug field is blank, the normal automatic slug string is generated and set as value of the slug field. Also when the slug field looses focus, the input value is sanitized immediately and value updated. The slug field value is not saved in frontmatter.
So if there is a slug change for any published or unpublished entry, a new entry is created using the new slug and the old slug entry is deleted.

Tested changes with the `test-repo`, ` github`,`gitlab` and `bitbucket`  backend.

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit b74ef1070df25e65e28a43bb6009116585266f80

https://deploy-preview-1931--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit b74ef1070df25e65e28a43bb6009116585266f80

https://deploy-preview-1931--cms-demo.netlify.com

**Comment by barthc** [comment]
@erquhart  Could you please take a look again, pushed some updates.

> is that the identifier (title) field only updates the slug field during the initial focus. So if I enter a title, blur, then edit the title a little more, the edits aren't reflected in the slug.

The idea is to only sync the slug field with the `identifier_field` only if it's empty, incase the user would like to used something different.

**Comment by erquhart** [comment]
That makes sense if the identifier field is not empty on load. If it's empty on load, though, any edits between load and save should be reflected in the slug.

**Comment by barthc** [comment]
> That makes sense if the identifier field is not empty on load. If it's empty on load, though, any edits between load and save should be reflected in the slug.

Yup, I believe that's the behavior of the slug field at the moment. Try creating new entry on the demo.

**Comment by barthc** [comment]
So basically for new entry, if the user has the slug field filled out first before the `identifier_field` we respect the value, or if the user fills out the `identifier_field` first  the `slug_field` is synced immediately, and then incase the user modifies the slug field later on, any further changes to `identifer_field` is not reflected. As I said the idea is to present the user with the auto generated slug first, the user can choose to go with those or modify. I just think it is user friendly this way.

**Comment by erezrokah** [comment]
Closing this as stale, I think we can re-visit in the future as use this work as reference.

**Pull request closed without merging**
