### PR TITLE
Fixes field config usage with List widget.

### LINKED ISSUE #1139: Select widget inside List widget crashing
**Bug**

**What is the current behavior?**

I've got a List widget with a Select widget as the field:

```yaml
- label: "Tags"
 name: "tags"
 widget: "list"
 field:
   - label: "Tag"
     name: "tag"
     widget: "select"
     options: [
       '11 Plus','A-Level Results','API','Accounting','Analytics','Business Management','CRM','Compare','Edtech',
       'Education','Exam','Features','Grammar Schools','Internship','Language Learning',
       'Managing a tutoring agency','Marketing','Mobile','National Tutoring Conference','Newsletter',
       'Online Tutoring','Open Source','Oxbridge Admissions','Recruitment','SEO','SaaS','Sales',
       'Small Business','Small business','Starting a business','Startup','Stripe','Teaching',
       'Technology','Testimonial','TutorCruncher','Tutoring','User Experience','VAT'
     ]
```
It renders like so:

image

Which I presume is wrong? The standard drop down renders properly when not in a List widget.

The field that should be a Select here renders as a text field, and when I input two letters (or add one and delete one), I get an error in the console (in `ListControl.js:156`)

```js
Uncaught TypeError: t.getObjectValue(...).set is not a function
    at ListControl.js:156
    at onChange (EditorControl.js:68)
    at onChange (StringControl.js:30)
    at Object.s (react-dom.production.min.js:25)
    at Object.invokeGuardedCallback (react-dom.production.min.js:24)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.production.min.js:24)
    at p (react-dom.production.min.js:29)
    at v (react-dom.production.min.js:31)
    at y (react-dom.production.min.js:31)
    at Array.forEach (<anonymous>)
```

I'm using Jekyll, Netlify CMS version 1.2.2 and I've tried Chrome and Firefox on Ubuntu and Windows.

I seem unable to find an example of this on someone's site working, so if anyone can point me towards that I'd be happy to take a look.

### PR DESCRIPTION
**Pull request by brianlmacdonald**
Closes #1139. The original issue had two problems that I have found. The first was how the config.yml responds to `field`.

When adding in `fields` for a `list` widget as demonstrated under the label `List`, it renders correctly.

screen shot 2018-05-30 at 9 38 07 am

screen shot 2018-05-30 at 9 36 55 am

But when we use `field` instead, and indent with a dash, as we would with `fields`, 

screen shot 2018-05-30 at 11 58 52 am

this happens:
screen shot 2018-05-30 at 9 42 12 am

It doesn't render the select properly, and we get a whole console full of errors.

screen shot 2018-05-30 at 9 43 33 am

This error pointed to `handleChangeFor`.

```
  handleChangeFor(index) {
    return (fieldName, newValue, newMetadata) => {
      const { value, metadata, onChange, field } = this.props;
      const collectionName = field.get('name');
      const newObjectValue = this.getObjectValue(index).set(fieldName, newValue);
      const parsedValue = (this.valueType === valueTypes.SINGLE) ? newObjectValue.first() : newObjectValue;
      const parsedMetadata = {
        [collectionName]: Object.assign(metadata ? metadata.toJS() : {}, newMetadata ? newMetadata[collectionName] : {}),
      };
      onChange(value.set(index, parsedValue), parsedMetadata);
    };
  }
```
The handling of `newObjectValue` kept throwing because `getObjectValue` wasn't returning a `Map` like it was expecting, it was returning a `string` from the `select` widget. The `parsedValue` step was also expecting a `List`, but it was no longer becoming a `List`.

Having `newObjectValue` check first if it was `valueTypes.MULTIPLE` before using `getObjectValue`, and if it was a `valueTypes.SINGLE` then redirecting it to `newValue`, solved this problem. I removed the `parsedValue` step, since `newObjectValue` is no longer a `List`, and passed it to on change where the newValue was stored in a list.

That and using `field`'s object in `config` on the same line made the difference.

screen shot 2018-05-30 at 12 05 40 pm

screen shot 2018-05-30 at 12 05 17 pm

The preview pane issue required special parsing for `field` which I added in.

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 7f1368b91bacd890a61e0c1b041cb0fa41c753c0

https://deploy-preview-1395--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 7f1368b91bacd890a61e0c1b041cb0fa41c753c0

https://deploy-preview-1395--cms-demo.netlify.com

**Comment by erquhart** [comment]
Everything is working and has the proper appearance, but I'm concerned about our use of the item's index in the key. Can't tell if it's an issue or not, but I'm guessing we need an actual unique key instead.

**Comment by brianlmacdonald** [comment]
@erquhart I can switch it out for a unique key if you'd like.

**Comment by erquhart** [comment]
That would be awesome @brianlmacdonald, thank you!

**Comment by erquhart** [comment]
Just realized the unique key thing only affects the preview pane, so not an issue as the preview pane components won't ever change order dynamically like they do in the control pane.

**Pull request merged**
