### PR TITLE
docs: add gatsby v2 note, starter icons

### PR DESCRIPTION
**Pull request by erquhart**
Our Gatsby starter needs Netlify CMS 2.x, and that just won't work with Gatsby v1 for some reason. We'll be bumping the starter to Gatsby v2 beta, so I added a note to that effect in the docs. I can't think of a better approach.

While I was there, I noticed we didn't have icons for the SSG's, so I added those as well.

screen shot 2018-09-07 at 12 32 02 pm

Preview: https://deploy-preview-1730--netlify-cms-www.netlify.com/docs/start-with-a-template/

Will probably merge this before folks get around to reviewing, but please open an issue or comment in Gitter if you feel something here should be done differently.

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit ce3bfb6bc305fd24b9042fd621bf518d0a55773a

https://deploy-preview-1730--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit ce3bfb6bc305fd24b9042fd621bf518d0a55773a

https://deploy-preview-1730--cms-demo.netlify.com

**Comment by tomrutgers** [comment]
Nice touch with the icons! LGTM

**Comment by erquhart** [comment]
Awesome, thank you for reviewing!

**Pull request merged**
