### PR TITLE
Allow using subfields as identifier field

### LINKED ISSUE #2417: Allow using sub-fields of Object fields as identifier_field and slug
**Is your feature request related to a problem? Please describe.**

I have the following field structure:

```yaml
      - label: English
        name: en
        widget: object
        fields:
          - {label: Title , name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - label: Spanish
        name: es
        widget: object
        fields:
          - {label: Title , name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
```

I'd like to use `en.title` as the identifier_field (and therefore as the `{{slug}}`) but doing so breaks publishing (it loads forever and in the JS console I see an error saying that I need a valid `title` field or a valid field name specified in `identifier_field`.

Here's the full collection definition I was trying to use:

```yaml
  - name: "posts"
    identifier_field: "en.title"
    label: "Posts"
    label_singular: "Post"
    folder: "src/pages/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: English
        name: en
        widget: object
        fields:
          - {label: Title , name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - label: Spanish
        name: es
        widget: object
        fields:
          - {label: Title , name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
```

**Describe the solution you'd like**

I'd like to use sub-fields of Object fields as the `identifier_field` so that slugs can be based on them.

**Describe alternatives you've considered**

I tried setting `slug: "{{en.title}}"` and that didn't work either.

As a temporary workaround, I ended up just creating a standalone "Path" field which allows manual setting of the path, so it isn't automatically generated at all.

### PR DESCRIPTION
**Pull request by melbourne2991**
Closes #2417
 
**Summary**
Details covered in the original issue. 

**Test plan**
Added unit tests for affected components.

### CODE REVIEW

**Comment by Regaez** [comment]
This is looking good! Any chance you could extend this PR as mentioned in #2417 to allow the `summary` to use nested fields, as well?

From my own investigations into the issue, it looks like you'd need to change it in a couple of places:

https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-core/src/lib/stringTemplate.js#L26-L32

https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-core/src/lib/stringTemplate.js#L68

**Comment by melbourne2991** [comment]
@Regaez done!

**Comment by Regaez** [comment]
Awesome! Thanks a lot!

**Comment by toobulkeh** [comment]
👍

**Comment by toobulkeh** [comment]
@melbourne2991 - any chance we can get the conflicts resolved so it can be reviewed and merged? Thanks so much for your work!

**Comment by erquhart** [comment]
We'll revisit this soon 👍

**Comment by toobulkeh** [comment]
Happy holidays gents! We'd still love to see this as it really simplifies our GraphQL partials around metadata! Thanks

**Comment by erezrokah** [comment]
Replaced by https://github.com/netlify/netlify-cms/pull/3121

**Pull request closed without merging**
