### PR TITLE
Fixed two broken links.

### PR DESCRIPTION
**Pull request by kayceeingram**
Fixed two links. Hope this helps! Great job on Netlify by the way!

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 2a5f44b02da668f1171f004661a6c8986fa591cf

https://deploy-preview-1579--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 2a5f44b02da668f1171f004661a6c8986fa591cf

https://deploy-preview-1579--cms-demo.netlify.com

**Comment by tech4him1** [comment]
Thank you @kayceeingram!

**Comment by kayceeingram** [comment]
No problem!

**Pull request merged**
