### PR TITLE
Update Docs: Intro “start-with-a-template”

### PR DESCRIPTION
**Pull request by Knogobert**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by Knogobert** [comment]
And here's my contribution of a cute kitten

kit

**Review by erezrokah — CHANGES_REQUESTED** [review]
Thanks @Knogobert, the `Nuxt` logo is broken, you might need to add it to the repo as well. See https://deploy-preview-4286--netlify-cms-www.netlify.app/docs/start-with-a-template/
Will review the repo itself once I'm available later on this week.

**Comment by Knogobert** [comment]
Yeah I can't really grasp why it's not linked correctly. I uploaded it in the Netlify CMS at the same point as I edited the docs.

nuxt-netlify-cms-media

So I tried adding it to `/public/img`, the same place as another PR added its `nextjs.svg`, then I realized it is gitignored.
Then added it to `/src/img`, which I thought would work. Though there seems to be some sort of build step that converts the `` into a cloudfront url: ``.

How do I go about uploading [the logo](https://nuxtjs.org/design)?

**Comment by Knogobert** [comment]
Thanks for helping out finding the right place for it!

**Comment by erezrokah** [comment]
> Thanks for helping out finding the right place for it!

Sure thing, I still need go over the project itself though. Hopefully will to to it by next week

**Comment by erezrokah** [comment]
Sorry for the delay @Knogobert. This looks great but can we make Netlify LFS opt it? At the moment using the deploy button results in a broken media library:
image

Also, if you're passing `stack=cms` enabling `git-gateway` and `identity` is not required (see https://github.com/Knogobert/ntn-boilerplate#-getting-started)

**Comment by Knogobert** [comment]
No worries, I'm not stressed!

Yeah, I am using Netlify LFS on my installation. But maybe it's not setting it up/documented how to correctly yet. Good catch though, I'll look into it soon 😃 Any pointers are appreciated! 

I must've forgotten to update the documentation after adding the `stack=cms` to the "Deploy to Netlify"-button. I'll definitely update the documentation to reflect that better now. Thanks!!

**Comment by Knogobert** [comment]
Thanks for those, I updated the documentation to be more clear about LFS and Netlify LM and removed info that `stack=cms` deprecates. It feels a lot clearer and to the point now.

I didn't upload the boilerplates `.lfsconfig` though, as I feel like that would be more confusing than helping for people that clone the repo. Check the updated steps in https://github.com/Knogobert/ntn-boilerplate#-getting-started and https://github.com/Knogobert/ntn-boilerplate#troubleshooting where I mostly changed the text.

**Review by erezrokah — CHANGES_REQUESTED** [review]
Thank you again for following up with these changes @Knogobert.
`stack=cms` will also set Identity to `invite only` and send an email with an invite, so I believe the second part here:
https://github.com/Knogobert/ntn-boilerplate#-getting-started
is not required.

Also, I think I wasn't clear about Large Media. The `start with a template` buttons should have everything working out of the box after you click the button.
Since this is currently not possible with Large Media (an additional configuration is needed) I think we have 2 options:
1. Have the files here as regular images files:
https://github.com/Knogobert/ntn-boilerplate/tree/master/static/img
so the media library will work out of the box.
2. Move this from `start with a template` to examples:
https://www.netlifycms.org/docs/examples/

WDYT?

**Comment by Knogobert** [comment]
Thank you for being thorough! Great input!
Now I understand more what you are aiming for in those parts of the docs, you want it to be a quick easy automated setup. And I fully agree for this repo to become that. 

I have now updated the docs to become more tailored to that. I actually took a chunk of https://github.com/netlify-templates/one-click-hugo-cms to help me out in what you might be looking for.

The repo is now not dependant on being coupled with git lfs or Netlify LM from setup. It is a completely optional step, that now lets the user get their media library like this:

Screen Shot 2020-10-17 at 18 06 02

Perhaps the site also should be added to https://www.netlifycms.org/docs/examples/ for readers to easily find it?

**Comment by Knogobert** [comment]
I tried `git push --force-with-lease` on "cms/Knogobert/netlify-cms/docs_intro/start-with-a-template" but I get rejection errors. I guess I can't alter the history as I'm used to. So I can't resolve the conflict really.

Anyway, I wanted to add this line to `website/content/docs/examples.md:27`

```
[Nuxt, Tailwind & NetlifyCMS Boilerplate](https://ntn-boilerplate.netlify.app/) | Vue, Nuxt | demo | [Knogobert/ntn-boilerplate](https://github.com/Knogobert/ntn-boilerplate) | [read me](https://github.com/Knogobert/ntn-boilerplate#readme)
```

Maybe you can do that before an eventual merge for me?

**Comment by erezrokah** [comment]
> Now I understand more what you are aiming for in those parts of the docs, you want it to be a quick easy automated setup. And I fully agree for this repo to become that.

Sorry for not being clear about it before. Thank you for following up with the changes.

> Maybe you can do that before an eventual merge for me?

Added another commit for that

**Comment by Knogobert** [comment]
Thanks!

**Pull request merged**
