### PR TITLE
WIP: Accept absolute paths for public_folder.

### PR DESCRIPTION
**Pull request by tech4him1**
**- Summary**

Allow setting the `public_folder` to an absolute path. This does not change the support for relative paths.

**- Test plan**

Manually tested. I can add tests before merge.

**- Description for the changelog**

Allow absolute paths for `public_folder`.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 2911ba6764806836cf202eb087d678410891c31d

https://deploy-preview-1257--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 2911ba6764806836cf202eb087d678410891c31d

https://deploy-preview-1257--netlify-cms-www.netlify.com

**Comment by Benaiah** [comment]
@ahoward can you test this to make sure it resolves the use case you described in Gitter? (using an absolute path to have image previews and markdown images loaded from an arbitary URL root)

**Comment by ahoward** [comment]
#WOOT

**Comment by tech4him1** [comment]
@erquhart @talves Do you guys have any problem with the general idea of this? I don't see any problems, but I don't want to rush it if you have reservations.

**Comment by erquhart** [comment]
I still feel a bit gun shy. The tests help, but I'm not sure we're seeing all of what this change affects.

For example, I'm not sure what happens if someone is prepending a slash to their `media_folder`, which can affect the `path` property of `AssetProxy`: https://github.com/netlify/netlify-cms/blob/db292abe03f27d76196eab1b4e4340448d97a059/src/valueObjects/AssetProxy.js#L17

**Comment by Benaiah** [comment]
@erquhart yeah, I think we should separate the function into one for filepaths, used to traverse the source files (`media_folder`) and a different resolver for URLs. Making the distinction between the two more clear, especially in configuration, would clear up the code and make it easier to understand what we're using different values for.

**Comment by tech4him1** [comment]
> I'm still not quite there yet. I'm 100% with the _goal_, and the tests help, but I'm not sure we're seeing all of what this change affects.

@erquhart I completely agree.

**Comment by erquhart** [comment]
@tech4him1 closing as stale, please re-open if it's still on the table.

**Comment by erquhart** [comment]
@tech4him1 migrated to #1668.

**Pull request closed without merging**
