### PR TITLE
Fixes handling of field in list widget.

### LINKED ISSUE #1139: Select widget inside List widget crashing
**Bug**

**What is the current behavior?**

I've got a List widget with a Select widget as the field:

```yaml
- label: "Tags"
 name: "tags"
 widget: "list"
 field:
   - label: "Tag"
     name: "tag"
     widget: "select"
     options: [
       '11 Plus','A-Level Results','API','Accounting','Analytics','Business Management','CRM','Compare','Edtech',
       'Education','Exam','Features','Grammar Schools','Internship','Language Learning',
       'Managing a tutoring agency','Marketing','Mobile','National Tutoring Conference','Newsletter',
       'Online Tutoring','Open Source','Oxbridge Admissions','Recruitment','SEO','SaaS','Sales',
       'Small Business','Small business','Starting a business','Startup','Stripe','Teaching',
       'Technology','Testimonial','TutorCruncher','Tutoring','User Experience','VAT'
     ]
```
It renders like so:

image

Which I presume is wrong? The standard drop down renders properly when not in a List widget.

The field that should be a Select here renders as a text field, and when I input two letters (or add one and delete one), I get an error in the console (in `ListControl.js:156`)

```js
Uncaught TypeError: t.getObjectValue(...).set is not a function
    at ListControl.js:156
    at onChange (EditorControl.js:68)
    at onChange (StringControl.js:30)
    at Object.s (react-dom.production.min.js:25)
    at Object.invokeGuardedCallback (react-dom.production.min.js:24)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.production.min.js:24)
    at p (react-dom.production.min.js:29)
    at v (react-dom.production.min.js:31)
    at y (react-dom.production.min.js:31)
    at Array.forEach (<anonymous>)
```

I'm using Jekyll, Netlify CMS version 1.2.2 and I've tried Chrome and Firefox on Ubuntu and Windows.

I seem unable to find an example of this on someone's site working, so if anyone can point me towards that I'd be happy to take a look.

### PR DESCRIPTION
**Pull request by brianlmacdonald**
**- Summary**

Closes #1139.  The `parsedValue` created in `handleChangeFor` in `ListControl.js` was causing problems as it was a string being treated like a Map. The parse value step, when removed, stopped this from happening.

It's also interesting to note that field in the `config.yml` file would break the widget if `field` was followed by a `-` on a new line. But when field was given an object of the single field, it worked.

screen shot 2018-05-29 at 1 31 13 pm

screen shot 2018-05-29 at 1 31 40 pm

Then to address the preview pane issues, I made sure to check for `field.get('field')` in `ObjectPreview.js`, and then added a special `field` handler in `EditPreviewPaine.js`

**- Test plan**

The changes worked when I ran the app. Preview worked too.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 2c328cdc6ded78cb078792eecd06078f2fb90e39

https://deploy-preview-1373--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 2c328cdc6ded78cb078792eecd06078f2fb90e39

https://deploy-preview-1373--cms-demo.netlify.com

**Comment by erquhart** [comment]
@brianlmacdonald no go on this?

**Comment by brianlmacdonald** [comment]
It needs a small tweak, and I’m away for the weekend. I will make the changes it needs when I’m back and reopen.

**Comment by erquhart** [comment]
Okay, sounds good.

**Comment by brianlmacdonald** [comment]
I need to rebase this. Just a second.

**Comment by tech4him1** [comment]
@brianlmacdonald Problems?

**Pull request closed without merging**
