### PR TITLE
#2984 - Responsive fixes - Floating action button

### PR DESCRIPTION
**Pull request by alexbuiltit**
**Summary**

The work I have completed contributes to issue #2984, more specifically the Quick add section of that issue. 

I have introduced a new Floating Action Button component for screen sizes less than 768, this is the first in a handful of tasks required to make the Netlify CMS UI fully responsive. 

This pull request only addresses a small part of #2984 and there are several more issues that will need to be resolved before the issue is fully solved.

**Changes**

- Introduced media queries object in `packages/netlify-cms-ui-default/src/styles.js`
- Introduced `FloatingActionButton` component with individual `FabItem`'s
- Modified Header component to allow use of Hooks

### CODE REVIEW

**Comment by erquhart** [comment]
So excited to see this! I’m going to give it a proper review tomorrow, but I wanted to let you know right away that we can’t implement hooks until our next major release, as it breaks the CMS when multiple instances of React are active in the same DOM. Gotta keep it old school for now 😣

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alexbuiltit** [comment]
Hey Shawn

So sorry about that I should've realised or at least mentioned it in the slack community! 

Do you know how far away you are from being able to use hooks?

I can refactor this to remove the hooks, it shouldn't take too long.

**Comment by erquhart** [comment]
No reason you would have known that, it isn’t documented anywhere - we’ll be able to use them once our next major release is out, not sure when that will be as we keep making everything backwards compatible.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by erquhart** [comment]
Need to determine why the build isn't completing.

**Comment by alexbuiltit** [comment]
The build completes for me locally. 

Do you think its worth me closing this pull request and opening a new one when I have implemented these features without hooks?

**Comment by erquhart** [comment]
I believe some oddities in the your branch history threw off our change detection - just rebased it, should work now. You can push the non-hooks updates to this same branch.

**Pull request closed without merging**
