### PR TITLE
fix(widget-relation): set initial metadata value

### LINKED ISSUE #4177: Missing fieldMetadata content for multiple relation widget in preview
I cannot show the content of a multiple relation widget inside a custom preview, since the fieldMetadata prop doesn't contain the data anymore.

**To Reproduce**
1. Create a relation field on a collection type with multiple true, referencing another collection type (es. post authors)
2. Populate the related entry (es. create some authors)
3. Populate the relation widget referencing the entry (es. insert in blog post related authors)
4. Register a custom preview component for the entry with the relation field

**Expected behavior**
The props passed to the preview component should contain the data for the relation entities, nested inside the fieldMetadata prop. This should allow the preview component to display the entry like in production. The expected content is like in https://github.com/netlify/netlify-cms/issues/2434#issuecomment-510563966.

**Applicable Versions:**
 - netlify-cms-app version: 2.14.19
 - Git provider: GitHub
 - OS: Windows 8
 - Browser version: latest Chrome
 - Node.JS version: 12.16.1

**Additional context**
The bug doesn't appear in netlify-cms-app 2.14.18. By exclusion, in my investigation I think it was probably introduced in #4063.

### PR DESCRIPTION
**Pull request by barthc**
Closes #4177

### CODE REVIEW

**Review by erezrokah — APPROVED** [review]
Thanks @barthc

**Comment by equivalentideas** [comment]
Thanks all. Has this been released yet? What's the best way to tell that for this project? Thanks :bouquet:

**Comment by erezrokah** [comment]
Not release yet, we'll try get it out today.
You can click the merge commit link to see which tags include it:
image
https://github.com/netlify/netlify-cms/commit/4a510f3a9bc3ebdbd03d2971b7bf5fdba19a102c

currently the merge commit in only in the master branch.

Here is an example for a commit that has been released:
https://github.com/netlify/netlify-cms/commit/633a452e88b6bfd8fec2eda0334c4077d2e7c01b

**Comment by equivalentideas** [comment]
Thanks @erezrokah that's very clear :+1:

**Pull request merged**
