### PR TITLE
WIP: Media library thumbnails

### PR DESCRIPTION
**Pull request by owenhoskins**
WIP for #946

- Implementation of pica.toCanvas to generate thumbnails on the fly in `MediaLibrary/CardImage.js`
- Using react-intersection-observer in `EditorWidgets/GalleryPreview` to throttle the toCanvas calls
- Using react-virtualized in the `MediaLibrary` to handle large sets of data and also throttle toCanvas calls

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit c2d491e179309542f5267a2bda535c7f0b7a1469

https://deploy-preview-1230--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit c2d491e179309542f5267a2bda535c7f0b7a1469

https://deploy-preview-1230--cms-demo.netlify.com

**Comment by ro-savage** [comment]
@owenhoskins - Will this allow users to upload and previews images without them being directly uploaded to github master branch?

**Comment by erquhart** [comment]
No, just performance improvements for the media library interface.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mbergeronupgrade** [comment]
Waiting for this mostly to fix https://github.com/netlify/netlify-cms/issues/787

**Comment by tech4him1** [comment]
@owenhoskins Let me know if you want any help on this!

**Comment by owenhoskins** [comment]
@tech4him1 So glad you asked, that'd be awesome! I can hit you up on Gitter tomorrow or sometime this week? I finally got clear of a few things so this is coming back in focus!

**Comment by erquhart** [comment]
@owenhoskins going to go ahead and close this as stale, but please comment to re-open if you dig any further on it!

**Pull request closed without merging**
