### PR TITLE
Fix link to extending.md

### PR DESCRIPTION
**Pull request by ryanclarke**
The ".md" filetype was missing from the link path.

### CODE REVIEW

**Comment by erquhart** [comment]
A root relative path is better, actually, same way I did it in my latest PR. Not sure if we have a consistent approach across the docs.

**Comment by erquhart** [comment]
So here's what I'm seeing:

* The [docs site](https://netlifycms.org) is our primary documentation, so we should leave links without extension so they continue working there
* To fix links within the docs, we'll probably need to write a Markdown Magic [plugin](https://github.com/DavidWells/markdown-magic#plugin-example) on the docs site [repo](https://github.com/netlify/netlify-cms-www) to transform `.md` extension links.
* Once the plugin is in place, this PR will be eligible for merge. Any similar links should be updated at that point as well.

We may also consider other means for transforming source repo docs to html, but a quick search did not reveal anything promising.

**Comment by verythorough** [comment]
We can likely look to the docs implementation used by Serverless, primarily coded by @DavidWells, who also created Markdown Magic.

They keep docs in the repo, as in this page (note the link at the bottom points to an .md file)
https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/installation.md

Then use those files to generate the main site, as in this page (with no extension on the last link)
https://serverless.com/framework/docs/providers/aws/guide/installation/

I don't think they use Markdown Magic as a separate entity, but have it integrated into the code (before MM was broken out). Code for content importing and conversion can be found in here:
https://github.com/serverless/site/tree/master/scripts/docs

**Comment by erquhart** [comment]
@verythorough good find - the conversion happens here: https://github.com/serverless/site/blob/master/scripts/docs/update-doc-content.js#L55

**Comment by erquhart** [comment]
This will be properly fixed under #511. Closing.

**Pull request closed without merging**
