### PR TITLE
fix: preview show error stack trace

### LINKED ISSUE #5907: Preview show error when change name of Cover Image field
[](url)I am using the default config.xml, when I change the name of the cover image field to "featureImage" like below:
` - label: 'Cover Image'
        name: 'featureImage'
        widget: 'image'
        required: false
        tagname: ''`

the preview feature show this error:
Screen Shot 2021-10-17 at 22 53 46

Is this a bug or I must have a field with the name "image".
Thank you.

### PR DESCRIPTION
**Pull request by devnamrits**
Closes #5907 #4070

Summary:
It will elaborately describe the error by showing the stack trace of the error.

As of now, only the error message is being shown in the UI which makes it difficult to debug things in the app.

**Test plan**
Screenshot 2022-03-08 at 9 50 07 PM

**Checklist**

Please add a `x` inside each checkbox:

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x] Code is formatted via running `yarn format`.
- [x] Tests are passing via running `yarn test`.
- [ ] The status checks are successful (continuous integration). Those can be seen below.

### CODE REVIEW

**Comment by devnamrits** [comment]
@erezrokah 
I have raised draft PR. What's next?? Will it be merged?? 
Or, meanwhile, I've to wait?? If I've to wait then can I jump to other issues??

Please explain the further procedure. Sorry for being so silly.

**Comment by erezrokah** [comment]
Thanks @devnamrits, give me some time to test this.

You can look at other issues if you'd like

**Comment by devnamrits** [comment]
@erezrokah 
Thank you for your kind response. Meanwhile, I'm looking into other issues.

**Comment by devnamrits** [comment]
@erezrokah Looking into this.

**Comment by devnamrits** [comment]
@erezrokah Created a new state variable named as errorTitle because while creating the issue URL we're using just errorMessage rather than using the whole error stack. Also since we're generating snapshots for tests we run. In the case of ErrorBoundary.js, we're generating a snapshot of the error UI which will contain the error trace. So the snapshots will contain those error traces as well which will vary from user to user due to different local directory configurations. Hence, after updating test snapshots, all tests are passing.
Screenshot 2022-03-16 at 7 55 01 PM

**Comment by erezrokah** [comment]
Thanks for this @devnamrits, I removed the snapshot validation as it does more harm than good in this case.
I also added some logic to cleanup the stack trace, see 
image

**Pull request merged**
