### PR TITLE
If no lable is supplied, use the name.

### PR DESCRIPTION
**Pull request by m-henderson**
**- Summary**
This PR fixes https://github.com/netlify/netlify-cms/issues/1256 .
If a label is not supplied within the configuration then the name will be used as the label of the widget. 

**- Test plan**
1. Add this to your config.yml
`- name: "Test", widget: "markdown"`
you will see that a label is added to your widget. The cms takes the name of your widget and generates a label based off that name. 

Before this PR, you had to specify a label when creating a widget. If you did not supply a label then the widget would display without a label, like this: 
image

The code changes in this PR allow for the CMS to use the name of the widget as a label if no label is supplied; like this: 
image

**- Description for the changelog**

If a widget does not have a label the CMS will generate one based on the widget name.
**- A picture of a cute animal (not mandatory but encouraged)**
img_0510

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 66dfb955945788b92164fb213b2f0fa48e13f2b2

https://deploy-preview-1553--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 66dfb955945788b92164fb213b2f0fa48e13f2b2

https://deploy-preview-1553--cms-demo.netlify.com

**Comment by erquhart** [comment]
Thanks @m-henderson!

Here are a few other areas that need this change:

```
packages/netlify-cms-widget-list/src/ListControl.js
265:    const label = field.get('label');
266:    const labelSingular = field.get('label_singular') || field.get('label');

packages/netlify-cms-core/src/components/Editor/EditorPreviewPane/EditorPreviewPane.js
86:          <strong>{field.get('label')}:</strong> {value}
```

**Comment by m-henderson** [comment]
@erquhart ok. I will make these changes when I can and then push to this same branch.

**Comment by m-henderson** [comment]
@erquhart I pushed the changes. could you check them out when you get a chance? we should be good to go. Let me know if you have any questions or concerns.

**Comment by m-henderson** [comment]
@erquhart I pushed the changes. could you check them out when you get a chance? we should be good to go. Let me know if you have any questions or concerns.

**Comment by m-henderson** [comment]
@erquhart I pushed the changes. could you check them out when you get a chance? we should be good to go. Let me know if you have any questions or concerns.

**Comment by Benaiah** [comment]
@m-henderson I've manually rebased your changes onto the current master branch and pushed that here: https://github.com/benaiah/netlify-cms/tree/1256-make-field-label-optional - that branch should be ready to merge if you reset your PR branch to it.

**Comment by erquhart** [comment]
I do not remember deleting comments, that's weird.

**Pull request merged**
