### PR TITLE
refactor: mutate config in normalizeConfig and handleLocalBackend fns

### PR DESCRIPTION
**Pull request by smashercosmo**
**Summary**

Another atomic PR to make https://github.com/netlify/netlify-cms/pull/4776 easier to merge

**Test plan**

Run current tests

### CODE REVIEW

**Comment by smashercosmo** [comment]
Seems like latest commits from master cause e2e tests to fail

**Comment by erezrokah** [comment]
> Seems like latest commits from master cause e2e tests to fail

👀

**Comment by smashercosmo** [comment]
Hm... now I have no idea why it fails. When I run e2e tests locally they pass.

**Comment by smashercosmo** [comment]
@erezrokah I think I'm gonna need your help with it ((

**Comment by erezrokah** [comment]
Sorry for the delay @smashercosmo. I'm clearing some stuff off my plate and we'll review the PRs this week.

**Comment by erezrokah** [comment]
@smashercosmo This seems like an issue with Cypress https://github.com/netlify/netlify-cms/pull/4846/checks?check_run_id=1791036988#step:7:1195

**Comment by erezrokah** [comment]
I'm going to try and revert the Cypress version per https://github.com/cypress-io/cypress/issues/14663

**Review by erezrokah — APPROVED** [review]
Sorry for the delay @smashercosmo, thank you for another great PR which makes our codebase much cleaner and easier to understand.

I decided to keep the methods non-mutating as personally I believe they make the code easier to follow.

**Comment by smashercosmo** [comment]
hm... @erezrokah I understand you concern, but if you want to keep methods immutable, I would suggest we just use immer instead of object spreads.

**Comment by erezrokah** [comment]
> hm... @erezrokah I understand you concern, but if you want to keep methods immutable, I would suggest we just use immer instead of object spreads.

That's a good point. I wasn't sure if the the nesting was deep enough to justify that.

**Comment by smashercosmo** [comment]
@erezrokah another question not directly related to this PR but to netlify-cms code style in general. I noticed that you're using both function expressions and function declarations across codebase, but seems like there is no logic in when either is being used. I would propose to use function expressions only in inline callbacks and declarations in all other cases. Because it's easier to distinguish function from a simple variable when function is declared as declaration.
Bad:
const someVar = 1
const someFn = () => { ... }

Good:
const someVar = 1
function someFn() { ... }

**Comment by erezrokah** [comment]
Another good point. We mostly care about consistency (which we don't have).
What do you think about adding https://eslint.org/docs/rules/func-style to our linting configuration?

**Comment by smashercosmo** [comment]
Well, surely I can, but should I then fix all of the eslint errors? 🙂

**Comment by erezrokah** [comment]
I'm mostly interested on how many errors we get :) we can apply the rule for specific parts of the codebase and slow fix errors

**Comment by smashercosmo** [comment]
618 errors 🙂 I'll check if it can be fixed by some codemod

**Pull request merged**
