### PR TITLE
Update examples.md

### PR DESCRIPTION
**Pull request by DemoMacro**
**Summary**

**Test plan**

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 757b6e91659a74df8295b4367cebe0d57d3d8794

https://deploy-preview-1993--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 757b6e91659a74df8295b4367cebe0d57d3d8794

https://deploy-preview-1993--cms-demo.netlify.com

**Comment by DemoMacro** [comment]
It is a commit for adding some examples with Netlify CMS

**Comment by talves** [comment]
@DemoMacro do you have examples that use the latest versions of NetlifyCMS ^2.x ?

**Comment by DemoMacro** [comment]
Emmm...How is it?

**Comment by erquhart** [comment]
Looks great, thanks!

**Pull request merged**
