### PR TITLE
Add multi-format frontmatter parser

### LINKED ISSUE #227: Use jonschlinkert/gray-matter for front-matter?
Improvement Suggestion:

https://github.com/jonschlinkert/gray-matter looks like a really robust solution for multi format front-matter. Maybe we should try to use it on the CMS?

### PR DESCRIPTION
**Pull request by josephearl**
**- Summary**

Adds the ability to read front matter in TOML and JSON formats. Fixes #227.

Currently `sortedKeys` is not implemented when stringifying, neither are the custom types when parsing or stringifying since these were YAML specific. I can add these if it's a blocker.

**- Test plan**

Added tests for the new parser.

**- Description for the changelog**

Added dependency on [preliminaries](https://www.npmjs.com/package/preliminaries).
Added tests for basic parser cases expected to work in netlify-cms.

**- A picture of a cute animal (not mandatory but encouraged)**

A cute koala

### CODE REVIEW

**Comment by calavera** [comment]
I feel like the `yaml-frontmatter.js` and `yaml-frontmatter-test.js` files should be renamed to something else. Beside that, this change is fantastic, thank you!

**Comment by josephearl** [comment]
Renamed to `frontmatter.js` and `frontmatter.spec.js`.

**Comment by erquhart** [comment]
Hey @josephearl - awesome work on this, mate! I do wonder, though, if it wouldn't be better to attempt getting these changes into gray-matter directly. Thoughts?

**Comment by josephearl** [comment]
@erquhart There's a PR that's been open in that repository https://github.com/jonschlinkert/gray-matter/pull/15 a while now to do some of the same things (separate out at the parsers), so although it would be good to get some of the changes merged upstream -- I'm not sure how quick a process that will be, if it happens.

**Comment by erquhart** [comment]
Fair point, that repo does seem to be slow moving as of late.

**Comment by erquhart** [comment]
@josephearl last thought on this - might be good to at least raise an issue in gray-matter and give a heads up. You put in some serious work, and the community will likely benefit more from it if you can get the changes in on that repo. I'm guessing from the lack of movement there that the author could use some help.

**Comment by josephearl** [comment]
https://github.com/jonschlinkert/gray-matter/issues/38

**Comment by jonschlinkert** [comment]
> I'm guessing from the lack of movement there that the author could use some help.

indeed! I would love some help on gray-matter! @josephearl you've done some great work, I added you as a collab on gray-matter. (sorry for the very late response!)

**Comment by jonschlinkert** [comment]
Hi @erquhart, I just pushed up [3.0 of gray-matter](https://github.com/jonschlinkert/gray-matter/commit/2c1b5ced084d9480f49816bf4aae1353cd319686), which adds support for excerpts, and simplifies adding parsers/stringifiers for other formats. 

Fwiw, after reviewing preliminaries more, I don't see anything that it really added even to the previous version of gray-matter, it looks like the code was mostly just reorganized into sub-projects (and the gray-matter pr that ["had been open a while"](https://github.com/netlify/netlify-cms/pull/348#issuecomment-293051272) was an anomoly on gray-matter. There had been other issues and updates since that pr was made, so I'm not sure why it was singled out). 

In any case, would you be open to a pr to use gray-matter 3.0 directly instead of a fork?

**Comment by erquhart** [comment]
Hey @jonschlinkert - definitely, that was the hope from the beginning. Thank you!

**Comment by jonschlinkert** [comment]
great, I'll put a pr together as soon as I have a chance. thanks!

**Pull request merged**
