### PR TITLE
Adding Preact CLI as a starter option

### PR DESCRIPTION
**Pull request by prateekbh**
**Summary**
Adds Preact CLI as an option for netlify starter.

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by erquhart** [comment]
Thanks Prateek, trying this out soon.

**Comment by prateekbh** [comment]
Thank you so much :)
Does this auto deploy to https://www.netlifycms.org/docs/start-with-a-template/?

**Comment by prateekbh** [comment]
nvm found my answer

**Comment by erquhart** [comment]
Lol sorry @prateekbh my notifications are off the charts - yep, Preact CLI is front and center 🎉

**Pull request merged**
