### PR TITLE
Update uploadcare plugin

### PR DESCRIPTION
**Pull request by nd0ut**
**Summary**

- Include Widget and EffectsTab using NPM instead of script load (now it is working in strict mode)
- Pass `integration` option to the widget to collect usage statistics

### CODE REVIEW

**Comment by nd0ut** [comment]
@erquhart I thinks there some memory problems with CI environment

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Build exceeded maximum allowed runtime
```

Could you check it please?

**Comment by erquhart** [comment]
(So to clarify, this PR requires updates to the Uploadcare unit test file before it can be merged.)

**Comment by nd0ut** [comment]
@erquhart oh, sorry, my fault, fixed it

**Comment by erquhart** [comment]
@nd0ut this had to be reverted as it caused the uploadcare scripts to auto initialize for all Netlify CMS users, whereas injecting script tags from our own uploadcare extension `init` function loaded these libs on demand. The issue is made obvious by the console messaging about missing an uploadcare api key.

We also can't use dynamic imports for the [same reason](https://github.com/netlify/netlify-cms/pull/1889#issuecomment-462010680) that lazy loading won't work for Netlify CMS in general.

It'd be great to load your lib from npm, it just needs to provide a manual initialization method rather than bootstrapping on import.

**Pull request merged**
