### PR TITLE
Update quick-start.md

### PR DESCRIPTION
**Pull request by StarfallProjects**
**- Summary**
Amended the github link to go the the CMS repo, instead of just the github homepage.

**- What existing problem does the pull request solve?-**
Makes the link more useful for people using the Quickstart

**- Test plan**
Manually checked the new URL works

**- Description for the changelog**
Amended the github link to go the the CMS repo, instead of just the github homepage.

**- A picture of a cute animal (not mandatory but encouraged)**
rattie

### CODE REVIEW

**Comment by verythorough** [comment]
Thanks for the update (and love the pic)! 

For the link, though, the intention of the sentence is that the CMS user's files must be stored in a repo on GitHub, in the user's own account. I feel like linking to the Netlify CMS repo in that instance could cause confusion about where the files should be stored. Perhaps it makes more sense to remove the link altogether.

Alternatively, if having a handy link to the repo is the goal, we could link the words "Netlify CMS" at the beginning of the paragraph to the repo. Might be weird to link the project on the project's own site, though. And there *is* a link to the repo in the header of every page. (Not to mention that some people read these files directly *in* the repo.) I have wondered if we should change the "Fork me on GitHub" button to say "Find me on GitHub," since a person isn't typically forking unless they're contributing.

What do you think, @StarfallProjects ?

**Comment by StarfallProjects** [comment]
Good point. It would definitely be helpful to have a link to the Netlify CMS repo somewhere on that page though.

**Comment by tech4him1** [comment]
@verythorough I would really like if we changed "Fork Me on GitHub" to something else, I think that is overused a lot, especially since we are not actually wanting the user to fork the repo to use it.

**Comment by erquhart** [comment]
@tech4him1 agreed. @StarfallProjects the (admittedly obtuse) Fork me on GitHub button is present on every page in the header, that should suffice for this.

@verythorough how about "View on GitHub"? I typically just use the GitHub icon or the word "GitHub" for this sort of link, but a phrase makes more sense on the button we currently have.

**Comment by tech4him1** [comment]
Maybe we could even do something like "Contribute on GitHub", it just depends on what kind of users we want to draw to that vs going through our main docs.

**Comment by erquhart** [comment]
Moved to: https://github.com/netlify/netlify-cms-www/issues/61

**Pull request closed without merging**
