### PR TITLE
feat(netlify-cms-core): add basic route code-splitting

### PR DESCRIPTION
**Pull request by alexandernanberg**
**Summary**

Code-split the main routes into separate chunks to improve both network and cpu performance. Only downside atm is that we have to show 2 spinners (first the config loading and then the chunk loader) instead of one. IIRC concurrent rendering will allow us to solve this later. 

**Test plan**

Tested locally and didn't notice any problems.

### CODE REVIEW

**Comment by erquhart** [comment]
Nice! I always assumed code splitting wouldn't work with our single bundle requirement, didn't realize the webpack handles adding script tags, and with so little setup. Really awesome to see in action!

If you can address the merge conflict we can get this in 👍👍

**Comment by erquhart** [comment]
Update: I'm going to merge #1858 before this one, which might break it, honestly not sure. Maybe if rollup leaves the dynamic imports and webpack comments alone it will still work as is. Merging that one soon.

**Comment by alexandernanberg** [comment]
Ah probably a good idea! I can revisit this once that PR gets merged and investigate if this is possible with rollup as well.

**Comment by erquhart** [comment]
argh why does github produce a merge commit when you resolve conflicts in their editor 🙄

**Comment by erquhart** [comment]
Status on #1858 is unclear, going ahead with this one. Thanks again @alexandernanberg 👍

**Comment by talves** [comment]
Awesome change, I am wondering if it is going to make a big improvement on performance.
image

**Comment by erquhart** [comment]
not by the numbers lol, but it's a start!

**Comment by erquhart** [comment]
@alexandernanberg this had to be reverted, as it triggered [chunk-pocalypse](https://github.com/netlify/netlify-cms/issues/2074#issuecomment-462002049) - it requires the developer to copy over the additional files to their site. We'll need to think through making this doable with our current single script distribution model.

**Pull request merged**
