### PR TITLE
Add example of Netlify CMS website

### PR DESCRIPTION
**Pull request by robertcoopercode**
**Summary**

I've added an example of an [open source website](https://gatsby-netlify-cms-example.netlify.com/) that is built using Netlify CMS.

**A picture of a cute animal (not mandatory but encouraged)**
1b270bf09bea7706fe6d115666805620

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit c8df50bd5ae72c4549d1f667cbffcc5925e5916d

https://deploy-preview-1957--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit c8df50bd5ae72c4549d1f667cbffcc5925e5916d

https://deploy-preview-1957--cms-demo.netlify.com

**Comment by tomrutgers** [comment]
This is absolutely awesome! Thanks for taking the time and effort to do both a demo and a blog post. I've requested one minor change, happy to merge when it's resolved 👌

**Comment by robertcoopercode** [comment]
You're very welcome! I don't see you requested change @tomrutgers. Are you sure you submitted your review?

**Comment by robertcoopercode** [comment]
@tomrutgers PR updated 👍

**Comment by tomrutgers** [comment]
Awesome, thanks!

**Pull request merged**
