### PR TITLE
custom logo support for login page

### LINKED ISSUE #964: Feature Request: Custom Logo for login page
Hello,

I would like to set a custom logo and a custom text to brand the login page of Netlify CMS.

Best,\
Robert

### PR DESCRIPTION
**Pull request by zolamk**
**- Summary**

Allow custom logo for login screen, closes #964 

**- Test plan**
- Tests are passing
- Manually Tested login page

screenshot_2018-06-25_12-25-49

**- Description for the changelog**
Added a configuration option that allows the user to change the logo displayed on login screen

**- A picture of a cute animal (not mandatory but encouraged)**
surrender-9442903

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 17a7c8ecc72797ae691a70006c99d1f1ddf0bb16

https://deploy-preview-1465--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 17a7c8ecc72797ae691a70006c99d1f1ddf0bb16

https://deploy-preview-1465--cms-demo.netlify.com

**Comment by erquhart** [comment]
Thanks for this! Definitely important to be able to brand this, especially for client work.

A few thoughts:
1. I think it benefits everyone that implements Netlify CMS to spread the word. Wondering if we should add a small Netlify CMS logo in the bottom right that wouldn't be subject to white labeling? Anyone could manually remove if they really wanted to, obviously, but I'm betting most will be fine with that.
2. We should have a central authentication page component that houses the custom logo rather than having each individual backend pass it around.
3. The Icon UI component shouldn't be impacted.

So I think a few things need to happen before we can do this correctly.

cc/ @Benaiah @tech4him1 @talves thoughts?

**Comment by talves** [comment]
> 1. I think it benefits everyone that implements Netlify CMS to spread the word.

For sure! We need to make it easy for the developer or company to give attribution to the project. If a customer does not want to show, then we should make it easy for them to exclude it also.

**Comment by zolamk** [comment]
> I think it benefits everyone that implements Netlify CMS to spread the word.

Yeah the NetlifyCMS logo at the bottom right should give the appropriate credit and it could be hidden with css if deemed necessary.

**Comment by tech4him1** [comment]
Agreed! We may legally have to credit anyway due to licensing anway (including for some of the dependencies we use).

**Comment by jclusso** [comment]
Any updates on this?

**Comment by mk0r** [comment]
Just wondering how close this is to being implemented. Its a big deal for many use cases

**Comment by tech4him1** [comment]
In my understanding, someone needs to take this PR and re-build it for the new CMS mono-repo format, making sure to incorporate @erquhart's suggestions above: https://github.com/netlify/netlify-cms/pull/1465#issuecomment-400478220.

**Comment by erquhart** [comment]
Superseded by #964.

**Pull request closed without merging**
