### PR TITLE
Add missing history package

### PR DESCRIPTION
**Pull request by josephearl**
**- Summary**

With a fresh clone of master `npm run build` gives me the error:

```
ERROR in ./routing/history.js
Module not found: Error: Cannot resolve module 'history' in /Users/Joseph/Workspace/netlify-cms/src/routing
 @ ./routing/history.js 8:15-33
```

**- Test plan**

Before: builds with error.
After: no error when building.

**- Description for the changelog**

Added missing [history](https://www.npmjs.com/package/history) package for `createHashHistory` in `history.js`.

### CODE REVIEW

**Comment by josephearl** [comment]
This was with `npm install`, with `yarn` it works fine first time.

**Comment by erquhart** [comment]
No, you're right - we're explicitly importing from the `history` package, it should be a dep. Good catch.

**Comment by josephearl** [comment]
Changed to ^2.1.2

**Comment by josephearl** [comment]
Travis failed due to an authentication issue, might want to retry?

**Comment by erquhart** [comment]
Yeah we're aware of that, working on it now. I'll rerun the test build when it's resolved.

**Comment by calavera** [comment]
LGTM. Thanks!

**Pull request merged**
