### PR TITLE
fix: Fix the umd builds

### PR DESCRIPTION
**Pull request by talves**
**Summary**

- One fix to import the backends correctly
- Fixes for a caps issue with the Redux folder name cases vs alias vs module import (alias added to resolve)
- Fix the localForage folder case vs alias vs module import (alias added to resolve)
- Fix a path import issue from '.' to './index'

**Test plan**

Same tests as original PR #2141

**A picture of a cute animal (not mandatory but encouraged)**
🐢

### CODE REVIEW

**Comment by talves** [comment]
@erquhart I found these issues. Not all breaking, because the case issues are windows issues mostly.

I am working on an es6 bundle PR and these things showed up right away, so it was a good thing. 😜

**Comment by talves** [comment]
@erquhart I keep forgetting to ask you if you want me to return those export names back for the backends or follow the same export names as the widgets, so we are ready for them to also have a register name as 'controlComponent'. Although they are not really components as much as control class modules.

**Comment by erquhart** [comment]
Oh yeah, I meant to content on that in the original pull requests, the nomenclature should be changed to be specific to backends as "control" doesn't really apply there.

Awesome to hear you're working on ES6 modules!!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by talves** [comment]
Ok, no problem. I wonder if they should follow a common for export like the widgets, so we can make the API the same way?

I will do it first thing in the am.

**Pull request merged**
