### PR TITLE
feat: Shiny new ES module builds

### PR DESCRIPTION
**Pull request by talves**
**Summary**

This PR will expose ES module code into the published libraries under `dist/esm`.

**Test plan**

Needs to make sure there are builds being produced from the ES modules and not the umd code.

- [x] Test main bundle to make sure everything is included, because there was a 20% size drop
- [x] Make sure all the bundles are creating valid module builds. A good test would be to use parcel to do a full build from the published libraries.
- [x] Check to make sure all exports and peers working properly on bundles.
- [ ] [Make a decision on handling a deep external import][1] from `src` in the Number widget.

**A picture of a cute animal (not mandatory but encouraged)**
🐉

[1]: https://github.com/netlify/netlify-cms/pull/2215#issuecomment-474607337

### CODE REVIEW

**Comment by erquhart** [comment]
This is incredible @talves!!!

**Comment by erquhart** [comment]
Webpack analyzer outputs:

- [2.6.1](https://upbeat-newton-71f68a.netlify.com/)
- [master without this PR](https://blissful-shockley-550837.netlify.com/)
- [this PR](https://brave-bhabha-aba248.netlify.com/)

**Comment by talves** [comment]
@erquhart testing the building off of esm published libraries:

The following code does not get replaced, because it is a webpack replacement.

The esm build could use the transform `babel-plugin-transform-define` and pull the version from the config. I will do this to move my test forward and we can discuss.
 .
From:

```javascript
  /**
   * Log the version number.
   */

  if (NETLIFY_CMS_VERSION) {
    console.log(`netlify-cms ${NETLIFY_CMS_VERSION}`);
  } else if (NETLIFY_CMS_CORE_VERSION) {
    console.log(`netlify-cms-core ${NETLIFY_CMS_CORE_VERSION}`);
  }

```

To:

```javascript 
  if ("esm-v2.6.2-beta.0") {
    console.log(`netlify-cms ${"esm-v2.6.2-beta.0"}`);
  } else if ("esm-v2.8.1-beta.0") {
    console.log(`netlify-cms-core ${"esm-v2.8.1-beta.0"}`);
  }

```

**Comment by talves** [comment]
Also, here is the code reference from the `NumberConrol.js` widget that breaks an esm import to outside linking. This needs to be fixed and decision made on how we want to handle. 

My proposal is below:

From:

```javascript
import ValidationErrorTypes from '
```

To:

```javascript
const ValidationErrorTypes = {
  PRESENCE: 'PRESENCE',
  PATTERN: 'PATTERN',
  RANGE: 'RANGE',
  CUSTOM: 'CUSTOM'
}
```

**Comment by talves** [comment]
@erquhart I got it!!! The test for building off the ES modules PR is working using parcel!
https://github.com/talves/netlify-cms-parcel-example
https://cms-parcel-example.netlify.com
✨✨🚀🔥
Build log: https://app.netlify.com/sites/cms-parcel-example/deploys/5c9168baf448f80008be2ea1
That pretty much tests the builds 100%, because it used the dist/esm builds to get the modules for the build. The bundles are better now for parcel and takes the right amount of time 93s vs 383s on umd builds. Also the bundle dropped in size appropriately. Great stuff!

**Comment by erquhart** [comment]
Tony this is crazy awesome, can't wait to get it merged. Anything you need from me? I know you mentioned some odds and ends in chat, but wanted to get specifics here so I don't lose track. UMD builds already made releases and the app itself faster, ready to go all the way!

**Comment by talves** [comment]
I have been getting some weird side affects when trying to [bring these modules into a CRA app](https://github.com/ADARTA/netlify-cms-react-example).

I am not sure if this is just a devServer isssue in CRA, so I may eject and try it on a branch. If I do a production build things work fine. It is worrying me that we might have some issues with these builds, because I have not tested every little thing in the parcel build.

**Comment by talves** [comment]
So, If we bring this into master, I am afraid we will get stuck in beta until these things are ironed out. What are your thoughts?

**Comment by talves** [comment]
@erquhart OMG. It just occurred to me that this might just be an issue with my fs backend and the new api changes! I will check that tonight!

**Comment by talves** [comment]
@erquhart (and others) Sorry for all the spamming. It WAS the fs backend that needed to be updated for the api changes for media! There are so many moving parts that I was getting caught up in misreading the errors as issues with the esm builds using `ref=`. Although we will need to address these eventually, just not required for this release.

Although there are errors showing up during development, most are the ref warnings and prop-types that we can deal with as we go. They have always been there, just more apparent now with the new version of React and developing from a transpiled version.

One more successful test: [A full create-react-app example using the ES modules][1]

### Included in the test...
- uses all the test data from the test-repo backend, but setup for the file-system backend.
- tests the ability to run a backend registered and built outside of the cms using react hooks.
- All the custom previews converted to use React Hooks for testing the single instance of React!
- imports the libraries individual for now, until we decide what to do with providing a BARE library or not. But this was a good test.

I would like to release this as beta soon also, so we can make sure the github, git-gateway backends are all working properly.

What a relief it was to get this version of tests up and running. 🚀

[1]: https://github.com/ADARTA/netlify-cms-react-example

**Pull request merged**
