### PR TITLE
Add `netlify-cms-oauth-provider-node` external OAuth client

### PR DESCRIPTION
**Pull request by bericp1**
**Summary**

Adding in [bericp1/netlify-cms-oauth-provider-node](https://github.com/bericp1/netlify-cms-oauth-provider-node) to the "External OAuth Clients" documentation.

Built out primarily to support serverless platforms, specifically Zeit now but also supports generic handlers for any Node HTTP server or Node serverless environment.

**Test plan**

No tests need. Only documentation updates.

**Note**

I tried to edit these docs from the admin panel via the "Edit this page" link but for some reason the Backends section of the documentation wasn't showing up 🤷‍♂

### CODE REVIEW

**Comment by erezrokah** [comment]
Hi @bericp1, thanks for this. Just to make sure I understand the purpose of the library, it is intended to support multiple providers? Hence supplying function creators instead of just the functions?

**Comment by erezrokah** [comment]
> I tried to edit these docs from the admin panel via the "Edit this page" link but for some reason the Backends section of the documentation wasn't showing up

Thanks, we recently changed the structure of the docs, but forgot to update the CMS config

**Comment by bericp1** [comment]
> Hi @bericp1, thanks for this. Just to make sure I understand the purpose of the library, it is intended to support multiple providers? Hence supplying function creators instead of just the functions?

Yes providers in the sense of hosting options. The current external OAuth client listed on the page for Node explicitly creates an express server for handling the whole OAuth flow: https://github.com/vencax/netlify-cms-github-oauth-provider/blob/master/index.js.

My use case was to be able to run a `netlify-cms`-powered static site on Zeit Now which uses serverless functions so a long-running express server didn't work for me. I wanted to abstract out the behavior a bit so that one could create separate serverless functions: one to kick off the flow and one to complete the flow.

Check out the Zeit now example which creates 2 api endpoints to do this (`/api/begin` and `/api/complete`): https://github.com/bericp1/netlify-cms-oauth-provider-node/tree/master/examples/now

It also includes an example of integrating it into a generic long-running Node HTTP server as well for the sake of flexibility: https://github.com/bericp1/netlify-cms-oauth-provider-node/blob/master/examples/generic/index.js

**Comment by erezrokah** [comment]
By providers I was referring to this https://github.com/bericp1/netlify-cms-oauth-provider-node/blob/6c37139093c1a6b38a612c46628345823d9551ff/lib/providers/index.js#L6
and https://github.com/bericp1/netlify-cms-oauth-provider-node/blob/6c37139093c1a6b38a612c46628345823d9551ff/lib/handlers/generic.js#L21
which seems to be able to facilitate different git services (e.g. GitLab) in the future.

**Comment by bericp1** [comment]
> By providers I was referring to this https://github.com/bericp1/netlify-cms-oauth-provider-node/blob/6c37139093c1a6b38a612c46628345823d9551ff/lib/providers/index.js#L6
> and https://github.com/bericp1/netlify-cms-oauth-provider-node/blob/6c37139093c1a6b38a612c46628345823d9551ff/lib/handlers/generic.js#L21
> which seems to be able to facilitate different git services (e.g. GitLab) in the future.

Oh yeah totally, the genesis for me building this out was the need to run on Zeit Now but as I was building it out I wanted to make it as easy as possible to add additional providers in the future for sure. Should be pretty low effort to support i.e. GitLab due to the polymorphism there.

**Pull request merged**
