### PR TITLE
Fix a 404 link

### PR DESCRIPTION
**Pull request by kishaningithub**
Fix a 404 link [here](https://www.netlifycms.org/docs/authentication-backends/)

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 9bc79eb16e530225b31c767cf22d51e4d32bd35f

https://deploy-preview-1950--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 9bc79eb16e530225b31c767cf22d51e4d32bd35f

https://deploy-preview-1950--cms-demo.netlify.com

**Comment by tomrutgers** [comment]
The link seems to be working just fine. Could you try clearing your cache and test it again?

**Comment by kishaningithub** [comment]
@tomrutgers As you said this is now working fine. The relative path `../start-with-a-template` seems to work. Since this is the case why not we change this link `https://www.netlify.com/docs/identity/` to `../identity/` which happens to be in the same line ?

**Comment by tomrutgers** [comment]
Because that's on a different domain (netlify.com instead of netlifycms.org). Thanks for the confirmation!

**Pull request closed without merging**
